### ISSUE TITLE
意义不大, 貌似不支持context.getSystemService所支持以外以外的其他服务类型

### ISSUE THREAD

**Issue by 3ystem** [RikkaApps/Shizuku#101]
我在UserService中创建了一个"getBinder"方法, 在Shell进程中通过反射构造其他高阶api接口, 然后使用getBinder方法将高阶接口的asBinder传回到app层. 然而在app层的binder权限还是app层

**Comment by RikkaW** [comment]
你需要实现类似 https://github.com/RikkaApps/Shizuku/blob/master/server/src/main/java/moe/shizuku/server/ShizukuService.java#L197-L218 这样的一个转发过程（并且只是这样的目的根本不用用 UserService，拿到想要的 binder 用 ShizukuBinderWrapper 套起来用就行了）。

直接随便把 binder 发给使用者，使用者来用当然是以使用者的身份。

**Comment by 3ystem** [comment]
谢谢解答, 我再研究研究, 对binder一无所知. 研究了几天shizuku才对binder一知半解.

**Comment by 3ystem** [comment]
我是用UserService的原因是调用某些静态方法, 我想使用转发Binder的原因是因为有些对象太大(如Bitmap), 会被Binder截断? 所以我想通过直接转发Binder, 所以就卡在这个砍上了, 有些系统服务app层没有权限启动, 我想在在Shell端启动服务后然后将对应系统服务的Binder转发到app层来处理. 所以就卡在这个坎上了, 当然我这条路可能走得不对.

**Comment by RikkaW** [comment]
发送大东西首选看能不能直接发送 fd（Bitmap 内部在能发送 fd 时也确实是发 fd 的），不行就只能发送一个新的 binder 过去再通过那个 binder 分次接受（可以参考系统的 ParceledListSlice）

**Comment by 3ystem** [comment]
> 发送大东西首选看能不能直接发送 fd（Bitmap 内部在能发送 fd 时也确实是发 fd 的；是文件就直接发 fd，是一块内存就搜 shared memory binder 之类的关键字），不行就只能发送一个新的 binder 过去再通过那个 binder 分次接受（可以参考系统的 ParceledListSlice）

谢谢解答, 像你说的我用fd实现了bitmap的传输, 但是性能不理想.  为什么用ShizukuBinderWrapper包装"activity"以后, 可以在app层使用带有shell权限的IActivityManager, 但是非Context以外的其他Service用ShizukuBinderWrapper包装后却不可以

**Comment by 3ystem** [comment]
> > 发送大东西首选看能不能直接发送 fd（Bitmap 内部在能发送 fd 时也确实是发 fd 的；是文件就直接发 fd，是一块内存就搜 shared memory binder 之类的关键字），不行就只能发送一个新的 binder 过去再通过那个 binder 分次接受（可以参考系统的 ParceledListSlice）
> 
> 谢谢解答, 像你说的我用fd实现了bitmap的传输, 但是性能不理想. 为什么用ShizukuBinderWrapper包装"activity"以后, 可以在app层使用带有shell权限的IActivityManager, 但是非Context以外的其他Service用ShizukuBinderWrapper包装后却不可以

是因为我创建的UserService与Shizuku不属同一进程, 并不能像系统服务那样每个进程都可以获取到?

**Comment by RikkaW** [comment]
例子里有多进程应该怎么办
