### ISSUE TITLE
adb shell settings put system

### ISSUE THREAD

**Issue by ziyucao** [RikkaApps/Shizuku#102]
使用Shizuku API可以实现adb shell settings put system之类的功能吗

**Comment by RikkaW** [comment]
没有直接的，但可以自己取得 "settings" 这个 provider 并使用 provider 的相关方法（你可以探索通过 adb 执行 settings 之后都发生了什么

**Comment by wkbin** [comment]
> 使用Shizuku API可以实现adb shell settings put system之类的功能吗

有找到方法吗？
