### ISSUE TITLE
执行start.sh会提示没有权限访问

### ISSUE THREAD

**Issue by chx818** [RikkaApps/Shizuku#106]
PS E:\platform-tools> .\adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh
sh: /sdcard/Android/data/moe.shizuku.privileged.api/start.sh: Permission denied
机型iqoo7 OriginOS1.0（Android11）
尝试把start.sh挪到/sdcard会提示Starter file not exist，网络调试也不行因为设置不能分屏

**Comment by RikkaW** [comment]
在别处看到的方法：
开发者选项的最后有“强行将活动设为可调整大小”，打开它试试呢

**Comment by chx818** [comment]
可以启动，然后一锁屏就炸了…

**Comment by RikkaW** [comment]
USB 使用模式仅充电，再不行就只有大骂 vivo 并且记得下次买 Pixel（

**Comment by chx818** [comment]
usb依然提示无权限，无线adb反而直接卡在waiting for service彻底不能启动

**Comment by chx818** [comment]
等会......刚锁屏了一下还正常了.什么鬼...

**Comment by chx818** [comment]
问题解决，可以关闭issue了

**Comment by Thanasak-Sompong** [comment]
PS E:\platform-tools> .\adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/start.sh
sh: /sdcard/Android/data/moe.shizuku.privileged.api/start.sh: Permission denied
机型iqoo7 OriginOS1.0（Android11）
尝试把start.sh挪到/sdcard会提示Starter file not exist，网络调试也不行因为设置不能分屏

**Comment by THARADO** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

**Comment by Ti008** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

**Comment by TheMadPhysicist** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh
