### ISSUE TITLE
应用管理列表bug

### ISSUE THREAD

**Issue by Suci233** [RikkaApps/Shizuku#122]
自11.30之后的11.4和11.5应用管理都显示为空，应用里也无法调用权限

**Comment by RikkaW** [comment]
[shizuku-11.5.1.r587.e45ee5e-release.apk.zip](https://github.com/RikkaApps/Shizuku/files/6508446/shizuku-11.5.1.r587.e45ee5e-release.apk.zip)
稍微多加了一些 log，安装并重新启动服务，然后提供 log（

**Comment by Suci233** [comment]
> [shizuku-11.5.1.r587.e45ee5e-release.apk.zip](https://github.com/RikkaApps/Shizuku/files/6508446/shizuku-11.5.1.r587.e45ee5e-release.apk.zip)
> 稍微多加了一些 log，安装并重新启动服务，然后提供 log（

没找到log在哪😢

**Comment by RikkaW** [comment]
亲自使用 adb logcat

**Comment by Suci233** [comment]
> 亲自使用 adb logcat

啊这,我不会.....

**Comment by RikkaW** [comment]
跟着帮助的使用 adb 启动走，只是需要运行的指令变成 `adb logcat > 1.txt`。
然后之后再重新启动服务（

**Comment by tsaiajie** [comment]
红米K40 miui12.5 开启“USB 调试（安全设置） 关闭MIUI优化
我也是一样的 一开始搞了很多以为不行 然后看到这个试试看11.3的可以 
11.4之后就ANYWHERE一个可以在应用管理里面显示
小黑屋虽然不显示 但是可以使用 （没有授权他过）
安装狮 shizuku服务状态可用 但是本身的可用状态不行  然后我用酷安的一个都不能安装 自带的商店可以使用 直接文件管理器安装的话 应该是成功使用安装师把 反正出现的不是miui的安装界面
安装冰箱 点击那个使用shizuku 都不能点的。

**Comment by Suci233** [comment]
> 红米K40 miui12.5 开启“USB 调试（安全设置） 关闭MIUI优化
> 我也是一样的 一开始搞了很多以为不行 然后看到这个试试看11.3的可以 
> 11.4之后就ANYWHERE一个可以在应用管理里面显示
> 小黑屋虽然不显示 但是可以使用 （没有授权他过）
> 安装狮 shizuku服务状态可用 但是本身的可用状态不行  然后我用酷安的一个都不能安装 自带的商店可以使用 直接文件管理器安装的话 应该是成功使用安装师把 反正出现的不是miui的安装界面
> 安装冰箱 点击那个使用shizuku 都不能点的。

跟作者提供一下log吧，我还是不会弄log😵😵

**Comment by tsaiajie** [comment]
> > 红米K40 miui12.5 开启“USB 调试（安全设置） 关闭MIUI优化
> > 我也是一样的 一开始搞了很多以为不行 然后看到这个试试看11.3的可以
> > 11.4之后就ANYWHERE一个可以在应用管理里面显示
> > 小黑屋虽然不显示 但是可以使用 （没有授权他过）
> > 安装狮 shizuku服务状态可用 但是本身的可用状态不行  然后我用酷安的一个都不能安装 自带的商店可以使用 直接文件管理器安装的话 应该是成功使用安装师把 反正出现的不是miui的安装界面
> > 安装冰箱 点击那个使用shizuku 都不能点的。
> 
> 跟作者提供一下log吧，我还是不会弄log😵😵

日卡卡叫我们提供落鸽 但是我也不会啊 大佬你研究下啊

**Comment by Suci233** [comment]
> > > 红米K40 miui12.5 开启“USB 调试（安全设置） 关闭MIUI优化
> > > 我也是一样的 一开始搞了很多以为不行 然后看到这个试试看11.3的可以
> > > 11.4之后就ANYWHERE一个可以在应用管理里面显示
> > > 小黑屋虽然不显示 但是可以使用 （没有授权他过）
> > > 安装狮 shizuku服务状态可用 但是本身的可用状态不行  然后我用酷安的一个都不能安装 自带的商店可以使用 直接文件管理器安装的话 应该是成功使用安装师把 反正出现的不是miui的安装界面
> > > 安装冰箱 点击那个使用shizuku 都不能点的。
> > 
> > 跟作者提供一下log吧，我还是不会弄log😵😵
> 
> 日卡卡叫我们提供落鸽 但是我也不会啊 大佬你研究下啊

尴尬，我也不会呀

**Comment by tsaiajie** [comment]
在提供一个的说
覆盖更新的话 还是可以在应用管理里面看到的

**Comment by tsaiajie** [comment]
在卸载安装过的话就是出现其他有在应用管理里的了

**Comment by tsaiajie** [comment]
红米K40 miui12.5 开启“USB 调试（安全设置） 关闭MIUI优化 使用ADB模式激活
[删除在安装 应用列表有应用的.txt](https://github.com/RikkaApps/Shizuku/files/6526578/default.txt)
[关鸡在安装的 应用列表部分应用.txt](https://github.com/RikkaApps/Shizuku/files/6526581/default.txt)
[覆盖安装 应用列表有应用的.txt](https://github.com/RikkaApps/Shizuku/files/6526575/default.txt)
关机再装了了 小黑屋 ANYWHERE 权限狗 冰箱 前面两个有出现 后面两个没有

**Comment by tsaiajie** [comment]
> > > > 红米K40 miui12.5 开启“USB 调试（安全设置） 关闭MIUI优化
> > > > 我也是一样的 一开始搞了很多以为不行 然后看到这个试试看11.3的可以
> > > > 11.4之后就ANYWHERE一个可以在应用管理里面显示
> > > > 小黑屋虽然不显示 但是可以使用 （没有授权他过）
> > > > 安装狮 shizuku服务状态可用 但是本身的可用状态不行  然后我用酷安的一个都不能安装 自带的商店可以使用 直接文件管理器安装的话 应该是成功使用安装师把 反正出现的不是miui的安装界面
> > > > 安装冰箱 点击那个使用shizuku 都不能点的。
> > > 
> > > 
> > > 跟作者提供一下log吧，我还是不会弄log😵😵
> > 
> > 
> > 日卡卡叫我们提供落鸽 但是我也不会啊 大佬你研究下啊
> 
> 尴尬，我也不会呀

我研究了下 给日卡卡落鸽了 但是他说是正常的 估计是我落井下鸽的方式不对把

**Comment by tsaiajie** [comment]
好像不是小米的原因 我给朋友oppo FX P3 装的话也出现一样的情况… 是直接用它手机所以没落鸽

**Comment by RikkaW** [comment]
[shizuku-11.6.0.r590.554595b-release.apk.zip](https://github.com/RikkaApps/Shizuku/files/6536375/shizuku-11.6.0.r590.554595b-release.apk.zip)
应该好了（
