### ISSUE TITLE
Use WRITE_SECURE_SETTINGS permission to auto-start for non-rooted Android 11 devices

### ISSUE THREAD

**Issue by zacharee** [RikkaApps/Shizuku#123]
Android 11 can use the wireless ADB method to start Shizuku entirely on-device. Shizuku (usually) stays paired with the device across different networks.

If Shizuku requested and self-granted the WRITE_SECURE_SETTINGS permission, it could auto-activate wireless ADB for itself on startup (or when next connected to WiFi), and thus auto-start the Shizuku process.

Since WRITE_SECURE_SETTINGS is a pretty sensitive permission, this should probably be an optional feature, but it'd be one that I'd personally find really useful.

**Comment by vvb2060** [comment]
This is not possible, there is a pop-up asking the user to confirm every reboot, it cannot be bypassed.

**Comment by zacharee** [comment]
The dialog may still need user input, but it will appear as soon as Settings.Global.adb_wifi_enabled is set to 1, so the user doesn't have to go to the development settings, and it can be done I the background.

**Comment by sonatamartica** [comment]
Totally agree, would love to see this!

**Comment by sermart1234** [comment]
@RikkaW I think it's a good idea. Users can set "Always allow on this network" for trusted wifi. This will allow you to restart the Shizuku when connected to your home wifi
