### ISSUE TITLE
Need a help Regarding Ui

### ISSUE THREAD

**Issue by Android1500** [RikkaApps/Shizuku#124]
Actually i want to add new ui in my xposed module and want to add all my content like scrollview under status bar i see your app and its also have same thing which i want can i knw how to get this when use scroll then all content go under status bar and navigation bar i appericate if you could help

**Comment by RikkaW** [comment]
Search for 'android windowinsets'.
The official document: https://developer.android.com/training/gestures/edge-to-edge

My library to handle insets: https://github.com/RikkaApps/RikkaX/tree/master/insets

**Comment by Android1500** [comment]
> Search for 'android windowinsets'.
> 
> The official document: https://developer.android.com/training/gestures/edge-to-edge
> 
> 
> 
> My library to handle insets: https://github.com/RikkaApps/RikkaX/tree/master/insets

Thanks i appericate ❤️

**Comment by Android1500** [comment]
> > Search for 'android windowinsets'.
> > 
> > The official document: https://developer.android.com/training/gestures/edge-to-edge
> > 
> > 
> > 
> > My library to handle insets: https://github.com/RikkaApps/RikkaX/tree/master/insets
> 
> Thanks i appericate ❤️ i am stuck on scroll view for  when user scroll then all scroll go under navigation bar and status bar
