### ISSUE TITLE
UserService中无法在64位设备上使用armeabi-v7a的so库?

### ISSUE THREAD

**Issue by 3ystem** [RikkaApps/Shizuku#127]

**Comment by haruue** [comment]
能不能不要把 Shizuku Issue Tracker 当作 Google ， 净提这些无关问题。

64 位程序只能载入 64 位的库， 32 位程序只能载入 32 位的库， 这是 **常识** 。

有问题先 Google， 或者找个群组问， 我们没有义务给你补课。

**Comment by 3ystem** [comment]
> 能不能不要把 Shizuku Issue Tracker 当作 Google ， 净提这些无关问题。
> 
> 64 位程序只能载入 64 位的库， 32 位程序只能载入 32 位的库， 这是 **常识** 。
> 
> 有问题先 Google， 或者找个群组问， 我们没有义务给你补课。

安卓程序so库以外的部分没有32与64之分吧? 常规应用程序不都能在64位设备上可以正常使用32位的so啊

**Comment by haruue** [comment]
> 安卓程序so库以外的部分没有32与64之分吧? 常规应用程序不都能在64位设备上可以正常使用32位的so啊

能说出这种话只能 **凸显你的无知** 。

现代的 64 位 CPU 虽然有对 32 位的兼容， 但是所有程序都有 32 位和 64 位之分。 即使是运行在 ART 里的 Java 代码（也就是你说的「常规应用程序」）—— Android 会判断程序安装的时候是释放了 32 位还是 64 位的 native library （没有释放就 64 位）， 然后选择是由 zygote （对应 32 位的 `app_process32`） 还是由 zygote64 （对应 64 位的 `app_process64`）来执行 `fork()` 来启动它。 而对于系统服务进程（也就是你说的 `UserService` 运行的环境）， 则是以设备的架构（现在通常都是 64 位架构）被启动的。

虽然跑在同一颗 CPU 上， 但是 32 位和 64 位有着天壤之别， 字长、 指令集、 寄存器组基本上完全不一样， 所以也绝对不可能会有一致的 calling convention ， 这使得在一个 64 位的进程中加载 32 位的动态库是不可能实现的（除非用虚拟化， 这不是本文讨论范畴）， 反之亦然。 也就是说， 一个 64 位的进程只能加载 64 位的动态库， 一个 32 位的进程只能加载 32 位的动态库。

「常规应用能在 64 位设备上正常使用 32 位 so」这句话没错， 但是前提条件是这个「常规应用」是个 32 位进程。 Linux 的兼容性措施只是提供了在 64 位 CPU 上 execve() 执行 32 位的可执行程序的功能， 但是并没有提供在 64 位进程里载入 32 位动态库的功能， 这是两码事。

强烈建议你 **先花一些时间来系统地学习一下计算机基础课程， 不要急于求成**， 学了点鸡毛蒜皮就想用网上的资源来做东西变现， 世界上的事情没有那么简单的。 这些软件运行相关的机制和原理， 可能像写 Java 后端或者 Android UI 之类的东西是用不太上（所以各种培训机构都宣称只要 5 个月就能从零基础量产一个程序员）， 但是这些涉及到底层的「魔法」操作， 没有一定的知识积累是做不了的。

另外这是最后警告， **请不要再在 RikkaApps 的 Issue Tracker 里提交任何与 RikkaApps 无关的问题， 不然你会立即被从 RikkaApps 组织封禁**。

**Comment by 3ystem** [comment]
> > 安卓程序so库以外的部分没有32与64之分吧? 常规应用程序不都能在64位设备上可以正常使用32位的so啊
> 
> 能说出这种话只能 **凸显你的无知** 。
> 
> 现代的 64 位 CPU 虽然有对 32 位的兼容， 但是所有程序都有 32 位和 64 位之分。 即使是运行在 ART 里的 Java 代码（也就是你说的「常规应用程序」）—— Android 会判断程序安装的时候是释放了 32 位还是 64 位的 native library （没有释放就 64 位）， 然后选择是由 zygote （对应 32 位的 `app_process32`） 还是由 zygote64 （对应 64 位的 `app_process64`）来执行 `fork()` 来启动它。 而对于系统服务进程（也就是你说的 `UserService` 运行的环境）， 则是以设备的架构（现在通常都是 64 位架构）被启动的。
> 
> 虽然跑在同一颗 CPU 上， 但是 32 位和 64 位有着天壤之别， 字长、 指令集、 寄存器组基本上完全不一样， 所以也绝对不可能会有一致的 calling convention ， 这使得在一个 64 位的进程中加载 32 位的动态库是不可能实现的（除非用虚拟化， 这不是本文讨论范畴）， 反之亦然。 也就是说， 一个 64 位的进程只能加载 64 位的动态库， 一个 32 位的进程只能加载 32 位的动态库。
> 
> 「常规应用能在 64 位设备上正常使用 32 位 so」这句话没错， 但是前提条件是这个「常规应用」是个 32 位进程。 Linux 的兼容性措施只是提供了在 64 位 CPU 上 execve() 执行 32 位的可执行程序的功能， 但是并没有提供在 64 位进程里载入 32 位动态库的功能， 这是两码事。
> 
> 强烈建议你 **先花一些时间来系统地学习一下计算机基础课程， 不要急于求成**， 学了点鸡毛蒜皮就想用网上的资源来做东西变现， 世界上的事情没有那么简单的。 这些软件运行相关的机制和原理， 可能像写 Java 后端或者 Android UI 之类的东西是用不太上（所以各种培训机构都宣称只要 5 个月就能从零基础量产一个程序员）， 但是这些涉及到底层的「魔法」操作， 没有一定的知识积累是做不了的。
> 
> 另外这是最后警告， **请不要再在 RikkaApps 的 Issue Tracker 里提交任何与 RikkaApps 无关的问题， 不然你会立即被从 RikkaApps 组织封禁**。

明白了, 那shizuku的userservice是不是应该增加一个api, 让接入shizuku的人来决定使用app_process32还是还是本机abi来启动

**Comment by vvb2060** [comment]
目前中国正在加快淘汰32bit，国内各种第三方库均已开始提供64bit的library。32bit很快将在硬件层面停止支持。
我建议 UserService 依据设备 ABI 载入library，而不是要求UserService运行在32bit，这不合理，并且很快将会无法在现代设备上运行。
