### ISSUE TITLE
使用需要传 IBinder 的 API NPE

### ISSUE THREAD

**Issue by Trumeet** [RikkaApps/Shizuku#14]
Parcel 无法传递 Binder，看 Server 里面是直接从 Parcel read 出来的，然后就是 null，再传给系统 API，之后就 NPE 了。建议对于传给 Shizuku Binder 这类情况直接在 Shizuku Server new 出来一个 Binder 即可。

**Comment by RikkaW** [comment]
可是并不是所有的都可以直接 null（

**Comment by Trumeet** [comment]
所以需要 new 出来（
