### ISSUE TITLE
在Android 12 beta3上无法通过无线调试启动

### ISSUE THREAD

**Issue by wankey** [RikkaApps/Shizuku#144]
在Android 12 beta3上，完成无线调试配对后，无法启动shizuku

**Comment by RikkaW** [comment]
尝试开关无线调试

**Comment by wankey** [comment]
> 尝试开关无线调试

有试过，也不行。

目前看下来，可能是这个版本有什么改动导致功能异常，不只是shizuku、黑域也无法通过无线调试启动。

运行debugable的shizuku似乎是 adbMdns = AdbMdns(context, AdbMdns.TLS_CONNECT, port)未能正常工作，没有获取到port

**Comment by ryuunoakaihitomi** [comment]
> > 尝试开关无线调试
> 
> 有试过，也不行。
> 
> 目前看下来，可能是这个版本有什么改动导致功能异常，不只是shizuku、黑域也无法通过无线调试启动。
> 
> 运行debugable的shizuku似乎是 adbMdns = AdbMdns(context, AdbMdns.TLS_CONNECT, port)未能正常工作，没有获取到port


[???](https://github.com/RikkaApps/Shizuku/blob/5f162b355d14f14eb6e19e506d6ab43b3e0d3794/manager/src/main/java/moe/shizuku/manager/home/AdbDialogFragment.kt#L72-L73)
```
gsi_arm64:/ $ getprop | grep adb
[init.svc.adbd]: [running]
[persist.sys.usb.config]: [adb]
[ro.adb.secure]: [1]
```

**Comment by wankey** [comment]
在AdbMdns里加了些log，只输出了
> AdbMdns: start:false
AdbMdns: onDiscoveryStart:true

onServiceFound方法没有走到

**Comment by iamverycute** [comment]
> 尝试开关无线调试

请问是否有希望增加wifi adb自动启动或是一个桌面快捷方式启动？我在rom中默认开启wifi adb。
