### ISSUE TITLE
在Shizuku中通过root启动时黑白门会申请root权限

### ISSUE THREAD

**Issue by ZXAS007** [RikkaApps/Shizuku#145]
如题，shizuku和黑白门都为最新版本
系统官方MIUI12.5安卓11稳定版bingwei
shizuku并为对黑白门授权权限，黑白门并为在后台运行
面具版本23001
已经过几次测试验证

**Comment by RikkaW** [comment]
和 Shizuku 无关

**Comment by ZXAS007** [comment]
你就不解释一下为什么启动shizuku会导致黑白门自启动吗？

**Comment by RikkaW** [comment]
你看你一开始的问题有提到这个吗（

只要声明了需要 Shizuku 的应用都会在启动 Shizuku 服务（并非启动 Shizuku）后被 Shizuku 服务启动。

* 为什么要启动？
  
  使用 Shizuku 的应用与 Shizuku 通过 Binder 交互，因为 Shizuku 还支持通过 adb 使用，所以只有由服务将 Binder 发给使用的应用（也就是必须启动用它的应用）这一条路。

* 为什么没有授权也要启动？
  
  为了使用的应用能够正常地处理请求权限流程。
