### ISSUE TITLE
使shizuku支持通过Sui启动

### ISSUE THREAD

**Issue by ZXAS007** [RikkaApps/Shizuku#146]

**Comment by haruue** [comment]
没有意义。

**Comment by RikkaW** [comment]
会导致同时支持 Sui 和 Shizuku 的应用工作异常

**Comment by ZXAS007** [comment]
> 会导致同时支持 Sui 和 Shizuku 的应用工作异常

添加优先级自动隐藏其中一个

**Comment by ZXAS007** [comment]
既然会导致紊乱为什么shizuku和Sui可以同时存在？这不都一样吗？

**Comment by segfault-bilibili** [comment]
我倒有点好奇两者共存会如何，会不会导致shizuku被绕过架空
