### ISSUE TITLE
你好 一直尝试失败在OS10中用无线ADB端口开启Shizuku

### ISSUE THREAD

**Issue by sunyink** [RikkaApps/Shizuku#149]
你好 一直尝试失败在OS10中用无线ADB端口开启Shizuku

我使用三星原版的安卓10系统（oneui2.0）。我可以用USB连接电脑使用ADB命令，但这个模式每次通过USB连接电脑拔线后都需要重新设定，紧急的情况下解冻不了冰箱的程序简直热锅蚂蚁。
所以我一直在尝试通过ADB开启如5555端口的无线调试，再通过Shizuku的无线ADB开启模式，让安卓10也能单手机启用。
现在的结果来说是失败的，开启ADB端口后Tasker可以控制wifi开关，但Shizuku开启不能如图（使用无线ADB开启后页面截图）。
![Screenshot_20210809-135438_Shizuku](https://user-images.githubusercontent.com/37411580/128665604-a9fa5124-2216-4ad2-af93-fda9aed4209d.png)
另外鬼使神差，以前还真的成功过，可我完全不知道为什么，重启就没了，也无法再现...   如果能得到帮助，我非常感谢~

====translate by google====
Hello, I have been trying and failing to open Shizuku with the wireless ADB port in OS10

I use Samsung's original Android 10 system (oneui2.0). I can use the ADB command to connect to the computer via USB, but this mode needs to be reset every time I connect the computer to the computer via USB and unplug the cable. In an emergency, it is troublesome that the refrigerator cannot be defrosted.
So I have been trying to enable wireless debugging such as port 5555 through ADB, and then through Shizuku's wireless ADB enable mode, so that Android 10 can also be enabled on a single phone.
The current result is a failure. Tasker can control the wifi switch after opening the ADB port, but Shizuku cannot be turned on as shown in the figure (screenshot of the page after turning on the wireless ADB).
In addition, I’ve been really successful in the past, but I don’t know why, and the restart is gone, and it can’t be reproduced... If I can get help, I’m very grateful~
====translate end====
thanks~

**Comment by sunyink** [comment]
补充一下，设备非Root。Root没有以前那么香就放弃了。
And this is no root.

**Comment by RikkaW** [comment]
尝试一下最新的 CI 构建 https://github.com/RikkaApps/Shizuku/actions/runs/1141771626 呢

**Comment by sunyink** [comment]
感谢你的回复，我认为这个版本已搞定了这个问题。
我自己也用这个版本做了些测试，
只要满足：1、ADB开启过无线调试端口；2、USB调试模式开启
那么无论是，手机重启后、“默认USB仅充电”的设备连接线缆重选模式的插拔行为后（此点现在已不是问题~）；
shizuku均可以使用无线ADB那个“开启”按钮启动服务。
再次感谢付出，现在我可以丢开有副作用的“设备管理员模式”了~~
