### ISSUE TITLE
App takes up all of space

### ISSUE THREAD

**Issue by Auvere** [RikkaApps/Shizuku#15]
A critical bug appeared after using it the previous day. It looks like it used up all my available storage space, probably due to logging although I don't see any setting for logging in the app itself.

Using Shizuku Manager version 2.0.0 on Android 6.0 with root capability
![screenshot_20171031-225744](https://user-images.githubusercontent.com/27517093/32231227-fde928e0-be8f-11e7-9ab4-80e22aff1817.png)

**Comment by RikkaW** [comment]
Can you see what files in these two folders occupy space?
`/sdcard/Android/data/moe.shizuku.privileged.api/` (with any file manager app)
`/data/data/moe.shizuku.privileged.api/` (with any file manager app support root)

**Comment by Auvere** [comment]
Unfortunately I already cleared up the app's data. But the log files are in `/sdcard/Android/data/moe.shizuku.privileged.api/`
I'll comment an update once I see otherwise.
