### ISSUE TITLE
版本12在Android9上无法启动

### ISSUE THREAD

**Issue by PikuZheng** [RikkaApps/Shizuku#151]
adb运行启动指令返回正常，但服务并没有启动。应该如何收集调试信息？

**Comment by RikkaW** [comment]
开两个终端，一个运行 `adb logcat > 1.txt`，另一个尝试启动，尝试启动后等个几秒回到第一个按下 CTRL+C，然后把 1.txt 发过来。

**Comment by PikuZheng** [comment]
12.2存在此问题，12.3正常。
