### ISSUE TITLE
(Question) ADB vs Shizuku manager

### ISSUE THREAD

**Issue by NSTAdventure** [RikkaApps/Shizuku#152]
After reading readme i still didn't get it
If you say you can use api directly adb over tcp have same ability

Can you explain more pls? 🙏😊❤️

**Comment by haruue** [comment]
Please take a look at our website. 
https://shizuku.rikka.app/introduction/

**Comment by NSTAdventure** [comment]
> Please take a look at our website.
> https://shizuku.rikka.app/introduction/

Okay do ADB over TCP have same way to let app use hidden API?

**Comment by haruue** [comment]
Of cause but you will need to run & maintain a daemon to interact with your user interface, this kind of daemon is just another Shizuku.

Or maybe you just want to run commands instead of providing a user-friendly user interface, please just use adb over TCP in this condition.

**Comment by haruue** [comment]
If you are an Android application developer, please take a look at our website, where you can get the answer to your question and you will be able to determine whether to use Shizuku or not.

If you are just a user of some application that uses Shizuku rather than a developer, please just follow the configuration guide of what application you want to use.

**Comment by NSTAdventure** [comment]
> Of cause but you will need to run & maintain a daemon to interact with your user interface


You mean command prompt?

Also you mean need enable adb over tcp to use user interface A.K.A terminal or any kind of that?

**Comment by haruue** [comment]
Nope, the "user interface" I said, is an application that provides a user-friendly graphical user interface (GUI).

If you just want to use the command line, the Shizuku makes no sense for you, please just use the adb over tcp directly.

**Comment by haruue** [comment]
It is not easy to draw GUI with the root or adb permission (it may be not easy to understand why if you are a Linux guy, but this is a fact on the Android, just try if you don't believe), so the standard implementation of programs that requires higher permission is running a daemon with high permission, and connect it with TCP or other IPC ways from a normal Android application. (Runs commands upon user operations is also a choice, but it is extremely slow & unstable)

**Comment by NSTAdventure** [comment]
Okay so the conclusion for different ADB over tcp and shizuku manager are

1. Shizuku
(and all app that have shizuku framework)
doesn't have dependencies to daemon
(ADB over TCP)

2. Shizuku is more simple than ADB over TCP 
All dev need to do is add shizuku code implementation and user just need run shizuku and connect all app to shizuku manager 
(On some specific android version you need grant access API to shizuku and other related app)

But shizuku and ADB Have something in common:
1. Allow user to access API directly (using app_process too?)


Right? @haruue

**Comment by RikkaW** [comment]
I don’t think you understand anything, it’s useless to continue to explain.

**Comment by NSTAdventure** [comment]
> I don’t think you understand anything, it’s useless to continue to explain.

Yeah i try my best to understand it :(

**Comment by haruue** [comment]
> Yeah i try my best to understand it :(

Could you please explain why you opened this issue without any knowledge about Shizuku? It seems like you are not a Shizuku user or a related developer. Are you writing some paper or doing some research on it?

**Comment by NSTAdventure** [comment]
> > Yeah i try my best to understand it :(
> 
> Could you please explain why you opened this issue without any knowledge about Shizuku? It seems like you are not a Shizuku user or a related developer. Are you writing some paper or doing some research on it?

Sorry in advance 🙏
I've also used Shizuku, I've read the documentation too But still don't understand the difference between shizuku manager and adb over tcp

Because both can allow app access hidden framework directly

**Comment by RikkaW** [comment]
> Because both can allow app access hidden framework directly

ADB **CANNOT** allow apps to use system APIs. Also, apps **CANNOT** interact with adb directly.

**Comment by haruue** [comment]
You cannot understand because of the lack of knowledge about Android development, you just thought about Android  API permission & restriction as to the one on Linux, but it is definitely different. So however I try to explain it, you won't understand. 

If you are interested in how the Shizuku work, please learn about Android development and related restriction first. This world is much more complex than you thought.

**Comment by NSTAdventure** [comment]
> > Because both can allow app access hidden framework directly
> 
> ADB **CANNOT** allow apps to use system APIs. Also, apps **CANNOT** interact with adb directly.

But how app like app manager working? They use adb over tcp or root to work.... 🙏🥴🥴🥴🥴

**Comment by haruue** [comment]
It is not our responsibility to waste our time to teach you everything about Android development, please ask in an Android development group on your favorite IM or search for these questions on Google.
