### ISSUE TITLE
一加5T root模式下无法启动

### ISSUE THREAD

**Issue by LinaChong** [RikkaApps/Shizuku#153]
系统版本7.1.1
日志
Starting with root...

info: start.sh begin
info: attempt to copy starter from /data/user_de/0/moe.shizuku.privileged.api/starter to /data/local/tmp/shizuku_starter
info: exec /data/local/tmp/shizuku_starter
warn: can't read cgroup
info: starter begin
info: killing old process...
info: killed 22280 (shizuku_server)
info: use apk path from argv
info: apk path is /data/app/moe.shizuku.privileged.api-1/base.apk
info: starting server...
info: shizuku_starter exit with 0

Waiting for service...

**Comment by RikkaW** [comment]
需要启动期间的 log。

你可以使用任何你喜欢的 logcat 应用，或是在任意的终端应用（记得先 su）或 adb shell 中运行 logcat，来抓取 log。

在启动之前开始 logcat，在启动完成后几秒停止即可。
