### ISSUE TITLE
能否通过Magisk模块开机启动Shizuku服务？

### ISSUE THREAD

**Issue by nukemiko** [RikkaApps/Shizuku#155]
手头的华为Nova3已经解锁和刷入Magisk，上面的Shizuku服务无法通过任何手段（手机管家允许自启动、关闭电池优化、转换成系统应用等）实现开机启动，但是直接进入应用能够正常启动服务。

估计你们不会针对华为机型进行修复，所以能否使用Magisk模块加载用于adb启动模式的脚本，实现开机自启动？

**Comment by RikkaW** [comment]
你可以使用 https://github.com/RikkaApps/Sui，只要你不需要使用只支持 Shizuku v11 以前（不包括 11）的应用就没问题。

**Comment by 919334339** [comment]
> 你可以使用 https://github.com/RikkaApps/Sui，只要你不需要使用只支持 Shizuku v11 以前（不包括 11）的应用就没问题。

大佬，我用shizuku和sui都不能实现开机自启clash，shizuku需要开机后点进shizuku界面它才会启动clash，sui需要我打开clash才会启动。miui14，已ROOT。

**Comment by PhDLuffy** [comment]
利用magisk的模块自启动开启无线调试的端口就可以吧
