### ISSUE TITLE
Shizuku doesn't stay active.

### ISSUE THREAD

**Issue by Cortru619** [RikkaApps/Shizuku#156]
After making sure the app wasn't being optimized and the do not force stop list. Is there a way to keep it active?

**Comment by shaggyskunk** [comment]
If you mean keep Shizuku running, Disable adb authorisation time out in
Developer Options.

**Comment by e-t-l** [comment]
> and the do not force stop list

@Cortru619 what list are you referring to? I'm also having issues with Shizuku randomly stopping (usually overnight)
