### ISSUE TITLE
你好 shizuku 支持安卓6.0.1吗 移动文件到bin后运行命令报错

### ISSUE THREAD

**Issue by yu1chaofan** [RikkaApps/Shizuku#158]
shizuku 支持安卓6.0.1吗 移动文件到bin后运行命令报错 

termux mt管理器 都报错 手机是魅蓝E2 安卓6.0.1 已经root

$ rish 
CANNOT LINK EXECUTABLE: cannot locate symbol "EVP_CIPHER_CTX_init" referenced by "/system/lib64/libdrmmtkutil.so"...
page record for 0x7fa3b76010 was not found (block_size=16)

**Comment by RikkaW** [comment]
直接运行 app_process 会发生什么呢
