### ISSUE TITLE
sony xperia xzp问题

### ISSUE THREAD

**Issue by tarkky** [RikkaApps/Shizuku#16]
您好，
我是美版xzp，8.0系统，未root，每次运行adb命令后，shizuku manager显示server已经正常运行，但是每次一拔下usb线，server就没了，请问这是正常吗？
谢谢。

**Comment by haruue** [comment]
看起来不正常。
Android 8.0 会在停用 adb 的时候停止所有使用 adb 启动的程序，但是拔下 USB 就没了就很奇怪了。
另外能不能提供一下您使用的 Shizuku Manager 的版本号呢？

**Comment by tarkky** [comment]
2.1.1-beta.r149.d0b406d谢谢

**Comment by haruue** [comment]
无法在 Android 8.0 上的这个版本的 Shizuku 重现此异常。
如果您使用命令行通过 adb 启动 Shizuku ，能不能把启动时的输出发一下？另外请关注一下启动之后能不能回到命令行状态（比如会不会回到命令提示符 `C:\Windows\System32>` ，或者试试执行其他命令），还是启动成功之后就卡在那里？

**Comment by tarkky** [comment]
请看附件的截图，命令执行完毕时正常的回到提示符状态，可以执行其他命令的。
![shizuku](https://user-images.githubusercontent.com/19773978/33796450-786cdefa-dd2f-11e7-9f96-9c86f8eadafc.jpg)

**Comment by haruue** [comment]
连接电脑的方式选“只充电”试试？

**Comment by tarkky** [comment]
非常感谢 @haruue  选只充电行了。
