### ISSUE TITLE
MIUI Unable to find permission to get application management working

### ISSUE THREAD

**Issue by mLgz0rn** [RikkaApps/Shizuku#174]
Please report bugs of Shizuku itself.

**Requirements:**

- [ x] Shizuku version is up-to-date
- [ x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ x] Shizuku is not running in a virtual environment
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

**Information:**

- Shizuku version: 12.4.3
- Mode: adb
- Android version: 11
- Device: (optional): Xiaomi mi 9t pro

**Describe the bug:**

Unable to find permission to get application management working, it's just not there.
miui optimization is disabled.

**Additional context:**

I guess from the information detailed here https://shizuku.rikka.app/guide/setup/ that there is no way to get it working on miui?

**Comment by RikkaW** [comment]
https://shizuku.rikka.app/guide/setup/

> You need to enable "USB debugging (Security options)" in "Developer options".

**Comment by mLgz0rn** [comment]
> https://shizuku.rikka.app/guide/setup/
> 
> > You need to enable "USB debugging (Security options)" in "Developer options".

Gonna reopen this, because that was not the issue.
And I actually got it fixed by going into "Android Settings -> Apps -> Administrate apps -> Permissions -> Permissions (might be called Permissions administrator) -> scroll to the bottom -> Additional permissions" where there was a Shinzuku entry and then changed the app permissions from denied to allowed, if the app was not there I restarted the phone and it would show up.
Then restarted the Shinzuku service and it started working.

https://i.imgur.com/tihFAPf.jpg
https://i.imgur.com/4ZZVtda.jpg

**Comment by haruue** [comment]
Duplicated with #45 and android-in-china/Compatibility#16 (though both of these issues are reported in Chinese).

This is a really simple bug in the system component of MIUI since 2019 but just not got fixed even after 2 years.

So, Xiaomi, Fxxk you!

**Comment by mLgz0rn** [comment]
> Duplicated with #45 and [android-in-china/Compatibility#16](https://github.com/android-in-china/Compatibility/issues/16) (though both of these issues are reported in Chinese).
> 
> This is a really simple bug in the system component of MIUI since 2019 but just not got fixed even after 2 years.
> 
> So, Xiaomi, Fxxk you!

Yeah I did read through those, with google translate though, which might be why I couldn't find an answer there.
But yeah, that is really the only bad thing I have about xiaomi phones, such a simple bug, yet not fixed.

Thanks for the response guys!
