### ISSUE TITLE
Requesting binder from a background service

### ISSUE THREAD

**Issue by CasperVerswijvelt** [RikkaApps/Shizuku#175]
While developing an app that provides custom tiles using a TileService, I noticed that the binder does not get received if the app process is started with only a background service. Digging a bit into the code confirms that a process is only registered when a new foreground activity starts.

I have tried using `requestBinderForNonProviderProcess` to get the binder that way, but the `context.getContentResolver().call(..)` call always returns null when my app activity has not yet been started.

Am I missing something here or is it not possible to get the binder in background services unless a foreground activity of the same app was openend?

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku#attention 3. Android 8.0 & ADB

> On API 26, ADB lacks permissions to use `registerUidObserver`

There is nothing to do :(

**Comment by CasperVerswijvelt** [comment]
Oh that sucks, must have read over that.

I actually got it to work by starting a foregroundservice in my `Application` subclass, which does get picked up by shizuku :)

**Comment by RikkaW** [comment]
This should be the real reason :(

9f47d521
