### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by prestonstone2004** [RikkaApps/Shizuku#177]
Would it be possible to make a cmd like interface for shizuku, for adb comands like this:
pm grant com.maxmpz.audioplayer android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER
this doesn't open in shizuku and just copied to my clipboard
![Screenshot_20211230-050233_Poweramp](https://user-images.githubusercontent.com/69037877/147746217-e77a5c2d-6f55-4be7-a192-9ddb4e1f306d.jpg)

**Comment by RikkaW** [comment]
Such feature has been there for a long time, see "Use Shizuku in terminal apps" in Shizuku app.
