### ISSUE TITLE
为什么在miui13中无法通过配对码连接到无线调试呢

### ISSUE THREAD

**Issue by eternity49** [RikkaApps/Shizuku#178]
为什么在miui13中无法通过配对码连接到无线调试呢

**Comment by RikkaW** [comment]
具体一点描述，什么叫“无法通过配对码连接到无线调试”。

**Comment by eternity49** [comment]
![Uploading Screenshot_2022-01-03-13-58-34-022_com.android.settings.jpg…]()

**Comment by eternity49** [comment]
在输入配对码后，显示“配对失败 无法连接至无线调试服务。”

**Comment by eternity49** [comment]
我已打开开发者选项、USB调试、USB调试（安全设置）、无线调试

**Comment by RikkaW** [comment]
看一下 tag 是 AdbPairingService 的 log。

另外怀疑 MIUI 是不是有什么不在前台一段时间就禁止访问网络功能，把系统的限制这个限制那个功能全部关闭试试呢（

**Comment by eternity49** [comment]
感谢，万万没想到是因为MIUI禁止了shizuku的访问网络功能，授予权限后就可以正常用了
