### ISSUE TITLE
When WiFi is close The app is can't work

### ISSUE THREAD

**Issue by Tback1** [RikkaApps/Shizuku#18]
System version MIUI 9.0.5.0
Shizuku version 2.1.1-beta.r149.d0b406d
When wifi is close the logcat put out this:
02-01 14:51:53.898  5856  7176 W ShizukuClient: can't connect to server: Permission denied

![screenshot_2018-02-01-14-58-41-378_moe shizuku privileged api](https://user-images.githubusercontent.com/8872546/35665329-bd1ff112-0760-11e8-8f28-0e0a1642fb4e.png)

And the app ops delay the Shizuku is not working
After the Wifi is open The Shizuku is work again.

![screenshot_2018-02-01-14-58-31-784_moe shizuku privileged api](https://user-images.githubusercontent.com/8872546/35665332-c17de962-0760-11e8-957f-c10b91ba4301.png)

**Comment by Tback1** [comment]
wifi 断开后
02-01 15:21:15.439  7245  7245 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-01 15:21:15.456  7245  7245 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=229376 outq=0 send_len=49
02-01 15:21:16.095   752   752 I ServiceManager: Waiting for service AtCmdFwd...
02-01 15:21:16.338  2439  2439 D BatteryController: action=android.intent.action.BATTERY_CHANGED; mCharging=false
02-01 15:21:16.340  3360  3360 I BatteryInfoReceiver: ACTION_BATTERY_CHANGED
02-01 15:21:16.341  3202  3379 W QCNEJ   : |CORE| CNE received unexpected action: android.intent.action.BATTERY_CHANGED
02-01 15:21:16.342  3837  4143 D PowerCheckerService: onBatteryChanged, mBatteryLevel = 98, status = 3, level = 98, plug = 0
02-01 15:21:16.546  6163  6163 I Timeline: Timeline: Activity_launch_request time:362823
02-01 15:21:16.553  1633  3393 I ActivityManager: START u0 {cmp=moe.shizuku.privileged.api/moe.shizuku.manager.ManageAppsActivity} from uid 10264 on display 0
02-01 15:21:16.574  1633  3393 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-01 15:21:16.574   469  2952 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
02-01 15:21:16.599  3277  3564 I WtProcessController: MOVE TO FOREGROUND: moe.shizuku.privileged.api 10264
02-01 15:21:16.599  3277  3564 I WtProcessController: FOREGROUND INFO: name=moe.shizuku.privileged.api uid=10264 pid=6163 TaskId:3071
02-01 15:21:16.599  1633  3393 I Timeline: Timeline: App_transition_ready time:362877
02-01 15:21:16.614  6163  6163 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2057d9e
02-01 15:21:16.614  6163  6163 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@ed0d07f
02-01 15:21:16.626  6163  6163 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@c84d76f
02-01 15:21:16.626  6163  6163 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@d0dbc7c
02-01 15:21:16.629  1633  3393 E com.android.server.pm.PackageManagerServiceInjector: MIUILOG- Permission Denied getInstalledPackages. pkg : moe.shizuku.privileged.api uid : 10264
02-01 15:21:16.679  3562  7310 I IMAP_PUSH_SERVICE: reschedulePushers()
02-01 15:21:16.708  3562  7310 I IMAP_PUSH_SERVICE: startAccountPush()
02-01 15:21:16.716  3562  7311 I IMAP-PUSH: start imap idle tos***-6**@qq.com and mailbox isINBOX
02-01 15:21:16.721  3562  7311 W SSLCertificateSocketFactory: Bypassing SSL security checks at caller's request
02-01 15:21:16.725  1633  1642 I art     : Background partial concurrent mark sweep GC freed 193958(10MB) AllocSpace objects, 148(5MB) LOS objects, 31% free, 34MB/50MB, paused 1.972ms total 135.840ms
02-01 15:21:16.733  2439  2439 D PhoneStatusBar: disable: 0x00000200 -> 0x00000000 (diff: 0x00000200)
02-01 15:21:16.733  2439  2439 D PhoneStatusBar: disable: < expand icons alerts ticker system_info back home recent clock full hide keyguard none float >
02-01 15:21:16.734  3360  3360 I a       : bindCount : 1
02-01 15:21:16.743  1633  3393 I Timeline: Timeline: App_transition_ready time:363021
02-01 15:21:16.745  1633  3393 I Timeline: Timeline: App_transition_ready time:363022
02-01 15:21:16.748  1633  3392 I ActivityManager: Start proc 7315:com.miui.guardprovider/u0a48 for service com.miui.guardprovider/.manager.SecurityService caller=com.miui.securitycenter
02-01 15:21:16.759  7315  7315 D TidaProvider: TidaProvider()
02-01 15:21:16.766  7315  7315 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@4308bdd
02-01 15:21:16.772  1633  1654 I Timeline: Timeline: App_transition_ready time:363050
02-01 15:21:16.774  2439  2439 D PhoneStatusBar: disable: 0x00000000 -> 0x00000200 (diff: 0x00000200)
02-01 15:21:16.774  2439  2439 D PhoneStatusBar: disable: < expand icons alerts ticker system_info back home recent clock full hide keyguard none float >
02-01 15:21:16.774  1633  1654 I ActivityManager: Displayed moe.shizuku.privileged.api/moe.shizuku.manager.ManageAppsActivity: +179ms
02-01 15:21:16.775  2439  2439 V PhoneStatusBarPolicy: updateManagedProfile mManagedProfileFocused: false mManagedProfileInQuietMode: false mKeyguardVisible: false mCurrentUserId:0 mCurrentProfileId:0 mSecondSpaceStatusIconVisible: true showIcon:false
02-01 15:21:16.792  7315  7315 W System  : ClassLoader referenced unknown path: /system/app/GuardProvider/lib/arm64
02-01 15:21:16.800  6163  7198 D OpenGLRenderer: endAllActiveAnimators on 0x7f75ec6000 (CardView) with handle 0x7f75a889c0
02-01 15:21:16.808  7315  7315 D MI_STAT : initialize com.miui.guardprovider, 2882303761517522561, default, false
02-01 15:21:16.813  7315  7315 D SecurityService: ------ service create------
02-01 15:21:16.814  7315  7315 D SecurityService: ------ service on bind------
02-01 15:21:16.818  7315  7331 D SanityUtil: check proguard ok
02-01 15:21:16.840  7315  7331 I TencentEngine: wifiDetect:observer=com.miui.guardprovider.aidl.IWifiDetectObserver$Stub$Proxy@b7d886f; type=NETWORKSTATE; argnull
02-01 15:21:16.841  7315  7331 I TencentEngine: wifiDetect:observer=com.miui.guardprovider.aidl.IWifiDetectObserver$Stub$Proxy@2a9d205; type=SECURITY; argnull
02-01 15:21:16.842  7315  7331 I TencentEngine: wifiDetect:observer=com.miui.guardprovider.aidl.IWifiDetectObserver$Stub$Proxy@5043c8b; type=DNSANDPHISHING; argnull
02-01 15:21:16.842  7315  7331 I TencentEngine: wifiDetect:observer=com.miui.guardprovider.aidl.IWifiDetectObserver$Stub$Proxy@4fa8981; type=ARP; argmdetector
02-01 15:21:16.843  3360  7335 E PaySafetyCheckManager: start wifi scan task ...
02-01 15:21:16.843  7315  7341 D SanityUtil: pkgName:[com.miui.guardprovider]uid: [10048]android version:[24]
02-01 15:21:16.844  7315  7341 D SanityUtil: appId:[10048]
02-01 15:21:16.853  3418  3418 D TextExpansionAccessibilityServicePro: onAccessibilityEvent: windows changeds
02-01 15:21:16.865  7315  7341 D NetworkSecurityConfig: No Network Security Config specified, using platform default
02-01 15:21:16.871  7315  7341 W System.err: java.net.ConnectException: Connection refused
02-01 15:21:16.871  7315  7341 W System.err: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
02-01 15:21:16.871  7315  7341 W System.err: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
02-01 15:21:16.872  7315  7341 W System.err: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
02-01 15:21:16.872  7315  7341 W System.err: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
02-01 15:21:16.872  7315  7341 W System.err: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
02-01 15:21:16.872  7315  7341 W System.err: 	at java.net.Socket.connect(Socket.java:586)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.Connection.connectSocket(Connection.java:196)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.Connection.connect(Connection.java:172)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
02-01 15:21:16.872  7315  7341 W System.err: 	at tmsdk.bg.module.wifidetect.b.g(Unknown)
02-01 15:21:16.872  7315  7341 W System.err: 	at tmsdk.bg.module.wifidetect.WifiDetectManager.detectNetworkState(Unknown)
02-01 15:21:16.872  7315  7341 W System.err: 	at com.miui.guardprovider.engine.tencent.TencentEngine$2.run(TencentEngine.java:230)
02-01 15:21:16.872  7315  7341 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-01 15:21:16.872  7315  7341 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-01 15:21:16.872  7315  7341 W System.err: 	at java.lang.Thread.run(Thread.java:760)
02-01 15:21:16.872  7315  7341 I TencentEngine: wifiDetect:onResult type = NETWORKSTATE; ret = 2
02-01 15:21:16.878  7315  7342 I TencentEngine: wifiDetect:onResult type = SECURITY; ret = 258
02-01 15:21:16.899  7315  7346 I TencentEngine: wifiDetect:onResult type = ARP; ret = 261
02-01 15:21:16.967  7128  7128 D BreventServer: check and brevent
02-01 15:21:17.048  1633  1654 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{e4edcab u0 moe.shizuku.privileged.api/moe.shizuku.manager.ManageAppsActivity t3071} time:363325
02-01 15:21:17.048  1633  1648 D ActivityTrigger: ActivityTrigger activityStopTrigger 
02-01 15:21:17.049  2439  2439 D EventBus: [2439, u0] send(AppTransitionFinishedEvent)
02-01 15:21:17.049  2439  2439 D EventBus: [2439, u0]  -> ForcedResizableInfoActivityController [0xb18ec5, P1] onBusEvent(AppTransitionFinishedEvent)
02-01 15:21:17.049  2439  2439 D EventBus: [2439, u0] onBusEvent(AppTransitionFinishedEvent) duration: 20 microseconds, avg: 24
02-01 15:21:17.077  1633  1654 I WindowManager: Destroying surface Surface(name=moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2043 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:895 com.android.server.wm.WindowState.destroyOrSaveSurface:2116 com.android.server.wm.AppWindowToken.destroySurfaces:366 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:313 com.android.server.wm.WindowAnimator.animateLocked:714 
02-01 15:21:17.080  2439  2439 D EventBus: [2439, u0] send(AppTransitionFinishedEvent)


断开后shizuku的后台活动

02-01 15:18:12.332  6135  6157 W FA      : Service invalid
02-01 15:18:12.404  1633  1937 D ActivityManager: Set processmoe.shizuku.privileged.api max adj to 400
02-01 15:18:12.404  1633  1937 I ActivityManager: Start proc 6163:moe.shizuku.privileged.api/u0a264 for content provider moe.shizuku.privileged.api/moe.shizuku.manager.provider.TokenProvider caller=rikka.appops.pro
02-01 15:18:12.414  1633  1648 I ActivityManager: Waited long enough for: ServiceRecord{950298 u0 com.jeejen.family.miui/com.jeejen.home.launcher.services.LauncherService}
02-01 15:18:12.420  6163  6163 D TidaProvider: TidaProvider()

2-01 15:19:51.879  7059  7059 I Radio-JNI: register_android_hardware_Radio DONE
02-01 15:19:51.923  7059  7059 D AndroidRuntime: Calling main entry moe.shizuku.server.ShizukuServer
02-01 15:19:51.949   743  1618 E Parcel  : Reading a NULL string not supported here.
02-01 15:19:52.036  7059  7059 I ShizukuServer: uid: 2000
02-01 15:19:52.037  7059  7059 I ShizukuServer: api version: 24
02-01 15:19:52.037  7059  7059 I ShizukuServer: device: mido
02-01 15:19:52.038  7059  7059 I ShizukuServer: start version: 28 token: b0285387-5a57-40d9-beb6-dbc4a3d7263f
02-01 15:19:52.124  1633  3395 I ActivityManager: START u0 {act=moe.shizuku.privileged.api.intent.action.SERVER_STARTED cat=[android.intent.category.DEFAULT] flg=0x10000000 pkg=moe.shizuku.privileged.api cmp=moe.shizuku.privileged.api/moe.shizuku.manager.TokenReceiveActivity (has extras)} from uid 2000 on display 0
02-01 15:19:52.129   469  2952 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
02-01 15:19:52.130  3277  3564 I WtProcessController: mCurTask:3070
02-01 15:19:52.133  1633  3395 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@a66e1d7
02-01 15:19:52.134  1633  3395 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-01 15:19:52.136  7059  7059 I ShizukuServer: send token to manager app in user 0
02-01 15:19:52.137  1633  3282 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9e7dac4
02-01 15:19:52.137  1633  3282 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@3f80dad
02-01 15:19:52.144  3277  3564 I WtProcessController: MOVE TO FOREGROUND: moe.shizuku.privileged.api 10264
02-01 15:19:52.145  3277  3564 I StatusController: Last foreground:com.teslacoilsw.launcher uid:10068 Current foreground:moe.shizuku.privileged.api uid:10264
02-01 15:19:52.145  3277  3564 I WtProcessController: FOREGROUND INFO: name=moe.shizuku.privileged.api uid=10264 pid=6163 TaskId:3070
02-01 15:19:52.146  1633  3282 I Timeline: Timeline: App_transition_ready time:278423
02-01 15:19:52.149  5170  5170 D TouchAssistant: getPackageNameFromPid packageName:moe.shizuku.privileged.api
02-01 15:19:52.149  5170  5170 D TouchAssistant: onTopAppChanged packageName:moe.shizuku.privileged.api
02-01 15:19:52.150  5170  5170 D TouchAssistant: updateAll and mViewAdded = true
02-01 15:19:52.161  1633  3282 I Timeline: Timeline: App_transition_ready time:278439
02-01 15:19:52.165  1633  3282 I Timeline: Timeline: App_transition_ready time:278442
02-01 15:19:52.165  6163  6163 I ShizukuManager: token update: b0285387-5a57-40d9-beb6-dbc4a3d7263f
02-01 15:19:52.170  6163  7078 W System  : ClassLoader referenced unknown path: /system/app/MiuiContentCatcher/lib/arm64
02-01 15:19:52.158  7078  7078 W interceptor-thr: type=1400 audit(0.0:123): avc: denied { getattr } for path="/data/data/com.miui.contentcatcher" dev="dm-1" ino=1620808 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_app_data_file:s0 tclass=dir permissive=0
02-01 15:19:52.174  1633  3282 E com.android.server.pm.PackageManagerServiceInjector: MIUILOG- Permission Denied getInstalledPackages. pkg : moe.shizuku.privileged.api uid : 10264
02-01 15:19:52.178  1633  3395 I Timeline: Timeline: App_transition_ready time:278455
02-01 15:19:52.209  2577  2577 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
02-01 15:19:52.211  2577  2577 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=229376 outq=0 send_len=49
02-01 15:19:52.250  1633  3391 I Timeline: Timeline: App_transition_ready time:278527
02-01 15:19:52.250  1633  3391 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-01 15:19:52.253  1633  3282 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@e4dc473 attribute=null, token = android.os.BinderProxy@56eeb2
02-01 15:19:52.260  6163  6163 D AccessibilityManager: current package=moe.shizuku.privileged.api, accessibility manager mIsFinalEnabled=true, mOptimizeEnabled=true, mIsUiAutomationEnabled=false, mIsInterestedPackage=true

02-01 15:20:52.229  1633  2690 I ActivityManager: START u0 {act=moe.shizuku.privileged.api.intent.action.REQUEST_AUTHORIZATION pkg=moe.shizuku.privileged.api cmp=moe.shizuku.privileged.api/moe.shizuku.manager.AuthorizationActivityV23} from uid 10282 on display 0
02-01 15:20:52.229  6135  7167 I FA      : Tag Manager is not found and thus will not be used
02-01 15:20:52.233  1633  2690 E ResourceType: Style contains key with bad entry: 0x011100d8
02-01 15:20:52.233  1633  2690 E ResourceType: Style contains key with bad entry: 0x011100d9
02-01 15:20:52.234  1633  2690 E ResourceType: Style contains key with bad entry: 0x011100d8
02-01 15:20:52.234  1633  2690 E ResourceType: Style contains key with bad entry: 0x011100d9
02-01 15:20:52.234  1633  2690 E ResourceType: Style contains key with bad entry: 0x011100d8
02-01 15:20:52.234  1633  2690 E ResourceType: Style contains key with bad entry: 0x011100d9
02-01 15:20:52.236  1633  2690 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-01 15:20:52.268  1633  5767 D ui-boost: Set RenderThread tid 7169 for pid 6135 name=rikka.appops.pro
02-01 15:20:52.269  6135  6135 E HAL     : PATH3 /odm/lib64/hw/gralloc.qcom.so
02-01 15:20:52.269  6135  6135 E HAL     : PATH2 /vendor/lib64/hw/gralloc.qcom.so
02-01 15:20:52.270  6135  6135 E HAL     : PATH1 /system/lib64/hw/gralloc.qcom.so
02-01 15:20:52.270  6135  6135 E HAL     : PATH3 /odm/lib64/hw/gralloc.msm8953.so
02-01 15:20:52.270  6135  6135 E HAL     : PATH2 /vendor/lib64/hw/gralloc.msm8953.so
02-01 15:20:52.270  6135  6135 E HAL     : PATH1 /system/lib64/hw/gralloc.msm8953.so

02-01 15:20:52.286  3277  3564 I WtProcessController: MOVE TO FOREGROUND: moe.shizuku.privileged.api 10264
02-01 15:20:52.286  7128  7128 D BreventServer: update current to moe.shizuku.privileged.api
02-01 15:20:52.286  3277  3564 I StatusController: Last foreground:rikka.appops.pro uid:10282 Current foreground:moe.shizuku.privileged.api uid:10264
02-01 15:20:52.287  3277  3564 I WtProcessController: FOREGROUND INFO: name=moe.shizuku.privileged.api uid=10264 pid=6163 TaskId:3070
02-01 15:20:52.287  1633  2690 I Timeline: Timeline: App_transition_ready time:338564
02-01 15:20:52.290  5170  5170 D TouchAssistant: getPackageNameFromPid packageName:moe.shizuku.privileged.api
02-01 15:20:52.291  5170  5170 D TouchAssistant: onTopAppChanged packageName:moe.shizuku.privileged.api

02-01 15:20:52.352  3277  3564 I WtProcessController: MOVE TO FOREGROUND: rikka.appops.pro 10282
02-01 15:20:52.353  3277  3564 I StatusController: Last foreground:moe.shizuku.privileged.api uid:10264 Current foreground:rikka.appops.pro uid:10282

02-01 15:20:59.232  1633  7148 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity bnds=[648,1014][864,1328] (has extras)} from uid 10068 on display 0
02-01 15:20:59.244   469  2952 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
02-01 15:20:59.245  3277  3564 I WtProcessController: mCurTask:3071

02-01 15:20:59.248  1633  7148 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-01 15:20:59.266  3277  3564 I WtProcessController: MOVE TO FOREGROUND: moe.shizuku.privileged.api 10264
02-01 15:20:59.266  7128  7128 D BreventServer: update current to moe.shizuku.privileged.api
02-01 15:20:59.266  3277  3564 I StatusController: Last foreground:com.teslacoilsw.launcher uid:10068 Current foreground:moe.shizuku.privileged.api uid:10264
02-01 15:20:59.267  3277  3564 I WtProcessController: FOREGROUND INFO: name=moe.shizuku.privileged.api uid=10264 pid=6163 TaskId:3071
02-01 15:20:59.279  1633  7148 I Timeline: Timeline: App_transition_ready time:345556
02-01 15:20:59.283  5170  5170 D TouchAssistant: getPackageNameFromPid packageName:moe.shizuku.privileged.api
02-01 15:20:59.284  5170  5170 D TouchAssistant: onTopAppChanged packageName:moe.shizuku.privileged.api
02-01 15:20:59.285  5170  5170 D TouchAssistant: updateAll and mViewAdded = true
02-01 15:20:59.294  1633  1654 I Timeline: Timeline: App_transition_ready time:345572
02-01 15:20:59.296  2439  2439 D PhoneStatusBar: disable: 0x00000000 -> 0x00000200 (diff: 0x00000200)
02-01 15:20:59.297  2439  2439 D PhoneStatusBar: disable: < expand icons alerts ticker system_info back home recent clock full hide keyguard none float >
02-01 15:20:59.301  2439  2439 V PhoneStatusBarPolicy: updateManagedProfile mManagedProfileFocused: false mManagedProfileInQuietMode: false mKeyguardVisible: false mCurrentUserId:0 mCurrentProfileId:0 mSecondSpaceStatusIconVisible: true showIcon:false
02-01 15:20:59.334  6163  6163 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-01 15:20:59.367  6163  6163 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@62d1c62
02-01 15:20:59.367  6163  6163 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@5a721f3
02-01 15:20:59.380  3418  3418 D TextExpansionAccessibilityServicePro: onAccessibilityEvent: windows changeds
02-01 15:20:59.456  6163  6163 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@4c3dd9d
02-01 15:20:59.457  6163  6163 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9596212
02-01 15:20:59.505  1633  7148 D ui-boost: Set RenderThread tid 7198 for pid 6163 name=moe.shizuku.privileged.api


02-01 15:20:59.642  6163  6163 W art     : Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
02-01 15:20:59.652  1633  2690 E com.android.server.pm.PackageManagerServiceInjector: MIUILOG- Permission Denied getInstalledPackages. pkg : moe.shizuku.privileged.api uid : 10264
02-01 15:20:59.719  3418  3418 D TextExpansionAccessibilityServicePro: onAccessibilityEvent: windows changeds
02-01 15:21:00.045  1633  1654 I ActivityManager: Displayed moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity: +787ms
02-01 15:21:00.045  1633  1654 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{13b1022 u0 moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity t3071} time:346322
02-01 15:21:00.047  1633  7148 D ActivityTrigger: ActivityTrigger activityStopTrigger 
02-01 15:21:00.063  1633  7148 I WindowManager: Destroying surface Surface(name=com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher) called by com.android.server.wm.WindowStateAnimator.destroySurface:2043 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:895 com.android.server.wm.WindowState.destroyOrSaveSurface:2116 com.android.server.wm.AppWindowToken.destroySurfaces:366 com.android.server.wm.AppWindowToken.notifyAppStopped:394 com.android.server.wm.WindowManagerService.notifyAppStopped:4655 com.android.server.am.ActivityStack.activityStoppedLocked:1300 com.android.server.am.ActivityManagerService.activityStopped:7270 
02-01 15:21:00.065  5170  5182 D TouchAssistant: long enough since last foreground time, force update
02-01 15:21:00.065  5170  5170 D TouchAssistant: topActivity.getPackageName(),packageName:moe.shizuku.privileged.api
02-01 15:21:00.065  5170  5170 D TouchAssistant: onTopAppChanged packageName:moe.shizuku.privileged.api
02-01 15:21:00.244  1633  1654 I WindowManager: Destroying surface Surface(name=Starting moe.shizuku.privileged.api) called by com.android.server.wm.WindowStateAnimator.destroySurface:2043 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:895 com.android.server.wm.WindowState.destroyOrSaveSurface:2116 com.android.server.wm.AppWindowToken.destroySurfaces:366 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:313 com.android.server.wm.WindowAnimator.animateLocked:714 
02-01 15:21:01.329  2439  2439 D BatteryController: action=android.intent.action.BATTERY_CHANGED; mCharging=false

02-01 15:21:02.219  2439  2439 W ProgressBarDelegate: Unknown Drawable subclass, src=android.graphics.drawable.ScaleDrawable@fda8a4e
02-01 15:21:02.232  1633  7148 D PerfShielderService: moe.shizuku.privileged.api|moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity|437|346441559136|301|0
02-01 15:21:02.234  3081  3093 D MiuiPerfServiceClient: interceptAndQueuing:6163|moe.shizuku.privileged.api|437|301|running|null

**Comment by haruue** [comment]
当 WiFi 断开时
```
ShizukuClient: can't connect to server: Permission denied
```
所以会不会是开了流量节省或者限制了这个应用的后台流量使用？

**Comment by Tback1** [comment]
是的，应该是被代理vpn给本地映射出错了~~3Q @haruue
