### ISSUE TITLE
激活失败

### ISSUE THREAD

**Issue by iKCloud** [RikkaApps/Shizuku#180]
PS C:\platform-tools> .\adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh
sh: /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh: Permission denied
这是激活失败的信息。但是，adb激活黑阈成功，激活冰箱和shizuku都失败。用黑阈激活冰箱成功，激活shizuku失败。
机型华为NOVA9PRO，系统鸿蒙201，shizuku版本12.4.3。
同时查看了文件夹内容，moe.shizuku.privileged.api/files下没有文件。

**Comment by RikkaW** [comment]
adb 应该有权限访问 Android/data 的，清除数据再试试吧（

**Comment by iKCloud** [comment]
> 

清除数据，卸载重装都试过了，还是不行。

**Comment by iKCloud** [comment]
确认应该是鸿蒙系统本身的问题。鸿蒙的开发者模式缺少一个无线调试，应该是和安卓还有挺大区别的，放弃了。
