### ISSUE TITLE
Stuck on "Waiting for service"

### ISSUE THREAD

**Issue by MarissaRS** [RikkaApps/Shizuku#181]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment
- [N/A] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 12.4.3.r713.e5d22d5
- Mode: [adb, root] ADB
- Android version: Android 12, January security patch (GrapheneOS)
- Device: Pixel 4

**Logs:**

Related **full logcat**.

https://nl.tab.digital/s/My7Qn388fxoDDLf

**Describe the bug:**

1) Launch Shizuku
2) Follow steps to enable Wireless ADB, pairing process
3) After successful pairing, click "Start"
4) App gets stuck on "waiting for service":

```
Starting with wireless adb...

info: start.sh begin
info: attempt to copy starter from /storage/emulated/0/Android/data/moe.shizuku.privileged.api/starter to /data/local/tmp/shizuku_starter
info: exec /data/local/tmp/shizuku_starter
info: starter begin
info: killing old process...
info: apk path is /data/app/~~97wnG83klhOaI3yTI2xH5g==/moe.shizuku.privileged.api-xa-zMUZUPzxPbeQ4Qyfo8Q==/base.apk
info: starting server...
info: shizuku_starter exit with 0

Waiting for service...


```

**Additional context:**

I am using GrapheneOS without root.

**Comment by RikkaW** [comment]
The log file you provide only contains logs from "com.tortel.syslog". Log catcher apps should have some tutorial about how to catch system wide logs.

**Comment by MarissaRS** [comment]
> catch system wide logs. 

My apologies Here is the new log file:

https://nl.tab.digital/s/My7Qn388fxoDDLf

**Comment by MarissaRS** [comment]
My apologies. Here is the new log file:

https://nl.tab.digital/s/My7Qn388fxoDDLf

**Comment by vvb2060** [comment]
GrapheneOS

**Comment by RikkaW** [comment]
```
java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/app/~~ClNqyD31S5E0m3YkF6OaBA==/moe.shizuku.privileged.api-kcTT7rr3CRWfuJUEBIy58g==/base.apk!/lib/arm64-v8a/librish.so" segment 0: Permission denied
```

The reason is unknown. I'm not sure if this is some restrictionfrom GrapheneOS. (disallow adb to mmap executable?)

**Comment by RikkaW** [comment]
Just learned from others that GrapheneOS makes tons of changes to the Android framework. His exact words, "I'm not surprised anything happens on GrapheneOS".

**Comment by srappan** [comment]
Is there anyway to make progress on this for GrapheneOS?

**Comment by RikkaW** [comment]
@srappan That's impossible because GrapheneOS limits the permission of adb, nothing we can do.
