### ISSUE TITLE
手机锁屏后打开adb失效，不息屏正常

### ISSUE THREAD

**Issue by liu1352183717** [RikkaApps/Shizuku#183]
手机型号OnePlus 8T
安卓11

**Comment by liu1352183717** [comment]
做了的呢，没用

2022-02-05 

1352183717 



发件人：Rikka ***@***.***>
发送时间：2022-02-03 21:29
主题：Re: [RikkaApps/Shizuku] 手机锁屏后打开adb失效，不息屏正常 (Issue #183)
***@***.***>
***@***.******@***.***>

https://shizuku.rikka.app/zh-hans/guide/setup/#_5-shizuku-%E9%9A%8F%E6%9C%BA%E5%81%9C%E6%AD%A2 该做的都做了吗（
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RikkaW** [comment]
不愿透露姓名的 vv：一看就是没开USB调试，然后锁屏断网。应该直接close。

**Comment by M69W** [comment]
> 不愿透露姓名的 vv：一看就是没开USB调试，然后锁屏断网。应该直接close。

@RikkaW 

一样的机型和系统（Android 11、Hydrogen OS 11.0.14.14.KB05)
其实是开启了，包括电池优化也选择了不优化，还是 息屏就失效。

之前是没问题的，后来使用随身WiFi(高通 410 刷了 OpenStick)，既然是 Linux 系统就用 Termux 先试试能不能通过 ADB 形式 使用，连接了 这个WiFi 的 热点然后一顿操作，就出现楼主一样的问题了。
即使是通过电脑 ADB 开启，只要一息屏就失效。

两个 App 都试过设置，问题还是有，手机也试过关机重启，问题仍存在。

就是最后，在开发者里面不知道设置了什么就好了
即使是设置了电池优化(开启 智能控制)，息屏也能存活

不知道这里有没有提示有用的信息，或者怎么提供所需的信息

**Comment by DustinWin** [comment]
一样的问题，澎湃 os，“省电策略”已开启“无限制”，开机运行也开启了。只要一锁屏就停止运行。

**Comment by M69W** [comment]
我现在改为无线调试启动了。
1、首页，点 配对，点 开发者选项，勾选 无线调试，通知栏提示要搜索验证码，
2、返回首页，启动

好处是只要有热点就行，不需要电脑
