### ISSUE TITLE
[Android 13 DP1] Keep showing "waiting for service" when using wireless adb

### ISSUE THREAD

**Issue by SonodaKazuto** [RikkaApps/Shizuku#194]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 12.4.3.r713.e5d22d5
- Mode: [adb, root] adb
- Android version: 13 DP1
- Device: (optional) Pixel 6 Pro

**Comment by RikkaW** [comment]
The lastest CI version has already support Android 13 DP1.

https://github.com/RikkaApps/Shizuku/actions
