### ISSUE TITLE
Version 12.6.0.r762.6812764 wont start

### ISSUE THREAD

**Issue by dragonGod97677** [RikkaApps/Shizuku#198]
As on the title, it wont start, it returns code 0 but it just stuck on waiting for service

**Comment by dragonGod97677** [comment]
Here's my device details by the way
 Oppo Neo 5 (1201), running on custom rom,  AospExtended-v4.6-UNOFFICIAL based on Android 7.1.2, SELinux is permissive, rooted with the latest magisk

**Comment by RikkaW** [comment]
Where is your log :)

**Comment by dragonGod97677** [comment]
> Where is your log :)



> Where is your log :)

[2022-03-02_01.15 latest.zip](https://github.com/RikkaApps/Shizuku/files/8163538/2022-03-02_01.15.latest.zip)
[2022-03-02_01.06 before update to latest.zip](https://github.com/RikkaApps/Shizuku/files/8163541/2022-03-02_01.06.before.update.to.latest.zip)

**Comment by RikkaW** [comment]
> 03-02 01:14:43.716 I/art     (21585): System.exit called, status: 50
> 03-02 01:14:43.716 I/AndroidRuntime(21585): VM exiting with result code 50.

https://github.com/RikkaApps/Shizuku/blob/8df3c308ecad9eed7b9b35c9b430143460ff5af9/server/src/main/java/rikka/shizuku/server/ShizukuService.java#L96-L99

`50` is `MANAGER_APP_NOT_FOUND`.  This means, for some reason, Shizuku service process (it runs under root or adb) cannot find Shizuku app. 

Shizuku service requires Shizuku app installed in the primary user. This part haven't change for a very long time and "Previous versions of shizuku works though", so this is not your case and this is obviously not a problem of Shizuku. You should check if you have wired modules installed that prevents adb or root to use APIs like `getPackageInfo`.
