### ISSUE TITLE
细化权限管理

### ISSUE THREAD

**Issue by maxelblack** [RikkaApps/Shizuku#199]
如题，希望添加细化的权限管理功能。

众所周知adb权限还是可以细分的，单纯的整个adb授权对于某些软件来说不符合最小权限原则。（比如安装器类的软件只需要管理软件包的权限，而adb有修改大部分系统配置的权限）

没有比较细的权限管理，可能会对非开源或无法开源的软件（比如icebox之类的付费解锁制软件）的用户群体造成一定限制，有的用户不想放心将高权限交给非完全开源的软件，有的用户甚至尽可能去自己编译需要高权限的开源软件。

其实最关键的还是修改系统配置的权限，如果细化权限管理比较难实现的话，希望考虑单独添加一个允许修改系统设置的选项。

**Comment by haruue** [comment]
你提出的这个需求， 需要对系统相关实现进行修改（例如， 使用 Xposed 模块）才能实现。 这不属于 Shizuku 的范畴， 在只有 adb （不对手机进行 root + Xposed）的情况下也不可能实现。

**Comment by maxelblack** [comment]
其实或许可以单独写一个API套壳adb来实现？

**Comment by RikkaW** [comment]
若要实现你的想法必然只能限制使用者只能使用这个[转发 binder transact 的功能](https://github.com/RikkaApps/Shizuku-API/blob/2b7abf8a09c18187b1d1bd3557b93f5f352d88c3/server-shared/src/main/java/rikka/shizuku/server/Service.java#L135-L156)，**而仅使用转发 binder transact 的功能显然不够覆盖所有的使用场景（例如操作文件）**。你显然不可能限制别人开发的程序只能用这个。

此外，转发 binder transact 的功能唯二知道的信息只有目标 binder 的 description （例如 `android.app.IActivityManager`） 和 transaction code（一个数字）。即使可以通过一些方式取得对应的 API 的名字，建立 API 的名字和细化的权限的工作量也过于巨大（有上百个系统服务，每个系统服务有数个到数百个 API）。简单地说，就是简简单单的原样转发，里面是什么很难知道，你所说的“其他应用程序调用这个 API”、“修改系统配置的权限”的概念是不存在的。

再另外，如果一个用户真的很清楚一个细化的权限能做什么，那么他对这套东西如何工作就已经有了相当程度的了解了，可以说离实现自己想要的功能就真的只有把代码写出来的距离了。

最后一句，个人觉得你的追求和「要求 Magisk 推出限制 root 能做什么」类似，都是不太可取的。用魔法程序，要么就信任它，要么就寻找开源的方案或者自己编写自己的程序。
