### ISSUE TITLE
Ip v6 required

### ISSUE THREAD

**Issue by j-romchain** [RikkaApps/Shizuku#200]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: v12.6.0.r762.6812764
- Mode: [adb]
- Android version: 10
- Device: (optional) samsung s9+

**Logs:**

Related **full logcat**.  **Incomplete*Starting with wireless adb...

java.net.UnknownHostException: Unable to resolve host "ip6-localhost": No address associated with hostname

**Describe the bug:**

Start via wireless adb fails if only using ipv4, and ipv6 not configured

**Additional context:**

Wireless debugging is enabled using adb tcpip 5555 on desktop.   Other local adb apps work connecting to localhost. Lan does not support ipv6, and no ipv6 ip address has been assigned to the device.

It does work on public wifi or mobile data, when an ipv6 ip address has been assigned.

**Comment by Chinese-Cyq20100313** [comment]
Me too.
I tried add ::1 ip6-localhost to /etc/hosts file.
But it's still not work!

**Comment by RikkaW** [comment]
Try this build? https://github.com/RikkaApps/Shizuku/actions/runs/2032599113
