### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Yukkun** [RikkaApps/Shizuku#201]
Please report bugs of Shizuku itself.

**Requirements:**

- [X] Shizuku version is up-to-date
- [X] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [X] Shizuku is not running in a virtual environment
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 12.6
- Mode: ADB
- Android version: 8.0.0 (EMUI 8.0.0 also) 
- Device: Huawei Mediapad T5 (AGS2-L09)

**Logs:**
This will be provided when someone bothers to explain me where and how to get them.

**Describe the bug:**
On my tablet, in TachiJ2K the updating using Shizuku does not work at all. I have enabled "Allow ADB debugging options in 'Charge only' mode".

I also have TachiJ2K on my phone and on WSA, on both of those there are no issues, so I can't imagine this being nothing but Shizuku issue

**Comment by RikkaW** [comment]
Is seems that your problem is a software (TachiJ2K) or system (modifications from your Huawei Mediapad T5) problem.
