### ISSUE TITLE
Add password support

### ISSUE THREAD

**Issue by redsigma** [RikkaApps/Shizuku#204]
Is it possible to make shizuku ask for a password before installing something.

Either a global password or a password per application can work.

Thanks

**Comment by RikkaW** [comment]
Shizuku does not provide any "real function". For example, Shizuku does not provide the function of "install something" you mentioned. For Shizuku, its nearly impossible to identify what an user app want to do detaily, e.g., if the user app wants to "install something".

There is already a "request permission" process, its obviours meaningless to add another password.
