### ISSUE TITLE
wifi配对启动出错

### ISSUE THREAD

**Issue by immaruko911** [RikkaApps/Shizuku#205]
- Shizuku version: 12.6.0
- Mode: [adb, root]
- Android version: MIUI 13.0.3
- Device: (optional)

**Logs:**

Starting with wireless adb...

javax.net.ssl.SSLProtocolException: Read error: ssl=0xb400007447e70cc8: Failure in SSL library, usually a protocol error
error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:594 0xb4000073d9e9a008:0x00000001)

**Comment by RikkaW** [comment]
是否已经进行过配对步骤呢

**Comment by immaruko911** [comment]
k40 miui13 不可以 
另一台1加3刷了 mokee安卓10 一下就成功了

**Comment by RikkaW** [comment]
问的是有没有进行配对步骤呀，“安装无线配对”是什么乱七八糟的。
另外，新式的无线调试（也就是先要配对的那种）是从 Android 11 添加的，Android 10 的扯不到。

**Comment by immaruko911** [comment]
系统的wifi adb 配对打开了 配对码也看见了 打开程序配对时 控制台就报了这个错误  然后通知里一直显示配对中

**Comment by haruue** [comment]
能录个屏发上来方便我们确认问题么？ MIUI 有自带的屏幕录制。

**Comment by haruue** [comment]
就把你从 Shizuku 点击「配对」开始， 到看到你发的这条错误信息的全过程屏幕录制发上来就可以。

**Comment by haruue** [comment]
哦我知道了， MIUI 13 从某个版本开始， 即使把通知改成了「原生样式」， 也无法从通知栏输入配对码。

**Comment by haruue** [comment]
我这边测试在 Xiaomi 11 MIUI 13.0.5 上， 仅通过无线调试是可以顺利启动 Shizuku Server 的， 麻烦您发送一下录屏来让我们能更容易地找到问题的原因。

**Comment by immaruko911** [comment]
https://user-images.githubusercontent.com/83220321/160905289-86880126-c8a3-49e6-814c-ff4abefc08fe.mp4

不太会 弄了半天 您看看这个可以不可以用

**Comment by haruue** [comment]
您好， 在观看了您的视频之后， 我想我已经找到了问题。
MIUI 的「开发者选项」里「无线调试」这个选项， 它不仅是一个开关， **你只要点左边， 它还能点进去。**
我录制了视频告诉你应该如何启动。

https://alicemana.moe/static/shizuku-pair-miui13.mp4

请注意 MIUI 的「开发者选项」界面设计与 Shizuku 项目无关， 如果您觉得是因为 MIUI 的设计有问题导致您无法执行正确的操作， 你应该向 MIUI 团队提交反馈。

**Comment by RikkaW** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/12999176/160987140-b249aaa1-6e5d-41a1-81b6-9e5d44f26778.png">
虽没有明确说明，但是网站中的教程也对“无线调试”选项左侧是可以点击的做出了提示。教程入口是应用内的“分步骤教程”。

**Comment by haruue** [comment]
在 Android 11 以及之前的 AOSP ， 这种可以点进去的开关其实长期被用于系统的 WLAN 设置中， 这种用一条线分隔成两个部分的 UI 设计十分明显， 能够很好地提示用户这是可以点进去的。
![photo_2022-03-31_14-19-20](https://user-images.githubusercontent.com/13131972/160989384-4071c432-ecfc-4275-99e3-71d65b6f2236.jpg)

然而到了 MIUI 这里却变成了一个几乎看不到并且令人感到不明所以的箭头。
![Screenshot_20220331_141708](https://user-images.githubusercontent.com/13131972/160989454-bb14b5ae-7288-4738-87fd-53efec6275de.png)

~~**雷军！金凡！**~~

关闭此 Issue 因为这本质上不是 Shizuku 的问题。

**Comment by immaruko911** [comment]
感谢楼主耐心 按照您给的方法已经可以进入最后一步 可惜现在卡在输入配对号 死活不让输入 这回也没有报错😂
 算了不折腾了 我怀疑是不是我装了什么跳过广告或者还有什么权限的问题了

**Comment by haruue** [comment]
配对号的那个通知在 MIUI 上是要点一下右边的向下箭头才会显示「输入配对码」的按钮。
![image](https://user-images.githubusercontent.com/13131972/161058091-547ad5bb-d22c-4e61-8ebb-2c41abcf37f1.png)
![image](https://user-images.githubusercontent.com/13131972/161058106-bdb66bd3-2034-44e5-a4d0-d785b949ec40.png)
另外「正在进行配对」的通知可能是不会消失的， 直接上滑通知栏看到已配对设备有 shizuku 了即可。
![image](https://user-images.githubusercontent.com/13131972/161058328-a0d4051a-6b70-44cf-92e1-383cddb898c3.png)

**Comment by immaruko911** [comment]
![Screenshot_2022-04-02-01-47-36-793_com android settings](https://user-images.githubusercontent.com/83220321/161315915-bb6fcbfb-3174-4776-bfcf-5260a275c46d.jpg)
哭了 我的没箭头儿

**Comment by haruue** [comment]
下面这个「输入配对码」的按钮是点了没有反应么？
![image](https://user-images.githubusercontent.com/13131972/161316199-798971e4-7aa2-48cc-bb1d-6a3a6243dc2f.png)

**Comment by haruue** [comment]
经过测试这是因为你的 MIUI 的「通知显示设置」还是「经典样式」。
这个在 Shizuku 的配对页面里是有明确的红色提示的。
![image](https://user-images.githubusercontent.com/13131972/161362269-2069ca8a-07db-47cf-acc3-a47d4168d09e.png)
请务必认识到你使用的是一个严重修改的系统， Shizuku 界面上的每一条提示都很重要。

**Comment by immaruko911** [comment]
非常感谢楼主 成功啦  哇哈哈哈哈
