### ISSUE TITLE
Pairing not working on language . Arabic

### ISSUE THREAD

**Issue by Saliver7Sky** [RikkaApps/Shizuku#209]
Requirements:

- Shizuku version is up-to-date
- Shizuku is downloaded from official channels (GitHub release or Google Play)
- Shizuku is not running in a virtual environment
 (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

Reports not meet the requirements will be immediately closed.

Information:

Shizuku version: v12.6.0
Mode: [adb,] wireless debug port
Android version: 12
Device: (optional) Samsung S21Ultra

Shizuku app Pairing not working on language . Arabic
When entering the code .Show running Pairing . 
And he does nothing
But when you switch the language to English. is contacted
sorry for the bad translation

**Comment by RikkaW** [comment]
This build (https://github.com/RikkaApps/Shizuku/actions/runs/2218769822) should solve your problem.
