### ISSUE TITLE
shizuku的starter无法执行

### ISSUE THREAD

**Issue by dontknowhy** [RikkaApps/Shizuku#213]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
latest
- Mode: [adb, root]
adb
- Android version:
11
- Device: (optional)
BRT-W09

**Logs:**
adb's sh: Permission denied
Related **full logcat**.

**Describe the bug:**
adb can't start
似乎HONOR的adb都被噶了一把，导致即使手动拷贝start.sh和starter文件都提示starter文件未找到，导致adb无法正常启动shizuku
**Additional context:**

**Comment by dontknowhy** [comment]
建议像小黑屋一样使用设备管理员（adb shell dpm set-device-owner web1n.stopapp/.receiver.AdminReceiver）解决HONOR设备禁用通过配对码连接设备和禁用在设置里启用无线调试（真的，要usb连接adb后手动tcpip开启才能连接）这一SB问题

**Comment by haruue** [comment]
DPM 的 device/profile owner 无法启用和配对无线调试， 仅通过 DPM 也无法实现 Shizuku 的功能， 因此添加 DPM 支持并不能对你遇到的问题提供帮助。

或许你可以试试能不能使用类似于 [Hidden Activity Launcher](https://play.google.com/store/apps/details?id=com.andrefrsousa.tools.activitymanager) 的应用从「设置」里找到无线调试的功能。 如果找不到的话那就没办法了， 下回买手机别买 HONOR 。

**Comment by dontknowhy** [comment]
行…
我去催催小黑屋看看能不能通过小黑屋的DPM打开starter…

dontknowhy

________________________________
发件人: Haruue ***@***.***>
发送时间: 2022年5月29日星期日 下午10:09
收件人: RikkaApps/Shizuku ***@***.***>
抄送: dontknowhy ***@***.***>; State change ***@***.***>
主题: Re: [RikkaApps/Shizuku] shizuku的starter无法执行 (Issue #213)


DPM 的 device/profile owner 无法启用和配对无线调试， 仅通过 DPM 也无法实现 Shizuku 的功能， 因此添加 DPM 支持并不能对你遇到的问题提供帮助。

或许你可以试试能不能使用类似于 Hidden Activity Launcher<https://play.google.com/store/apps/details?id=com.andrefrsousa.tools.activitymanager> 的应用从「设置」里找到无线调试的功能。 如果找不到的话那就没办法了， 下回买手机别买 HONOR 。

―
