### ISSUE TITLE
[suggestion] Android TV UI support

### ISSUE THREAD

**Issue by Qutaiba-Khader** [RikkaApps/Shizuku#220]
Thanks for all your work,

I'm using this application for my Nvidia shield/GoogleTV/ mi box , and it's working great can you please add the application to TV play store? Because it's very useful with app-ops 

And if you don't mind just enable it to usable with mouse,

Thanks again

**Comment by RikkaW** [comment]
Publish applications to TV Play Store requires the application to have a real TV UI, I don't have much time and experience to do this. Also, Google Play has extra review steps on TV apps, apps like Shizuku may be in the grey area of the Play Store policy, extra review may trigger Google to take down Shizuku entirely for random reasons.
