### ISSUE TITLE
[Question] shizuku_starter location in Shizuku pre-built APKs

### ISSUE THREAD

**Issue by linuxct** [RikkaApps/Shizuku#221]
Hi, 

I would like to understand from where is `shizuku_starter` ELF binary generated, or extracted.
Thanks.

**Comment by haruue** [comment]
The ELF is named `libshizuku.so` in the Shizuku apk file.
```
lib/armeabi-v7a/libshizuku.so
lib/arm64-v8a/libshizuku.so
lib/x86/libshizuku.so
lib/x86_64/libshizuku.so
```

You can find its build code here
https://github.com/RikkaApps/Shizuku/blob/e9e41212479f3aabf7cb864d9b1ad450470d6005/manager/src/main/jni/CMakeLists.txt#L31-L32

You can find its copy code here
https://github.com/RikkaApps/Shizuku/blob/e9e41212479f3aabf7cb864d9b1ad450470d6005/manager/src/main/java/moe/shizuku/manager/starter/Starter.kt#L94
