### ISSUE TITLE
Pairing stuck on searching for pairing service notification

### ISSUE THREAD

**Issue by J0shua-code** [RikkaApps/Shizuku#222]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 1.2.8.1
- Mode: [adb, root]
- Android version: 12
- Device: S22+

**Logs:**

Related **full logcat**.

**Describe the bug:**

Pairing doesn't work on S22+ android 12. The notification is stuck on searching for pairing service.

**Additional context:**

**Comment by DentFuse** [comment]
Facing the same issue on Realme GT Master Edition.

**Comment by J0shua-code** [comment]
![edit_20220627072313](https://user-images.githubusercontent.com/40670164/175914885-e7299e55-a966-4a1f-a1b1-e5f9cf4f405b.jpg)

Works for me

**Comment by RikkaW** [comment]
@J0shua-code What if run Shizuku and paring in split screen mode?

**Comment by RikkaW** [comment]
<img width="249" alt="image" src="https://user-images.githubusercontent.com/12999176/175916906-b67182c1-3e16-4d8c-8dd2-917ff9cdf3de.png">

Ok, Samsung do the same thing as MIUI, it blocks apps to access network once the user leaves it. Disable anything like battery optimization, background limit, sleep app, balabala, for Shizuku, then split screen should not be required.

For your new problem, turn off and on wireless debugging, it should work.

**Comment by J0shua-code** [comment]
turning wireless debugging on/off made it work, thanks!

**Comment by woobhurk** [comment]
> The pairing notification works in splitscreen! And Shizuku is added to paired devices, but cannot start Shizuku. ![Screenshot_20220627-073236_Settings](https://user-images.githubusercontent.com/40670164/175916633-68c63d59-f81a-4d64-bbe9-4d2e33cb596d.jpg)
> 
>  Screen_Recording_20220627-073050_Shizuku.mp4

I use this method and successfully paired, then start Shizuku server!
If you cannot start Shizuku server, please try repair with wireless debugging. :)
