### ISSUE TITLE
Some bugs and questions about work

### ISSUE THREAD

**Issue by ThIsLinked** [RikkaApps/Shizuku#227]
Hello. There are several questions, but for some reason only the "Bug" report option is available? But it doesn't matter.

1. Inside Shizuku, I chose the localization "English". But in the "Use Shizuku in terminal apps" tab, Russian localization (string-ru) is used in the title in a ActionBar, when English (default string, since there is no string-en among localizations) should be used. Why did this happen? My system language is set to "Russian" (ru).
<details>
<summary>Screenshot</summary>

![Screenshot_1](https://user-images.githubusercontent.com/45180688/177047390-153ca7a5-54c2-4701-94ad-a5696c82ef01.jpg)

</details>

2. I also noticed in this tab here is such a misunderstanding. Why is there no indent from the markup ceiling (pic. 1)? With the help of the Dev Assistant, I was able to find out the margin of this CardView on the sides. It is 12dp. I tweaked the layout of this window a bit and made marginTop equal to what is used on the sides. Now the appearance is more correct (pic. 2). Maybe you should fix it in the source code?
<details>
<summary>Screenshots</summary>

![Screenshot_2-3](https://user-images.githubusercontent.com/45180688/177048278-4be2197b-9972-4dcc-ac23-2f0c6d4b27ee.jpg)

</details>

3. (side question) I can't find your AppOps repository. Is he not on GitHub?

4. I don't understand the purpose of the rish script. Did I understand correctly that if I run this script in the terminal, then in the future with help Shizuku I can use ADB privileges inside this terminal?

**My device:
Huawei P smart Z, Android 10 (EMUI 10.0.0), build 10.0.0.255. security patch from July 1, 2021.**

_The text was translated using Google Translate, since I do not know English thoroughly. Therefore, it may contain errors. I apologize in advance._

**Comment by RikkaW** [comment]
1. Probable reason: `attachBaseContext` is not early enough or Activity title does not use Activity context.
2. The AppBar only changes its color when the content scrolls, it looks correct when the content does not scroll. But it's better to add some padding.
3. As a paid app, it's close sourced. Open source paid/freemium apps mean "free version" everywhere. There is even a case where a freemium app open sources on GitHub is published to F-Droid with payment checks removed (of course, it's not approved by the author). See https://t.me/vvb2060Channel/682 (it's in Chinese).
4. The script uses `/system/bin/app_process` to run a dex (Java codes). There is no public native (C/C++) API to run load Java codes), so

**Comment by haruue** [comment]
> I don't understand the purpose of the rish script. Did I understand correctly that if I run this script in the terminal, then in the future with help Shizuku I can use ADB privileges inside this terminal?

Did you have ever used the `sudo` command on Linux?

The command `sudo -i` lets you obtain a new shell session with root permission, and you will have the elevated permission in the session. Once you leave the session created by sudo (e.g. by pressing Ctrl-D or with the `exit` command), you will return to the original user.

The `rish` script acts exactly like `sudo`, except the root permission is replaced by the adb permission on the Android.

**Comment by ThIsLinked** [comment]
> [@RikkaW](https://github.com/RikkaApps/Shizuku/issues/227#issuecomment-1173143037)
> Probable reason: `attachBaseContext` is not early enough or Activity title does not use Activity context.

I restarted the app - it didn't fix the problem. Of course, changing the system language will fix this, but this is not what we need.

I have not watched his concept of work, so I will not suggest anything.
> [@RikkaW](https://github.com/RikkaApps/Shizuku/issues/227#issuecomment-1173143037)
> The AppBar only changes its color when the content scrolls, it looks correct when the content does not scroll. But it's better to add some padding.

I'm not talking about the AppBar you call. In general, don't mind the other colors - it's when I drew the pointers in Ai that I forgot to return the sRGB color profile and probably saved it in Adobe RGB (1999). Therefore, they look different.

I meant that the CardView, which has a hint about "rish" in itself, does not have an indent from the top. You can see this in picture 1. In picture 2 I added a marginTop is 12dp to it - now it has a padding. Or is it my local problem that there is no indentation initially?

By the way, I'm sorry, I forgot the technical information about the device - I added it to the header.
> [@RikkaW](https://github.com/RikkaApps/Shizuku/issues/227#issuecomment-1173143037)
> As a paid app, it's close sourced.

You can publish binaries without source code. For example, this policy is used in Adguard projects. I just prefer to first look for content in the offical repositories, and then in the Play Store.

**Comment by ThIsLinked** [comment]
> [@haruue](https://github.com/RikkaApps/Shizuku/issues/227#issuecomment-1173146905) 
> Did you have ever used the `su` command on a rooted Android device?

I know how the session works from the "root" user and his `su` binary. You misunderstood the question, but at the same time answered it. More precisely, you confirmed my hypothesis. In addition, your log from the terminal confirms this.

With the help of "rish", the terminal starts working on behalf of ADB, I mean, the shell. This is quite handy on non-rooted devices.

**Comment by RikkaW** [comment]
> You can publish binaries files (apk and other) without source code. For example, this policy is used in AdGuard projects. I just prefer to first look for content in the offical repositories, and then in the Play Store.

https://github.com/RikkaApps/App-Ops-issue-tracker/releases/tag/files

> The only downside is that you can't put the path into the PATH variable because you don't have root privileges (maybe there is a possibility that I don't know about?).

You can update PATH in your terminal app.

`export PATH=(somewhere your terminal app can access):$PATH`

> Probable reason: attachBaseContext is not early enough or Activity title does not use Activity context.

This is technical information.

**Comment by ThIsLinked** [comment]
> [@RikkaW](https://github.com/RikkaApps/Shizuku/issues/227#issuecomment-1173325214) 
> `export PATH=(somewhere your terminal app can access):$PATH`

As a terminal, I use a small terminal in MT Manager. I've added path, `echo $PATH` among the lines has my directory, and I can really call rish from anywhere now. But here's the problem: dex, which is nearby, is no longer detected by the rish script - a message is displayed complaining that dex was not found, and sends to get acquainted with the manual.

_I didn't check it on other terminals, maybe it's a problem in MT Manager. Well, MT this is not a specialized terminal, just an additional function in it. Because of this, I won't be attaching screenshots and other arguments proving the problem - the nature of the question deviates from our theme of this repo. Just wrote this text as a note._

_If necessary, I will collect all the materials for the analysis of this phenomenon._

**Comment by muckmouf** [comment]
> But here's the problem: dex, which is nearby, is no longer detected by the rish script - a message is displayed complaining that dex was not found, and sends to get acquainted with the manual.

I also had this problem with terminal applications that I went through, what worked for me was using the Termux app and I went ahead and installed oh-my-zsh framework in Termux and then put in an alias to rish which was

`alias rish='sh /storage/self/primary/rish/rish'`

And then rish became accessible anywhere.

Then after editing the rish script to point to the package name of Termux, I was then able to call rish which started a new shell session with elevated permissions.
