### ISSUE TITLE
Application Management: The permission of adb is limited.

### ISSUE THREAD

**Issue by b4imetu** [RikkaApps/Shizuku#228]
**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku
- [x] Non-Root. LSPatch not enabled.

**Information:**

- Shizuku version: 12.8
- Mode: adb
- Android version: 12
- Device: (optional) Redmi K40 (MIUI 13 22.7.1 Nightly)

**Logs:**

Related **full logcat**.

**Describe the bug:**

![20220705164529](https://user-images.githubusercontent.com/41535001/177288966-62153b71-fa27-4f0a-9884-88d9f4a40af4.jpg)

Application Management: 
The permission of adb is limited. It's highly possible that your device manufacturer limits the permission of adb.

Is there any solution to this problem?

**Additional context:**

**Comment by haruue** [comment]
The blue underlined text "this document" is a link and can be clicked.

Did you check the document?

![image](https://user-images.githubusercontent.com/13131972/177291402-06e65ca1-af82-4bde-87a1-93a598769b6f.png)

**Comment by RikkaW** [comment]
"this document" will lead you to a webpage that shows this:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/12999176/177318605-6df00c27-d0a0-4468-9e61-e4a48f67e050.png">

**Comment by b4imetu** [comment]
Sorry to bother~ I have read [this document](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-the-permission-of-adb-is-limited), but I mistakenly thought "USB debugging (Security options)" and "USB debugging" were the same. So embarrassing!😜
