### ISSUE TITLE
Request: add explanation about how to replace adb&su commands in general

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [RikkaApps/Shizuku#229]
Currently it seems to handle very specific cases, such as permissions (replacement of "pm grant "). 

Can Shizuku completely replace all adb&su commands? Or is it restricted in some way?

There are various adb  command that can be useful, that use: "am", "pm", "appops".
There are also "su" commands that can be useful , such as a restart of the device/OS, copying/deleting a file that's in a protected folder

For example, on the popular libsu, the way to call any command using su is as such when I want to get the list of files names from a given path (even when it's protected) :

```
@WorkerThread
fun getFilesOfFolderUsingRoot(path: String): List<String> {
    val commandResult = Shell.su("ls -a $path\n").exec().out
    if (commandResult is ArrayList<String>) {
        commandResult.removeAll { it == "." || it == ".." }
        return commandResult
    }
    return commandResult.filterNot { it == "." || it == ".." }
}
```

What would be the equivalent on Shizuku?

**Comment by haruue** [comment]
Shizuku is not designed to simply execute those commands, using Shizuku to execute those commands itself is not a recommended implementation for apps using Shizuku (for Shizuku users, you can just simply use `rish` if you want to execute any commands with adb permission).

If you'd like to develop an app that utilizes Shizuku to do something you usually did with `adb shell` commands, you should find the implementation of those commands in the AOSP (you can find most of them [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/cmds/;l=1?q=frameworks%2Fbase%2Fcmds&sq=)), and find its core logic (how it interact with system services), then you will be able to call those system services with Shizuku, in your own app.

**Comment by RikkaW** [comment]
For Android commands, Android APIs (in Java) are behind them.

For Linux commands, Linux system calls (or their wrapper, libc) are behind them. For example, what behind `ls` is [`readdir`](https://man7.org/linux/man-pages/man3/readdir.3.html). Also, Java also wraps it, `java.io.File` for example.

Shizuku API provides `UserService` to allow the deveploper to run their Java codes and native codes (JNI) under high privilege.

**Comment by AndroidDeveloperLB** [comment]
@haruue @RikkaW I don't think I understand what you guys mean.
Are you saying that Shizuku cannot run such commands (on a non-rooted device) as I wrote? 
There are countless of commands that I can use for "su". I don't think the library covers them all...

Or Shizuku is only a replacement for adb commands, and that's it?
But even then, why isn't there a general adb API, that will cover everything?

**Comment by RikkaW** [comment]
> Shizuku API provides UserService to allow the deveploper to run their Java codes and native codes (JNI) under high privilege.

If you want to use it to execute commands, **yes you can (Runtime.exec)**. But why?

**Comment by RikkaW** [comment]
Shizuku provides demo, https://github.com/RikkaApps/Shizuku-API/tree/master/demo, including the exapmle of [UserService](https://github.com/RikkaApps/Shizuku-API/blob/master/demo/src/main/java/rikka/shizuku/demo/service/UserService.java).

You are already able  to **run any Java codes or native codes you want in high privilege**, why you still want to limit yourself in commands?

**Comment by AndroidDeveloperLB** [comment]
@RikkaW Running "Runtime.exec" without the device being rooted won't work for the command I wrote...
It requires a rooted device.

My question was if Shizuku can replace the need for a rooted device when using "su" commands.

The demo doesn't have the general solution as I've requested, not for "su" and not for "adb"

**Comment by RikkaW** [comment]
You still don't understand anything.

**Comment by vvb2060** [comment]
https://developer.android.com/guide/components/aidl
Learn it, or stop using shizuku.

**Comment by RikkaW** [comment]
RTFM, run the demo by youself.

**Comment by AndroidDeveloperLB** [comment]
@RikkaW It's a yes/no question:
Does Shizuku support replacement of "su" commands, so that you could run them on a non-rooted device?

Also, Is Shizuku only for adb commands? If so, what's the general API to run them, instead of very specific examples like on the demo?

**Comment by vvb2060** [comment]
shizuku is lower level than the su or adb commands.  If you like, you can implement the commands you need yourself.

**Comment by AndroidDeveloperLB** [comment]
@vvb2060 You mean I can do more with Shizuku on a non-rooted device, than with "su" on a rooted device?

Copy protected files (cp), change the permissions to them (chmod), ...
?

Can you please offer a general solution for this, if that's all true?
What do you mean that I can implement the commands? They already exist. Can't I just launch them to have the easiest solution?

**Comment by RikkaW** [comment]
> Does Shizuku support replacement of "su" commands, so that you could run them on a non-rooted device?

Of course, you can implement something like "su" , but you need to some more codes.

> Also, Is Shizuku only for adb commands? If so, what's the general API to run them, instead of very specific examples like on the demo?

You can run ANY Java or native code you want. This is the third time I'm talking about it.

**Comment by AndroidDeveloperLB** [comment]
@RikkaW Good. So can you please offer it on the docs/sample, to show how to run "su" commands in general, like the one I've presented?
This can be useful for apps that require root, and they already have many places that use "su" with various commands.

**Comment by RikkaW** [comment]
> Copy protected files (cp), change the permissions to them (chmod), ...

Are you learning how to code on your first day? Search for "java copy file", "linux c change permission" (in fact, Android providers android.system.Os class as systemcall wrapper, C is not needed), there are tons of the result.

UserService, UserService, UserService, you can run ANY Java or native code you want. This is the fourth time I'm talking about it.

**Comment by vvb2060** [comment]
shizuku is a tool for professional developers that provides comprehensive access to the Android framework.  If you only use command line, we don't recommend you to use shizuku, you can choose libsu.
