### ISSUE TITLE
[咨询]您好，我想请教一个问题

### ISSUE THREAD

**Issue by AnnAngela** [RikkaApps/Shizuku#23]
就是如何使用 Tasker 直接启动 Shizuku Server？
目前我的想法是用“发送意图”（中文翻译，我不知道英文原文是什么）来调起，但是我需要一个 Activity，操作类型和 Data（若有），如果可以的话请您告知，烦请回复~
EDIT: 举个例子，这是调起特定 APP 的应用管理页面的 intent
````
System > Intent:
       Action: android.settings.APPLICATION_DETAILS_SETTINGS
       Data:   package:com.yourpackage.name
       Target: Activity
````

**Comment by haruue** [comment]
Shizuku Server 并不是一个简单的 Android 组件，并且分 root 和 adb 模式，有一定的配置过程。
建议跳转到 Shizuku Manager 主界面然后让用户来启动。

或者，如果有 root 权限的话，试试调用 bash 去执行 Shizuku 的启动脚本，就是主界面显示的那个。

**Comment by haruue** [comment]
想跳转到 Shizuku Manager 主界面的方法就很多了，比如 [`PackageManager.getLaunchIntentForPackage()`](https://developer.android.com/reference/android/content/pm/PackageManager.html#getLaunchIntentForPackage%28java.lang.String%29) 拿到一个 intent ，然后 startActivity() 即可。

**Comment by AnnAngela** [comment]
不不不，我不是应用开发者，我只是因为手机重启后要等非常久才能等到 Shizuku Server 自启，所以想要用 Tasker 这个一开机就能自启动的 APP 来启动 Shizuku Server =。= 所以我就想知道如何启动而已

**Comment by haruue** [comment]
暂时无法通过发送 Intent 实现这个，因为 Android 本身的限制，Shizuku Manager 无法对外提供用于启动 Shizuku Server 的 Android 接口。

如果您是 Magisk 用户，那你可以尝试 @simonsmh 编写的 [Privileged Api Booter](https://github.com/Magisk-Modules-Repo/magisk-privileged-api-booter) 来解决 Shizuku Server 开机启动过慢的问题。只需在 Magisk “下载” 中检索 `Privileged Api Booter`

**Comment by AnnAngela** [comment]
好的，感谢您的回复~
