### ISSUE TITLE
Shizuku keeps stopping

### ISSUE THREAD

**Issue by HeyItsIshaan** [RikkaApps/Shizuku#230]
For some reason, after I grant Shizuku ADB permission using a PC, the app runs for sometime but stops again. Sometimes in 5 minutes sometimes in 1 hour. Battery Optimisations are disabled for the app and the device is a Samsung Galaxy M31 running stable OneUI 4.1 based on Android 12. The latest version of the app is installed from the Google Play Store

**Comment by shaggyskunk** [comment]
You're not Rebooting by any chance?
Have you tried Disabling adb Authorisation Time Out?

**Comment by alkain1** [comment]
Same for me, I disabled all the battery optimizations and allowed background activity, event pinned the app in memory (OnePlus / Oppo feature). But Shizuku service stops usually after few minutes. Running on OnePlus 9 Pro, Oxygenos 12 (Android 12).
I didn't reboot, also tried disabling adb authorisation time out, so far nothing helps.

**Comment by RikkaW** [comment]
Have you tried all the steps in this section [Start via wireless debugging/Start by connecting to a computer: Shizuku randomly stops](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-shizuku-randomly-stops)?

**Comment by alkain1** [comment]
Hey I reinstalled latest Shizuku and followed the steps again, its working now, I might have skipped a step. Ty for your help
