### ISSUE TITLE
鸿蒙系统2.0不支持呢？

### ISSUE THREAD

**Issue by rv1688** [RikkaApps/Shizuku#232]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ ] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
- Mode: [adb, root]
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**.

**Describe the bug:**

**Additional context:**

**Comment by rv1688** [comment]
发送指令后找不到目录

**Comment by RikkaW** [comment]
请你换位思考一下，如果是你来解决问题，别人就啪唧一句不知道到底是什么的东西，你会是什么感受。
