### ISSUE TITLE
[BUG] Black theme not working

### ISSUE THREAD

**Issue by PandoraHayami** [RikkaApps/Shizuku#235]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 12.9.1
- Mode: Both
- Android version: 10
- Device: LG Stylo 6 and Alcatel Joy Tab 2

**Logs:**

Not related

**Describe the bug:**

The Shizuku app's black theme is broken, looks exactly the same with it enabled or disabled. 

**Additional context:**

![Screenshot_20220807-183235](https://user-images.githubusercontent.com/79670265/183317991-bb1c7644-4cf6-4548-85cf-f06a742625ff.png)
![Screenshot_20220807-183230](https://user-images.githubusercontent.com/79670265/183317992-873c46e5-5011-47a3-a596-b1921daf0fd8.png)

**Comment by RikkaW** [comment]
Just make a note here, it seems that the background is different on lower Android version, this finally causes black theme not working.
