### ISSUE TITLE
adb command for battery optimisation

### ISSUE THREAD

**Issue by Droidphilev** [RikkaApps/Shizuku#237]
Please report bugs of Shizuku itself.

**Requirements:**

- [ ] Shizuku version is up-to-date
- [ ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ ] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
- Mode: [adb, root]
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**.

**Describe the bug:**

**Additional context:**

Hi,

Not a bug but: does anyone know the ADB command to keep Shizuku out of Doze (battery opimisation) please?
My device ( a special one) misses this interface in battery settings but still battery optimisation is there. After a while Shizuku gets killed. If i know the ADB command i can let it keep on running.

Thanks in advance!
Phil

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/issues/230#issuecomment-1207242718

**Comment by Droidphilev** [comment]
found out myself. it seems to be:

adb shell dumpsys deviceidle whitelist +moe.shizuku.privileged.api

**Comment by RikkaW** [comment]
This commit (https://github.com/RikkaApps/Shizuku/commit/234b1c8335e821e63fd5a4d923627b358ccfe11e) has already implemented "add Shizuku app itself to power save temp whitelist". Please be aware that the thing that does the real work is not Shizuku app itself, but a process started by adb. Keep Shizuku app itself not being kill does not help.

Once USB usage mode changes, all processes started by adb are killed. So, you should do all the steps in this section [Start via wireless debugging/Start by connecting to a computer: Shizuku randomly stops](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-shizuku-randomly-stops) before you try to kill Shizuku app itself alive.

**Comment by RikkaW** [comment]
The version include that commit (> 12.9.0) may not on Play Store, are you using version 12.9.0+?

**Comment by Droidphilev** [comment]
I downloaded shizuku-v12.9.1.r859.28c5098-release.apk for this device from Github. There is no Play Store on this device.

**Comment by PeterKW** [comment]
> +moe.shizuku.privileged.api

@Droidphilev Where did you find out about this command? Is there a link to where this comes from?
Thank you very much
