### ISSUE TITLE
Use Material You (Android 12+)

### ISSUE THREAD

**Issue by gltile-two-electric-boogaloo** [RikkaApps/Shizuku#238]
**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: Version 5.5.6.r1453.f44c5855.G
- Mode: [adb, root] root
- Android version: Android 13 (TP1A.220624.014)
- Device: (optional) Pixel 5 (redfin)

**Describe the bug:**

Shizuku doesn't follow the Android 12 system theme. It'd be better to follow the system theme, since everything else does.

**Comment by RikkaW** [comment]
There is a follow system color option in settings.
