### ISSUE TITLE
I can 't allow itI can't allow appI can't allow apps to use the ADB hack

### ISSUE THREAD

**Issue by Fiiiiixxxx** [RikkaApps/Shizuku#239]
I can't allow ADB hack applications, writes that the manufacturer has restricted access, what should I do? There is nothing on your site 
![Screenshot_2022-08-19-01-13-12-285_moe shizuku privileged api](https://user-images.githubusercontent.com/111520527/185525379-88ee8148-70d2-44ae-96a9-5e4efead9fc5.jpg)

**Comment by haruue** [comment]
Please check here for a device manufacturer related solution.
https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-the-permission-of-adb-is-limited

If the manufacturer of your device is not listed, please tell us who it is.

**Comment by Fiiiiixxxx** [comment]
I have it all turned on

**Comment by Fiiiiixxxx** [comment]
I am interested in how to allow applications to useI am interested in how to allow applications to use ADI am interested in how to allow applications to use ADB, in the application management tab

**Comment by haruue** [comment]
An application needs to be designed for Shizuku to use it.

If you are a developer who wants to make your own application to work with Shizuku, please check our [Developer guide](https://github.com/RikkaApps/Shizuku/blob/master/README.md) and [demo](https://github.com/RikkaApps/Shizuku-API/blob/2a1a0b9ff6f23f3911da91a4901a5d8a08f2da24/demo/src/main/java/rikka/shizuku/demo/DemoActivity.java#L171-L187) for how to request the Shizuku permission.

If you are just a user who wants to elevate a random application to the ADB permission, I am sad to tell you it is impossible.
