### ISSUE TITLE
How to start without adb and root

### ISSUE THREAD

**Issue by Denisbg2011game** [RikkaApps/Shizuku#243]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:latest
- Mode: [adb, root]none
- Android version:10
- Device: (optional)huawei

**Logs:**
Idk
Related **full logcat**.

**Describe the bug:**

icantstartitwithoutadb
**Additional context:**

no

**Comment by RikkaW** [comment]
That's impossible
