### ISSUE TITLE
在已经ROOT的设备上，能不能设置成自动启动shizuku server？

### ISSUE THREAD

**Issue by GongT** [RikkaApps/Shizuku#25]
RT

**Comment by haruue** [comment]
在使用 root 成功启动一次之后，Shizuku Manager 会在每次系统启动后自动启动 Shizuku Server ，由于 Android 系统限制可能需要几分钟的时间才能启动成功。

如果这个失败了或者太慢：
+ 如果你也是 magisk 用户，你可以尝试 simonsmh 写的特权 API 启动模块 https://github.com/Magisk-Modules-Repo/privileged-api-booter 。
+ 提供你的 手机型号、ROM、Android版本，以便我们进一步分析可能存在的问题。

**Comment by GongT** [comment]
OK了，在magisk里装了privileged-api-booter就好了

**Comment by jasonwells0327** [comment]
> OK了，在magisk里装了privileged-api-booter就好了

能不能发我一个？谢谢！jasonfly@126.com

**Comment by GongT** [comment]
> > OK了，在magisk里装了privileged-api-booter就好了
> 
> 能不能发我一个？谢谢！[jasonfly@126.com](mailto:jasonfly@126.com)

已经过时了，现在不应该还有这问题（以及我已经换成kernelsu了
