### ISSUE TITLE
Shizuku Installer: User Denied

### ISSUE THREAD

**Issue by BatobolotovBato** [RikkaApps/Shizuku#252]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 12.14
- Mode: [adb]
- Android version: 12
- Device: Xiaomi Redmi Note 9 Pro

**Logs:**

Error Shizuku-installer:

Device: Redmi Redmi Note 9 Pro | MIUI | Android 12 | Using FilterApkSource ApkSource implementation | SAI 4.5

This User is not allowed to install applications

Command: pm install-commit 627591986
Exit code: 1
Out:
Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
=============
Err:
(From SAI)

**Describe the bug:**

I tried to use the Shizuku to install applications through SAI but I always get this error

**Additional context:**

The error says that the user does not have access to install applications

**Comment by RikkaW** [comment]
It's MIUI's problem. See https://stackoverflow.com/a/49485273/5646408.
