### ISSUE TITLE
Linux adb 开启问题

### ISSUE THREAD

**Issue by psklf** [RikkaApps/Shizuku#26]
在 Linux 下使用 transfer data 模式连接手机，执行命令，启动 server 后，拔掉数据线，服务停止。（在 Linux 下连接手机无法使用 charge only 模式调试）

尝试使用
```
adb tcpip 5555
```
也没有效果

**Comment by haruue** [comment]
无法在我的 Linux && Pixel 3XL && Android 9.0 上重现问题，另外 charge only 模式应该也可以调试。
这种行为估计和你的手机的 ROM 有关，能不能提供一下以下信息：
1. 你的设备型号。
2. 你的设备运行的 Android 版本和厂商或第三方 ROM 的版本。
3. 你电脑上安装的 adb 版本 （电脑上执行 `adb version` 的输出）。

**Comment by psklf** [comment]
使用 charge only 模式解决。
issue close

**Comment by aceforeverd** [comment]
> 使用 charge only 模式解决。
> issue close

@psklf Can you explain steps debugging on charge only mode?
I have the same issue

**Comment by psklf** [comment]
> > 使用 charge only 模式解决。
> > issue close
> 
> @psklf Can you explain steps debugging on charge only mode?
> I have the same issue

## Method 1

Connect devices to computer and execute `lsusb`

Find current device's info:

```
Bus 001 Device 006: ID 2717:ff08
```

`2717` is VendorID and `ff08` is ProductID

Then create `/etc/udev/rules.d/51-android.rules` (sudo needed) and add this line:

```
SUBSYSTEM=="usb", ATTR{idVendor}=="2717", MODE="0666", GROUP="plugdev"
```

At last execute:
```
sudo chmod a+r /etc/udev/rules.d/51-android.rules
```

## Another simple approach

Use this one: ![android-udev-rules](https://github.com/M0Rf30/android-udev-rules)

**Comment by aceforeverd** [comment]
> > > 使用 charge only 模式解决。
> > > issue close
> > 
> > 
> > @psklf Can you explain steps debugging on charge only mode?
> > I have the same issue
> 
> ## Method 1
> Connect devices to computer and execute `lsusb`
> 
> Find current device's info:
> 
> ```
> Bus 001 Device 006: ID 2717:ff08
> ```
> `2717` is VendorID and `ff08` is ProductID
> 
> Then create `/etc/udev/rules.d/51-android.rules` (sudo needed) and add this line:
> 
> ```
> SUBSYSTEM=="usb", ATTR{idVendor}=="2717", MODE="0666", GROUP="plugdev"
> ```
> At last execute:
> 
> ```
> sudo chmod a+r /etc/udev/rules.d/51-android.rules
> ```
> ## Another simple approach
> Use this one: ![android-udev-rules](https://github.com/M0Rf30/android-udev-rules)

Thanks :)
Problem solved
