### ISSUE TITLE
I want to use rish in termux but  the terminal reports an error.    java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by solakksk** [RikkaApps/Shizuku#262]
Please report bugs of Shizuku itself.

**Requirements:**

- [x ] Shizuku version is up-to-date
- [x ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x ] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x ]  No Xposed installed / Xposed is not enabled for Shizuku ，not root

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:shizuku-v12.14.0.r914.e88de6a-release
- Mode: termux terminal
- Android version:Android 8.1.0
- Device: meizu 16th

**Logs:**
USB debugging has been enabled, and shizuku has been activated
i want use rish in termux but the terminal reports an error.

**Describe the bug:**

I want to use rish in termux. When I configure the rish files "PKG" and run"sh rish", the terminal reports an error.
When I run rish with the adb shell, it works

**Additional context:**
error:
java.lang.IllegalArgumentException: Calling application did not provide package name
        at android.os.Parcel.readException(Parcel.java:2016)
        at android.os.Parcel.readException(Parcel.java:1958)
        at android.app.IActivityManager$Stub$Proxy.broadcastIntent(IActivityManager.java:4819)
        at rikka.shizuku.shell.ShizukuShellLoader.a(Unknown Source:75)
        at rikka.shizuku.shell.ShizukuShellLoader.main(SourceFile:2)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)

**Comment by RikkaW** [comment]
"Calling application did not provide package name", this means PKG is not correctly set. Please send the content of your rish file.

**Comment by solakksk** [comment]
[rish.zip](https://github.com/RikkaApps/Shizuku/files/10330334/rish.zip)

**Comment by RikkaW** [comment]
Fails at this line https://github.com/RikkaApps/Shizuku/blob/c9ab79363eb75366edd8a9a406d02b3bff4fe50c/shell/src/main/java/rikka/shizuku/shell/ShizukuShellLoader.java#L65.

However, theoretically, using `am broadcast` in the `adb shell` should fail with the same error as well. Could you please try it?

**Comment by RikkaW** [comment]
Try this build https://github.com/RikkaApps/Shizuku/actions/runs/3910024837. rish needs to be exported again.
