### ISSUE TITLE
Shizuku services stopped right away when closing recent, although battery is unrestricted and ROM is CrDroid (AOSP)

### ISSUE THREAD

**Issue by bolabola6789** [RikkaApps/Shizuku#266]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 12.14.0
- Mode: both root and adb, su granted through kernelSU (root)
- Android version: 13, crDroid 9.1, Jan 2023 security patch 
- Device: Redmi K40S (munch)

**Logs:**
Recorded logcat when opening the app, starting the service and close app in recents tab 
[2023-01-30-21-11-39.txt](https://github.com/RikkaApps/Shizuku/files/10536606/2023-01-30-21-11-39.txt)

Related **full logcat**.

**Describe the bug:**

As title said, Shizuku services stopped immediately when closing the app in recents tab. I retried for many, many times, rebooting and it just wouldn't work.

**Additional context:**

There might be something wrong with the system(?) 
Shizuku does work when it was closed in recents tab but very rarely

**Comment by vvb2060** [comment]
Kernel su is a broken su implementation, please replace it with magisk or use wireless debugging.

**Comment by bolabola6789** [comment]
> Kernel su is a broken su implementation, please replace it with magisk or use wireless debugging.

I included in my issue that it happens in adb too...

**Comment by RikkaW** [comment]
```
01-30 21:11:44.295 D/Zygote  (  860): Forked child process 6108
01-30 21:11:44.298 I/ActivityManager( 1716): Start proc 6108:moe.shizuku.privileged.api/u0a293 for next-top-activity {moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity}
01-30 21:11:44.311 E/.privileged.api( 6108): Not starting debugger since process cannot load the jdwp agent.
01-30 21:11:44.321 D/CompatibilityChangeReporter( 6108): Compat change id reported: 171979766; UID 10293; state: ENABLED
01-30 21:11:44.340 V/GraphicsEnvironment( 6108): ANGLE Developer option for 'moe.shizuku.privileged.api' set to: 'default'
01-30 21:11:44.340 V/GraphicsEnvironment( 6108): ANGLE GameManagerService for moe.shizuku.privileged.api: false
01-30 21:11:44.340 V/GraphicsEnvironment( 6108): Neither updatable production driver nor prerelease driver is supported.
01-30 21:11:44.341 D/NetworkSecurityConfig( 6108): No Network Security Config specified, using platform default
01-30 21:11:44.341 D/NetworkSecurityConfig( 6108): No Network Security Config specified, using platform default
01-30 21:11:44.368 I/AppCompatDelegate( 6108): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
01-30 21:11:44.378 D/CompatibilityChangeReporter( 6108): Compat change id reported: 210923482; UID 10293; state: DISABLED
01-30 21:11:44.378 D/CompatibilityChangeReporter( 6108): Compat change id reported: 37756858; UID 10293; state: ENABLED
01-30 21:11:44.385 D/CompatibilityChangeReporter( 6108): Compat change id reported: 183155436; UID 10293; state: DISABLED
01-30 21:11:44.410 I/AdrenoGLES-0( 6108): QUALCOMM build                   : c263890aed, Ifb496a9c37
01-30 21:11:44.410 I/AdrenoGLES-0( 6108): Build Date                       : 06/27/22
01-30 21:11:44.410 I/AdrenoGLES-0( 6108): OpenGL ES Shader Compiler Version: EV031.35.01.12
01-30 21:11:44.410 I/AdrenoGLES-0( 6108): Local Branch                     : 
01-30 21:11:44.410 I/AdrenoGLES-0( 6108): Remote Branch                    : 
01-30 21:11:44.410 I/AdrenoGLES-0( 6108): Remote Branch                    : 
01-30 21:11:44.410 I/AdrenoGLES-0( 6108): Reconstruct Branch               : 
01-30 21:11:44.410 I/AdrenoGLES-0( 6108): Build Config                     : S P 10.0.7 AArch64
01-30 21:11:44.410 I/AdrenoGLES-0( 6108): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
01-30 21:11:44.412 I/AdrenoGLES-0( 6108): PFP: 0x016dd093, ME: 0x00000000
01-30 21:11:44.424 E/OpenGLRenderer( 6108): Unable to match the desired swap behavior.
01-30 21:11:44.427 I/Gralloc4( 6108): Adding additional valid usage bits: 0x546c08202000
01-30 21:11:44.477 W/Parcel  ( 6108): Expecting binder but got null!
01-30 21:11:45.603 I/AppCompatDelegate( 6108): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
01-30 21:11:45.608 D/CompatibilityChangeReporter( 6108): Compat change id reported: 171228096; UID 10293; state: ENABLED
01-30 21:11:45.623 E/OpenGLRenderer( 6108): Unable to match the desired swap behavior.
01-30 21:11:45.629 W/Parcel  ( 6108): Expecting binder but got null!
01-30 21:11:46.444 D/Service ( 6158): attachApplication: moe.shizuku.privileged.api 10293 6108
01-30 21:11:46.444 I/ShizukuApplication( 6108): attachApplication
01-30 21:11:49.484 E/OpenGLRenderer( 6108): Unable to match the desired swap behavior.
01-30 21:11:54.100 D/BinderSender( 6158): onForegroundActivitiesChanged: pid=6108, uid=10293, foregroundActivities=false
01-30 21:11:54.645 I/ActivityManager( 1716): Killing 6108:moe.shizuku.privileged.api/u0a293 (adj 905): remove task
01-30 21:11:54.671 I/Zygote  (  860): Process 6108 exited due to signal 9 (Killed)
01-30 21:11:54.674 D/BinderSender( 6158): onProcessDied: pid=6108, uid=10293
01-30 21:11:54.677 W/ActivityManager( 1716): setHasOverlayUi called on unknown pid: 6108
01-30 21:11:54.717 I/libprocessgroup( 1716): Successfully killed process cgroup uid 10293 pid 6108 in 7ms
01-30 21:11:54.732 I/ActivityManager( 1716): Process PhantomProcessRecord {5f61a0c 6140:6108:su/0} died
01-30 21:11:54.732 I/libprocessgroup( 1716): Successfully killed process cgroup uid 10293 pid 6108 in 0ms
01-30 21:11:54.733 I/ActivityManager( 1716): Process PhantomProcessRecord {700ef55 6158:6108:shizuku_server/0} died
```

(log filtered with "6108")

6108: Shizuku app
6140: "su" executable
6158: shizuku_server

Why su and shizuku_server is in app's cgroup? Is it a kernelSU issue? Why shizuku_server is recorded as a PhantomProcessRecord? Why ActivityManager can kill the "su" process "su" and "shizuku_server"? I believe I can assume this is a problem with kernel su.

Btw, Shizuku starter try to switch cgroup on start. But it is printed to app, not logcat. You can check if there are these texts shows on starting shizuku server.
https://github.com/RikkaApps/Shizuku/blob/41df19122cfb8135754dfce1ff77604437e6bcea/manager/src/main/jni/starter.cpp#L143
https://github.com/RikkaApps/Shizuku/blob/41df19122cfb8135754dfce1ff77604437e6bcea/manager/src/main/jni/starter.cpp#L148
https://github.com/RikkaApps/Shizuku/blob/41df19122cfb8135754dfce1ff77604437e6bcea/manager/src/main/jni/starter.cpp#L152
https://github.com/RikkaApps/Shizuku/blob/41df19122cfb8135754dfce1ff77604437e6bcea/manager/src/main/jni/starter.cpp#L158
https://github.com/RikkaApps/Shizuku/blob/41df19122cfb8135754dfce1ff77604437e6bcea/manager/src/main/jni/starter.cpp#L163

**Comment by RikkaW** [comment]
> > Kernel su is a broken su implementation, please replace it with magisk or use wireless debugging.
> 
> I included in my issue that it happens in adb too...

Upload the log of using adb.

**Comment by bolabola6789** [comment]
> > > Kernel su is a broken su implementation, please replace it with magisk or use wireless debugging.
> > 
> > 
> > I included in my issue that it happens in adb too...
> 
> Upload the log of using adb.

My phone is behaving weirdly, I only tried wireless debugging once and probably concluded too quickly. Both wired and wireless adb seems to be working reliably as of now, thanks.

**Comment by bolabola6789** [comment]
> > > Kernel su is a broken su implementation, please replace it with magisk or use wireless debugging.
> > 
> > 
> > I included in my issue that it happens in adb too...
> 
> Upload the log of using adb.

It happened with wireless adb (pair with code). It either didn't pair at all. or can start but got killed when I locked the screen. Log can't be provided since there are too many scenarios. 
The only method seems to work properly is wired adb (adb shell), I will stick with that.

**Comment by vvb2060** [comment]
404

**Comment by bolabola6789** [comment]
> 404

https://github.com/bolabola6789/files-upload/blob/main/2023-01-30-22-41-40%5B1%5D.txt

**Comment by vvb2060** [comment]
shizuku_server pid=21959
I didn't find it dead in the log.

**Comment by bolabola6789** [comment]
Very weird, I see shizuku being killed by opening the app and see it not
running. I think we just close the issue for now.

Vào 0:09, Th 3, 31 thg 1, 2023 南宫雪珊 ***@***.***> đã viết:

**Comment by RikkaW** [comment]
adbd restarts at 01-30 22:43:09.361 (Line 5732), any log from shizuku_server is earlier than this. Have you do anything that can trigger adbd restart, such as change USB config.

**Comment by bolabola6789** [comment]
> adbd restarts at 01-30 22:43:09.361 (Line 5732), any log from shizuku_server is earlier than this. Have you do anything that can trigger adbd restart, such as change USB config.

I locked the screen for 1 to 2 minutes. As changing USB configs, I don't recall myself doing that. 
Wired ADB works well, root works like after 10 attempts. Will just stick to wired adb for now.

**Comment by natsumerinchan** [comment]
Here's a temporary solution.Create a magisk module and put these codes in service.sh

```
#!/system/bin/sh
MODDIR=${0%/*}
SCRIPT_DIR=/storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh
while [ "$(getprop sys.boot_completed)" != "1" ]; do
  sleep 3
done

while [ ! -e "$SCRIPT_DIR" ]; do
  sleep 3
done

# Execute in global mount namespace
nsenter --mount=/proc/1/ns/mnt sh $SCRIPT_DIR 2>&1 | tee $MODDIR/start.log
```
[shizuku_daemon.zip](https://github.com/RikkaApps/Shizuku/files/10979876/shizuku_daemon.zip)

**Comment by bolabola6789** [comment]
Thanks for the reply. I have moved on from ksu though since the
compatibility is a mess, almost all modules didn't work. Switched to magisk
delta and used sui-zygisk to remove all the headache.

Vào 19:42, Th 4, 15 thg 3, 2023 セリカ・シルフィル ***@***.***> đã
viết:
