### ISSUE TITLE
Shizuku Server stops after disconnecting from pc

### ISSUE THREAD

**Issue by shimpact003** [RikkaApps/Shizuku#267]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 12.14.0.r914.e88de6a
- Mode: [adb]
- Android version: 13
- Device: Oppo Find X5 Pro

**Logs:**

Related: [logcat.log](https://github.com/RikkaApps/Shizuku/files/10539659/logcat.log)

**Describe the bug:**

I tried reenabling shizuku via a computer and was able to start the service via adb. As soon as I unplug my phone tough, the service stops running

**Additional context:**

I didn't had shelter installed the last time I started the service I think. While my phone is connected shizuku works completely normal.

**Comment by e-t-l** [comment]
I believe the "USB Debugging" setting needs to remain enabled while Shizuku is running. Can you Check whether disconnecting your phone makes USB Debugging turn off?

**Comment by RikkaW** [comment]
https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-shizuku-randomly-stops

Have you tried all steps listed here?

**Comment by shimpact003** [comment]
When in charge only mode, adb lists the device with no permissions.

**Comment by shimpact003** [comment]
Tried it on a windows machine again and it worked.
