### ISSUE TITLE
Interactive shell not starting

### ISSUE THREAD

**Issue by the-loan-wolf** [RikkaApps/Shizuku#268]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

**Information:**

- Shizuku version:13.1
- Mode: root
- Android version:12.0 lineageOS official

**Logs:**

request timeout. The connection between the current app (yarolegovich.materialterminal) and Shizuku app may be blocked by your system. Please disable all battery optimization features for both current app (yarolegovich.materialterminal) and Shizuku app

**Describe the bug:**

Even after disabling battery optimization for both app it still giving this error and not starting.

**Additional context:**

**Comment by RikkaW** [comment]
Please provide log :)

**Comment by the-loan-wolf** [comment]
And where i can find log created from shizuku? I only have terminal output which i provided in logs section
