### ISSUE TITLE
Programmatically execute adb shell commands?

### ISSUE THREAD

**Issue by raywdude** [RikkaApps/Shizuku#270]
Is there any API in Shizuku to be able to execute adb shell commands directly?

That way it'd be a lot simpler to do some tasks (such as reboot phone, or install APK from storage with shell permissions) rather than setting up reflection / stub classes for everything.

**Comment by wkbin** [comment]
> Is there any API in Shizuku to be able to execute adb shell commands directly?Shizuku 中是否有任何 API 可以直接执行 adb shell 命令？
> 
> That way it'd be a lot simpler to do some tasks (such as reboot phone, or install APK from storage with shell permissions) rather than setting up reflection / stub classes for everything.这样一来，执行一些任务（例如重新启动手机，或使用shell权限从存储中安装APK）会简单得多，而不是为所有内容设置反射/存根类。

是否找到了方法？
