### ISSUE TITLE
It is recommended to introduce shizuku with random package names 

### ISSUE THREAD

**Issue by iciclesselua** [RikkaApps/Shizuku#274]
Some applications can detect shizuku's package name and determine to disable software running. can you consider randomizing packaging and hiding features for shizuku, which may make shizuku more powerful, thank you

**Comment by RikkaW** [comment]
Such apps can simply switch to detect if USB debugging is enabled with only one line code. So it's pointless to spend a lot of effort to achieve random package name.

**Comment by On1yAMan** [comment]
> Such apps can simply switch to detect if USB debugging is enabled with only one line code. So it's pointless to spend a lot of effort to achieve random package name.

Well no, not really, since it's a lot easier for the user to turn debugging off for a minute than to uninstall and reinstall the app. An app that needs to be uninstalled and reinstalled constantly is most likely gonna stay uninstalled
