### ISSUE TITLE
调用了bindservice，doSomething里面的代码不更新

### ISSUE THREAD

**Issue by xingkong123600** [RikkaApps/Shizuku#275]
调用了bindservice，doSomething里面的代码更新了，但是bindservice返回的结果还是旧的结果，确定代码没问题。甚至重启手机doSomething的新代码也不执行，啥原因。也尝试过unbind，也无效。一直执行旧的代码。

**Comment by RikkaW** [comment]
![image](https://user-images.githubusercontent.com/12999176/222032182-88cd3d08-8ad4-4d08-8449-89ea23d56d94.png)
