### ISSUE TITLE
Banking app thinks rooted phone when Shizuku is installed 

### ISSUE THREAD

**Issue by Jonneri** [RikkaApps/Shizuku#276]
Please report bugs of Shizuku itself.

**Requirements:**

- [ x ] Shizuku version is up-to-date
- [ x ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ x ] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ x ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 12.14, 
- Mode: [adb, adb
- Android version: 13 (one ui 5.1)
- Device: (optional) : s21 ultra 5g

**Logs:**

Related **full logcat**.

**Describe the bug: after installation banking app vanquis is saying that the device is rooted and can't be used. Uninstalling Shizuku fixes the problem. 

This issue happens even if adb is not enabled, so this makes me think that the package name is blocked somehow. 

**Additional context:**

**Comment by RikkaW** [comment]
There is nothing we can do.

**Comment by negier** [comment]
那就需要你自己单独打一个包来用了，改下包名
