### ISSUE TITLE
Service stops when locking phone.

### ISSUE THREAD

**Issue by 2b2tplayer** [RikkaApps/Shizuku#277]
- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku
- 
**Information:**

- Shizuku version: 12.14.0.r914.e88de6a
- Mode: [adb]
- Android version: 12
- Device: Moto g31

Whenever I lock the phone, service stops. App is running unrestricted.

**Comment by RikkaW** [comment]
Have you tried all the steps listed here? https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-shizuku-randomly-stops

**Comment by 2b2tplayer** [comment]
yes I have

**Comment by amon-ra** [comment]
Same problem here. By wireless and cable

**Comment by WOLF33B** [comment]
same. with android 12. once phone on lock/sleep or even just display turn off before lock it will kick adb connection. 
it probably android limitation or "security reason". i just hope you guys can add a workaround to not run the server from adb wireless/usb. or just need once at setup maybe? like systemui tunner?

**Comment by amon-ra** [comment]
Tryed again and setup usb mode on charging only solved the problem. Thanks @RikkaW

**Comment by e-t-l** [comment]
> Tryed again and setup usb mode on charging only solved the problem.
@amon-ra Can you describe what setting you actually changed to fix this? Your description is unclear

**Comment by amon-ra** [comment]
![Screenshot_2023-06-08-19-21-16-17.jpg](https://github.com/RikkaApps/Shizuku/assets/1049676/1e32797c-293f-4acd-8dda-bc3cf8ca4521)

**Comment by CrossyAtom46** [comment]
> Tryed again and setup usb mode on charging only solved the problem. Thanks @RikkaW

Still works with A15. Thank you for sharing that.
