### ISSUE TITLE
shizuku 开启后无法工作

### ISSUE THREAD

**Issue by GabrielCarson** [RikkaApps/Shizuku#28]
手机型号blackberry priv
系统6.0
在用adb 启动shizuku server后(running version 32) 日志如下
`info: start.sh begin
info: starter begin
info: no old shizuku_server found.
info: dex path is /storage/emulated/0/Android/data/moe.shizuku.privileged.api/files/server-23-v32.dex
info: process forked, pid=5846
info: checking shizuku_server start...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: shizuku_server started.
--- crash start ---
[command] logcat -b crash -t '03-16 19:00:06.000' -d
--- crash end ---
--- shizuku start ---
[command] logcat -b main -t '03-16 19:00:06.000' -d -s ShizukuServer ShizukuManager
03-16 19:00:07.579  5847  5847 I ShizukuServer: uid: 2000
03-16 19:00:07.580  5847  5847 I ShizukuServer: api version: 23
03-16 19:00:07.580  5847  5847 I ShizukuServer: device: venice
03-16 19:00:07.580  5847  5847 I ShizukuServer: start version: 32 token: 717e5a8d-33b6-4939-a4b2-c8a736df2270
03-16 19:00:07.641  5847  5847 I ShizukuServer: send token to manager app in user 0
03-16 19:00:07.799  5900  5900 I ShizukuManager: token update: 717e5a8d-33b6-4939-a4b2-c8a736df2270
--- shizuku end ---
info: shizuku_starter exit with 0
`
使用my android tools 时显示 shizuku authorization failed
使用 blocker 会报错
n
![Screenshot_20190316-193050](https://user-images.githubusercontent.com/13148727/54474657-67daef00-4822-11e9-9d8d-3af856301d66.png)
小黑屋，icebox 也必须要adb后才能使用

**Comment by RikkaW** [comment]
从截图看，两个可能性
一种是像 MIUI 那样，adb 权限受限（如果是改什么都这样
另一种是 adb 本来就不能改全部的组件（如果只有改其中的一部分出现这样的情况

**Comment by GabrielCarson** [comment]
我刚测试了下，应该是都不可以，但是app ops 是可以使用的，请问icebox和my android tools 都无法得到 shizuku manager 的授权是什么原因呢，adb 权限受限会导致my android tools授权失败，或者icebox根本检测不到shizuku manager 么

**Comment by GabrielCarson** [comment]
my android tools 和 blocker 还是需要root的，非常感谢
