### ISSUE TITLE
Shizuku kills after screen off

### ISSUE THREAD

**Issue by SirenGlitch** [RikkaApps/Shizuku#293]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.4
- Mode: adb
- Android version: 11
- Device: OnePlus 6T(no root)

**Describe the bug:**

Whenever screen turns off, shizuku is killed, meaning I have to reactivate it.

**Additional context:**

Happens through computer, wireless debugging, and a termux trick to run it.

**Comment by RikkaW** [comment]
Have you tried all the steps listed here? https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-shizuku-randomly-stops

**Comment by SirenGlitch** [comment]
Thanks, this worked perfectly!

**Comment by chaoscreater** [comment]
Setting to charge only worked for me on Android 13 on my Lenovo Xiaoxin Pad 12.7 tablet. But why does it break when I set default USB to file transfer instead of charge only? Just wanting to understand what's causing the issue.

**Comment by SirenGlitch** [comment]
> Setting to charge only worked for me on Android 13 on my Lenovo Xiaoxin Pad 12.7 tablet. But why does it break when I set default USB to file transfer instead of charge only? Just wanting to understand what's causing the issue.

Wish I knew, probably something with how the server/Android USB service works
