### ISSUE TITLE
请问是否有exec-out的执行方法

### ISSUE THREAD

**Issue by 1965514404** [RikkaApps/Shizuku#295]
我想执行adb exec-out screencap -p >screenshotName.png
这个命令,请问再shuzuku上是否有操作方法

**Comment by RikkaW** [comment]
逐一再去把 adb 的其他功能再去实现一遍是不现实也无意义的。以你的例子，目的是取得截图并写入到文件，实现某种执行程序并将其输入输出重定向的功能显然是舍近求远。应考虑换用更直接的方法实现目标，例如（这只是一些思路，不一定对）：
- 查看“screencap ”内部是如何取得截图的，直接在自己的程序中使用，并自己实现写入到文件
- 其他取得截图的方式，例如参看 scrcpy
