### ISSUE TITLE
Can't start Shizuku with wireless debugging on Pixel 7 after latest security update

### ISSUE THREAD

**Issue by svistakk** [RikkaApps/Shizuku#300]
Please report bugs of Shizuku itself.

**Requirements:**

- [X] Shizuku version is up-to-date
- [X] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [X] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [X] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.3.0.r993.5392b9d
- Mode: [adb, root] - wireless debugging
- Android version: 13 with May 5 2023 security update
- Device: Pixel 7

**Logs:**

Related **full logcat**.

**Describe the bug:**

I'm trying to start Shizuku with wireless debugging. I can pair the app, but after successful pairing, when I tap "start", I get info about enabling wireless debugging. 

Works with adb wired connection. 

**Additional context:**

**Comment by svistakk** [comment]
Been there plus install/reinstall app, reboot Pixel etc. As you can see phone paired with Shizuku, but app can't start. 
![Screenshot_20230508-201441](https://user-images.githubusercontent.com/4323985/236900345-7a2362e6-df9a-48a9-860e-fb7b6e168c96.png)
![Screenshot_20230508-122116](https://user-images.githubusercontent.com/4323985/236900406-c0d1729c-ec18-42a2-8201-c19783fb2837.png)

**Comment by MohammedALShimmary** [comment]
I can confirm the same issue with Red Magic 8 Pro running Android 13 with Google Security Update March 1st 2023 ..

![Screenshot_2023-05-10-11-13-36-327](https://github.com/RikkaApps/Shizuku/assets/58645632/d2163d62-10fe-4d86-a625-9a84571aff5a)
![Screenshot_2023-05-10-11-14-34-336](https://github.com/RikkaApps/Shizuku/assets/58645632/dd1fffe9-1f81-4cc4-ba80-8bf4802f8b81)

**Comment by dnestico** [comment]
For me it starts on Pixel 7 Pro but always disconnects when I exit the app now, didn't do that before and worked just fine in the background. Have battery set to unrestricted and restarted my phone but didn't work.

**Comment by ir1descent** [comment]
Same issue here on a S23.

On another S23 it works though, which makes me think it's one of the later updates that broke it

**Comment by RikkaW** [comment]
Pixel 5, unrooted, the latest patch (TQ3A.230705.001, Jul 2023), works without problem. I don't think it's related to security update. But none of you provides logs, so I have no way to investigate it.

**Comment by RikkaW** [comment]
Close this issue as no logs are provided.
