### ISSUE TITLE
Shizuku stops running right after disconnecting with PC

### ISSUE THREAD

**Issue by PranavPurwar** [RikkaApps/Shizuku#304]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.3.0
- Mode: [adb]
- Android version: 9
- Device: Xiaomi Redmi Note 5 Pro

**Logs:**

Couldn't find any suitable logs

**Describe the bug:**

If I enable shizuku through adb and then disconnect the PC, Shizuku loses all privileges right at that moment.

**Additional context:**

I have already tried putting shizuku to battery optimization ignore list, and this might not even be related because it stops even while im on the app

**Comment by xXMrDarkFireXx** [comment]
Hello
I had the same problem as mentioned above, but once I use Shizuku in Amarok it worked, and it stayed on.
hopefully, it will work for you too.
