### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Meow-purr** [RikkaApps/Shizuku#307]
Please report bugs of Shizuku itself.

**Requirements:**

 Shizuku version is up-to-date
 Shizuku is downloaded from official channels (GitHub release or Google Play)
 Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
 (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: N/a
- Mode: n/a
- Android version: n/a
- Device: (optional)

**Describe the bug:**
what is the license (wondering for NeoApplications/Neo-Store#102 )

**Additional context:**
its on izzyondroid so it **should be apche licend**(per app details)

**Comment by IzzySoft** [comment]
Related comment most likely answering your question: https://github.com/RikkaApps/Shizuku/issues/69#issuecomment-727717512
