### ISSUE TITLE
shizuku_starter exit with 0

### ISSUE THREAD

**Issue by Beat-YT** [RikkaApps/Shizuku#312]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.2.1r958.5f9516b
- Mode: [adb, root] adb
- Android version: 12
- Device: (optional) Samsung S22+ US variant

**Logs:**

C:\Users\username>adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh
info: start.sh begin
info: attempt to copy starter from /storage/emulated/0/Android/data/moe.shizuku.privileged.api/starter to /data/local/tmp/shizuku_starter
info: exec /data/local/tmp/shizuku_starter
info: starter begin
info: killing old process...
info: killed 20315 (shizuku_server)
info: apk path is /data/app/~~Xgoe-Dds_kyu8p4XEBJbmw==/moe.shizuku.privileged.api-V2fMLo2UxEIF351Hky2SoA==/base.apk
info: starting server...
info: shizuku_starter exit with 0

Related **full logcat**.

**Describe the bug:**

when I try to start Shizuku, it simply closes itself.
It also affect adb over wifi as well as normal adb from a computer

**Additional context:**

**Comment by RikkaW** [comment]
Please provide the log of Shizuku startup process.

**Comment by Beat-YT** [comment]
where can I find logs of Shizuku startup process?
