### ISSUE TITLE
Feature request : change port number

### ISSUE THREAD

**Issue by islam2hamy** [RikkaApps/Shizuku#317]
Thank you for the app ,
can you please add the ability to change the Port , like this app

![image](https://github.com/RikkaApps/Shizuku/assets/7989030/3aeab6a5-bcbe-4e8c-9605-2c9d279b2baf)

Thank you

**Comment by RikkaW** [comment]
Shizuku **USE** adb (or root, but we assume Shizuku is started by adb here).
WADB **CONTROLL** the toggle of the old wireless adb, including the port. **WADB requires root, so it can do this.**

So why does Shizuku need to have a function that can change the port of the old wireless adb? Also, changing the port requires the restart of adbd, but adb **CANNOT** restart adbd [1]. Your request is impossible from the beginning.

[1] When you are using the adb executable from your computer, adb executable communicates with adbd. So you can use "adb tcpip" to change the port from your computer.

**Comment by islam2hamy** [comment]
got it,
thank you
