### ISSUE TITLE
[Q] Is Shizuku capable of changing colour filter?

### ISSUE THREAD

**Issue by 5ulo** [RikkaApps/Shizuku#319]
Sorry if this question is OT but I can't find any relevant info to this topic question. There are multiple options for rooted phones to change colour temperature (f.lux, cf.lumen) or my absolute top 'Color changer pro' which changes the display to full grayscale+red ideal for night.
The question is if Shizuku (obviously not Shizuku, but some app compatible with Shizuku) is capable to add the same functionality to non-rooted phones or is this specific to only rooted phones? "It's just a simple colour filter", right?

**Comment by shaggyskunk** [comment]
Depending on what device you have, ie Samsung has what you're looking for
built-in on many of their devices.
There's an app "blue light filter" on the Play Store that does not require
Root.
You could always just Google Search.

**Comment by RikkaW** [comment]
From my knowledge there are only two ways:
The first is to use overlay to superimpose another color (such as making the screen darker), this does not require root or adb, but it may not cover the status bar and navigation bar and some system apps that prohibit overlay. Using Shizuku only makes it possible to cover more things, completely changing the color is impossible.
The second is to use SurfaceFlinger's API to change ColorMatrix (this is used by the system's Night Light mode, boosted color mode, etc.). But unfortunately, adb has no permission to use this API.

**Comment by 5ulo** [comment]
@shaggyskunk samsung has the same overlay method as the non-root apps in the play store - that means it will put some semi-transparent red overlay which makes black color as vanished red. So this is a no-go as the display is totally unreadable. I was googling and reading a lot but no one mentioned this colour filter 'problem'. 

@RikkaW thanks for the explanation. Would be great to have this built in inside the Samsung UI or every android phone. iOS has that since iOS 10 (I think).

So Shizuku without root is a no-go.
