### ISSUE TITLE
Naive Terminal, Other

### ISSUE THREAD

**Issue by derrdevel** [RikkaApps/Shizuku#321]
An in app native terminal with local adb functions would be a hugely valuable addition to Shizuku.

 ![IMG_20230620_040828.png](https://github.com/RikkaApps/Shizuku/assets/101167814/081da44b-481c-4d7e-aa13-6497be03bf56)

currently.derrick@gmail.com

**Comment by RikkaW** [comment]
Shizuku already provides `rish` that allows you to have "adb shell" in any terminal app. Implementing a fully functional terminal is much more complex than you thought, it's far more than executing some commands and showing the result. It is obviously not a good idea to go to the trouble of re-implementing a terminal.
