### ISSUE TITLE
Add limit for 5 apps install (per Staging app install) or (Pending install app) in settings for installing app with Shizuku. in app when extensions are 250+ for install or update app is crashing when install or updating more than 50 apps (app exemple: Tachiyomi / Browse / extensions / update)

### ISSUE THREAD

**Issue by Character95** [RikkaApps/Shizuku#323]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
- Mode: [adb, root]
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**.

**Describe the bug:**

**Additional context:**

**Comment by RikkaW** [comment]
Shizuku itself does not have the function of installing apps. You should contact the app developer who uses Shizuku to install apps.
