### ISSUE TITLE
Redmi

### ISSUE THREAD

**Issue by panyt0615** [RikkaApps/Shizuku#324]
After clicking on the input pairing code in the taskbar, MIUI14 directly displays an error message that the pairing code is incorrect (before entering the pairing code).

**Comment by RikkaW** [comment]
https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-immediately-fail-after-tapping-enter-pairing-code

> Start via wireless debugging: immediately fail after tapping "Enter pairing code"
>
> MIUI (Xiaomi, POCO)
> Switch notification style to "Android" from "Notification" - "Notification shade" in system settings.
