### ISSUE TITLE
[ feature request ] accessibility service start

### ISSUE THREAD

**Issue by theotheroracle** [RikkaApps/Shizuku#328]
If the application could use the accessibility service to autostart wifi adb and launch the service on boot, this would be very nice

**Comment by RikkaW** [comment]
1. This usage is impossible to approved by Google Play
2. Every OEM has its own Android skin, it is impossible to adapt to all the systems
3. I personally extremely disgusted to use accessibility service to do such auto click things (First, it's not be designed to do this; we only care about event on some specific view, but the system needs to pass all the events to you app. It is such a waste.)
