### ISSUE TITLE
Add virtual joystick for fire/android tv

### ISSUE THREAD

**Issue by Hunter9888x** [RikkaApps/Shizuku#33]
Adding a virtual joystick
for android/fire tv support

Want a way to enable
virtual mouse or joystick
Integrated inside shizuku

App Cloner has this feature
https://appcloner.app
Under android tv & wear os options:
Joystick pointer
Control touch-only apps through a cross-hair pointer using your D-pad. Press the center key to trigger clicks, long-press to show / hide the cross-hair pointer.

**Comment by H4xX0r1337** [comment]
@Hunter9888x So you actually want an app which does that using Shizuku?

**Comment by Hunter9888x** [comment]
Yes want a alternative to
Mouse toggle for fire tv/android tv

**Comment by Hunter9888x** [comment]
Want a virtual mouse or joystick
Integrated in shizuku
