### ISSUE TITLE
DeviceVerificationManager's setDomainVerificationLinkHandlingAllowed does not work with ADB rights

### ISSUE THREAD

**Issue by 1fexd** [RikkaApps/Shizuku#330]
Hello, I wanted to disable the link handling of an app, which can be done via `adb shell pm set-app-links-allowed --user 0 --package {package-name} false`

Since I am kind of new to all of this, I dug around in the Android source and I think I found the issue, why this does not work with ADB Shizuku:

`DomainVerificationShell`, which handles the ADB shell commands, [is able to call into](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/pm/verify/domain/DomainVerificationShell.java;l=421) `setDomainVerificationLinkHandlingAllowedInternal` of [DomainVerificationService](https://cs.android.com/android/platform/superproject/main/+/refs/heads/main:frameworks/base/services/core/java/com/android/server/pm/verify/domain/DomainVerificationService.java;l=497), while `DomainVerificationManager`, which is accessible from apps, [only implements](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/content/pm/verify/domain/DomainVerificationManager.java;l=252) `setDomainVerificationLinkHandlingAllowed` (I suppose all of this is behavior is defined in `IDomainVerificationManagaer.aidl` ([here](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/android/content/pm/verify/domain/IDomainVerificationManager.aidl)), right?). This method has a permission check which rejects the ADB user as it does not have the required permission.

Do you know if this is intenional on Google's side? And is there any way to work around this, except for just running the ADB command in my app?

Thanks!

**Comment by RikkaW** [comment]
Sometimes this thing, commands have less permission check, does happen. There is nothing we can do, if only commands work, we have no choice but to use the commands, since AIDL APIs directly with adb is not what it was designed to. Google doesn't care about such usage. ¯\_(ツ)_/¯

**Comment by 1fexd** [comment]
Yeah, I already figured. Thanks anyway, using the commands directly now and it works very well!
