### ISSUE TITLE
Rish returns "Aborted" on Android 14

### ISSUE THREAD

**Issue by eliasacab** [RikkaApps/Shizuku#331]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.5.1.r1025.ebb2a30
- Mode: adb
- Android version: 14 beta 4.1
- Device: Pixel 7

**Logs:**

Related **full logcat**.

**Describe the bug:**

Rish used to work on Android 13 on Termux and Tasker. After updating to Android 14 beta 4.1, both apps now return "Aborted" when sh rish is run. Same setup as 13. I've tried several things, no luck. Thanks.

Happening to others too:
https://www.reddit.com/r/android_beta/comments/15fqc4c/rish_shizuku_broken_on_android_14/

**Comment by RikkaW** [comment]
Removing the write permission for `rish_shizuku.dex` will solve the problem. This also means rish cannot be exported to internal storage (/sdcard).

**Comment by eliasacab** [comment]
Ok! Does this mean that for the time being Rish will only work with root on Android 14?

**Comment by RikkaW** [comment]
Apps have permission to adjust permission of their private file (/data/data). So, root is not required. For terminal apps don't expose their folder to SAF like Termux, the only thing the user needs to do is copy rish files to terminal apps' private data folder.

I have added remove write permission automatically in this commit dceecf1d6c1568b6eaa5519e4dd8c3ae39cd632e.

**Comment by eliasacab** [comment]
Thanks! Tried with the new commit, but it wasn't able to remove write permission. Copying it to the data folder did it! Got Rish working on A14 now. Thank you.

**Comment by CyanChanges** [comment]
Cab you update post-install.sh to fix it in Sui?
@RikkaW

**Comment by Badraly1984** [comment]
في الخميس، ٤ يناير ٢٠٢٤, ٨:٢١ ص Cyan ***@***.***> كتب:
