### ISSUE TITLE
Shizuku/Termux not able to open Shell on One UI Beta 6

### ISSUE THREAD

**Issue by wr3cckl3ss1** [RikkaApps/Shizuku#335]
Please report bugs of Shizuku itself.

**Requirements:**

- [ x] Shizuku version is up-to-date
- [ x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [no root ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.5.1.r1025
- Mode: [adb, root]: adb
- Android version: 14, One UI 6 Beta
- Device: S23 Ultra

**Describe the bug:**

Not able to get shell, using Termux/Shizuku combination.

**Additional context:**

Not able to get shell using the combination of Shizuku and Termux. I get the error of Aborted. I've tried even putting rish and rish_shizuku.dex into Termux's bin and running but to no success. I will include screenshot for more context. 
![Screenshot_20230817_223814_Termux](https://github.com/RikkaApps/Shizuku/assets/97212092/aad123cf-cba2-45e2-ac12-ec86aa3fb37a)

**Comment by TheGamer1002** [comment]
+1, but I'm sporting a Google Pixel 6 Pro.

**Comment by AlphaKR93** [comment]
move rish to home dir (`~`)

**Comment by TheGamer1002** [comment]
That's the place it lives in for me.

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/issues/331

**Comment by hothanhloc68** [comment]
> Please report bugs of Shizuku itself.
> 
> **Requirements:**
> 
> - [ x] Shizuku version is up-to-date
> - [ x] Shizuku is downloaded from official channels (GitHub release or Google Play)
> - [ x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
> - [no root ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku
> 
> Change "[ ]" to "[x]" if it meets the requirements.
> 
> **Reports not meet the requirements will be immediately closed**.
> 
> **Information:**
> 
> - Shizuku version: 13.5.1.r1025
> - Mode: [adb, root]: adb
> - Android version: 14, One UI 6 Beta
> - Device: S23 Ultra
> 
> 
> **Describe the bug:**
> 
> Not able to get shell, using Termux/Shizuku combination.
> 
> **Additional context:**
> 
> Not able to get shell using the combination of Shizuku and Termux. I get the error of Aborted. I've tried even putting rish and rish_shizuku.dex into Termux's bin and running but to no success. I will include screenshot for more context. 
> ![Screenshot_20230817_223814_Termux](https://github.com/RikkaApps/Shizuku/assets/97212092/aad123cf-cba2-45e2-ac12-ec86aa3fb37a)
>
