### ISSUE TITLE
Shizuko Manager Tasker Task

### ISSUE THREAD

**Issue by Hunter9888x** [RikkaApps/Shizuku#34]
Start shizuku server with tasker task
Runs command:adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh

Useful for fire tv/android tv

Requires adb debugging enabled
No other device required than
fire tv supports it

Requires tasker app
https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm
Requires ADB Shell [Tasker] Plugin
https://play.google.com/store/apps/details?id=com.ADBPlugin

Shizuku Manager Tasker Task
Import in tasker app
Than start the task
https://mega.nz/#!KSxFCK4I!10jEs6Qy-RQMo9qxu4g37N5m-qSPLLvVH_4irTqxGu4

**Comment by thetoolz** [comment]
adb shell sh /data/user_de/0/moe.shizuku.privileged.api/start.sh

**Comment by king2web** [comment]
https://github.com/RikkaApps/Shizuku/issues/34#issuecomment-691714799

**Comment by spart0n654** [comment]
Could someone re-upload the file, I'd like to use this
