### ISSUE TITLE
请教一下app_process启动的进程中如何bindService

### ISSUE THREAD

**Issue by hytTony** [RikkaApps/Shizuku#341]
https://github.com/RikkaApps/Shizuku/issues/104，看到这里说可以，但我水平太差，没看懂，可不可以再详细点说说？

**Comment by RikkaW** [comment]
基本还是那个回复里说的。由于自己没有合法的 ApplicationThread，所以直接绑定任意应用的服务是不可能的。最多只可能实现你的 app_process 的进程去主动启动并获得你的应用进程的 binder。可以使用任何可以传递 binder 的方式，例如 startActivity、broadcastIntent、getContentProviderExternal 再 call。
再讲更多就会非常的冗长了（

**Comment by hytTony** [comment]
谢谢，我试试
