### ISSUE TITLE
找不到 import rikka.shizuku.Shizuku

### ISSUE THREAD

**Issue by TimeBeneficiary** [RikkaApps/Shizuku#345]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [ ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ ] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
- Mode: [adb, root]
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**.

**Describe the bug:**

**Additional context:**

**Comment by TimeBeneficiary** [comment]
我想编译这个开源项目
但是我没有看到 import rikka.shizuku.Shizuku 这个文件

**Comment by RikkaW** [comment]
git submodule update --init --recursive

**Comment by TimeBeneficiary** [comment]
> git submodule update --init --recursive

非常感谢
