### ISSUE TITLE
请教一下ContentProvider的call方法的参数问题

### ISSUE THREAD

**Issue by hytTony** [RikkaApps/Shizuku#346]
app_process进程中反射ContentProvider的call方法，发现参数个数不确定，OPPO Reno（Android 11)有6个参数，红米5（Android 8)有4个参数。
这个方法有统一的调用方法吗？
如果没有统一的调用方法，有各种机型的适配资料吗？（不知道是Android版本的问题，还是国内厂商定制后的问题）

**Comment by RikkaW** [comment]
本来非公开 API 就是会变的
另外这个 Shizuku 这里就有.jpg
