### ISSUE TITLE
MIUI 14 android 12 - Shizuku showing limitations

### ISSUE THREAD

**Issue by NOMiRaaN** [RikkaApps/Shizuku#348]
Hi...!
         I'm using poco x3 android 12 MIUI 14. I'm not able to understand what is the issue and how to resolve it. Please help me with that. 

![Screenshot_2023-09-16-06-45-00-530_moe shizuku privileged api]

![Screenshot_2023-09-16-06-45-08-887_com android settings](https://github.com/RikkaApps/Shizuku/assets/145173798/69760972-2eb6-484b-b49a-92548a8572a8)
![Screenshot_2023-09-16-06-45-23-378_com android settings](https://github.com/RikkaApps/Shizuku/assets/145173798/cac9bb88-d31c-4058-ae5d-e17c7633c222)

(https://github.com/RikkaApps/Shizuku/assets/145173798/31dc40ff-632b-463f-b6d2-576f99d6d031)
Please report bugs of Shizuku itself.

**Requirements:**

- [ ] Shizuku version is up-to-date
- [ ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ ] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
- Mode: [adb, root]
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**.

**Describe the bug:**

**Additional context:**

**Comment by NOMiRaaN** [comment]
![Uploading Screenshot_2023-09-16-06-45-00-530_moe.shizuku.privileged.api.jpg…]()

**Comment by NOMiRaaN** [comment]
![Screenshot_2023-09-16-06-45-00-530_moe shizuku privileged api](https://github.com/RikkaApps/Shizuku/assets/145173798/41b9d7d3-2004-43b5-a448-f84e91bc464f)

**Comment by RikkaW** [comment]
![image](https://github.com/RikkaApps/Shizuku/assets/12999176/c215f36e-72a0-4cc9-b1d7-1beb3547e69a)
->
![image](https://github.com/RikkaApps/Shizuku/assets/12999176/e26cbf80-d6af-492e-84d3-63eef3e3bbde)
![image](https://github.com/RikkaApps/Shizuku/assets/12999176/0a9b8454-fce6-495d-8e96-13c3d513c49b)

Why don't you read it? ¯\(ツ)/¯

**Comment by NOMiRaaN** [comment]
Thanks it's solved 😃😍 I'm new actually

**Comment by NOMiRaaN** [comment]
> ![image](https://user-images.githubusercontent.com/12999176/268424613-c215f36e-72a0-4cc9-b1d7-1beb3547e69a.png) -> ![image](https://user-images.githubusercontent.com/12999176/268424596-e26cbf80-d6af-492e-84d3-63eef3e3bbde.png) ![image](https://user-images.githubusercontent.com/12999176/268424666-0a9b8454-fce6-495d-8e96-13c3d513c49b.png)
> 
> Why don't you read it? ¯(ツ)/¯



Hmmmm... I'm using Hail application to stop application in background but again and again after one hour or two Hail require Shizuku permission again. I need to start all process again.  Is it possible that i could use Hail with only single ADB command. I mean just once as we use superuser 😃 but I don't wanna RooT my phone
