### ISSUE TITLE
ColorOS14 Android14无法启动

### ISSUE THREAD

**Issue by a2596519067** [RikkaApps/Shizuku#353]
Starting with wireless adb...

info: start.sh begin
info: attempt to copy starter from /storage/emulated/0/Android/data/moe.shizuku.privileged.api/starter to /data/local/tmp/shizuku_starter
info: exec /data/local/tmp/shizuku_starter
info: starter begin
info: killing old process...
info: apk path is /data/app/~~GFcuM9U-6fYx37flmBp8VA==/moe.shizuku.privileged.api-s0outPv_57omi1absmlccw==/base.apk
info: starting server...
info: shizuku_starter exit with 0

Waiting for service...

一直显示Waiting for service...

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/actions/runs/6256051186 最新的 应该是 好的（

**Comment by MLSci** [comment]
Almost the same issue on OxygenOS 14.
90% of the time gets stuck at "Waiting for service..." Only works occasionally
