### ISSUE TITLE
Unable to input the pairing code

### ISSUE THREAD

**Issue by guberm** [RikkaApps/Shizuku#358]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.5.2.r1028.2bbf671
- Mode: [adb]
- Android version: Android 14 QPR1 Beta
- Device: Pixel 7 Pro

**Video**

https://youtube.com/shorts/vgtyU8U-oIU?si=FGJ3bitxy2Mp_MgE

**Comment by hothanhloc68** [comment]
> Please report bugs of Shizuku itself.
> 
> **Requirements:**
> 
> - [x] Shizuku version is up-to-date
> - [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
> - [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
> - [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku
> 
> Change "[ ]" to "[x]" if it meets the requirements.
> 
> **Reports not meet the requirements will be immediately closed**.
> 
> **Information:**
> 
> - Shizuku version: 13.5.2.r1028.2bbf671
> - Mode: [adb]
> - Android version: Android 14 QPR1 Beta
> - Device: Pixel 7 Pro
> 
> **Video**
> 
> https://youtube.com/shorts/vgtyU8U-oIU?si=FGJ3bitxy2Mp_MgE

**Comment by kaoneko** [comment]
@guberm How did you solve it?

I had the same problem, the Shizuku notification where you have to type the pairing code disappearing upon touching the virtual keyboard. For anyone looking for a workaround: I was able to "type" the code from an adb shell on my laptop with `input text 123456`
