### ISSUE TITLE
三星 S9 已启动的服务会自动关闭

### ISSUE THREAD

**Issue by AlynxZhou** [RikkaApps/Shizuku#36]
谷歌搜了一下没找到答案，我用的是 Android Pie，三星默认连接电脑是 MTP 模式，直接输入命令可以开启，但大概过两天两夜再打开就是没有运行，手机没重启，app 是 Play 上的最新版本。

**Comment by RikkaW** [comment]
然而并没有好办法（

**Comment by AlynxZhou** [comment]
不要用USB ADB，先改成tcpip模式再启动脚本就会好很多，然后尽量不要用USB线连电脑，每次连电脑就关了

**Comment by AlynxZhou** [comment]
既然没啥好办法我先关了，反正要是有人有这个问题就tcpip连adb启动吧……
