### ISSUE TITLE
WIRELESS DEBUGGING NOT  WORKING 

### ISSUE THREAD

**Issue by KashurUser** [RikkaApps/Shizuku#365]
Please report bugs of Shizuku itself.

**Requirements:**

- [ ] Shizuku version is up-to-date
- [ ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ ] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
- Mode: [adb, root]
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**.

**Describe the bug:**

**Additional context:**

When  i turn developer option on in my  Samsung m31 android 12  
 Then click on wireless debugging   it shows that please connect to wifi network 
Why not showing about shizuku app

**Comment by Releece** [comment]
You have to have Wi-Fi enabled and connected to a network, else wireless debugging won't turn on. So it needs to be enabled even if you just want to use Shizuku.

Also please fill in the bug report properly instead of skipping the entire thing...

This can be closed? 🔒
