### ISSUE TITLE
Shizuku stops when connecting to PC in File Transfer mode

### ISSUE THREAD

**Issue by muchuelo** [RikkaApps/Shizuku#366]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.5.2 r1028
- Mode: adb
- Android version: 9
- Device: Huawei P10

**Describe the bug:**

I start Shizuku using adb on a laptop via USB cable, connected in Charge Mode. Starts every time and I've jumped through all the hoops you have to jump through to make sure EMUI does not kill the process. 

I emphasize - Shizuku runs forever (except after a reboot, of course) and NEVER gets killed by EMUI or any other Huawei nonsense (like 'PowerGenie' which I've got permanently disabled).

BUT - here's the problem

When I connect to my laptop via USB cable in File Transfer mode (which I sometimes do multiple times a day) Shizuku stops instantly. 

So after transfering my files, I have to disconnect, then reconnect in Charge mode and run the adb start command again. It's getting really tedious. (My phone is not rooted, obviously, and is actually impossible to root - I've tried every rooting method known to man with no success).

I can understand the need to connect in Charge mode to use adb, but I CAN'T understand why simply connecting in File Transfer mode stops Shizuku.

Is this expected behaviour (and if so, why?) or is it a bug? 
Or can someone enlighten me as to a solution?

**Additional context:**
If you're wondering how I know "Shizuku runs forever" (until I connect to PC in File Transfer mode) it's because there have been periods of several days when I **haven't** connected in File Transfer mode and Shizuku never stopped running.

**Comment by RikkaW** [comment]
"in File Transfer mode" this means adb usage mode change, all processes started by adb, including Shizuku's server process, are killed. So this is intended behavior, and there is no solution.
