### ISSUE TITLE
After removing Shizuku, Google Pay won't work

### ISSUE THREAD

**Issue by AmitGolden** [RikkaApps/Shizuku#370]
Just recently discovered Shikuzu, installed it, fiddled with it for a bit, then removed it.  
BUT when I got to pay with Google Pay it just wouldn't let me.

Tried deleting all of Google Play Services data, rebooting, trying to reverse the Shikuzu start script, but to no success.  
Also checked my phone for SafetyNet and root, and it was not rooted and SafetyNet Passed.

What can I do?

**Comment by biggestsonicfan** [comment]
@AmitGolden Were you able to resolve this?

**Comment by AmitGolden** [comment]
Yeah, it turned out unrelated
