### ISSUE TITLE
Wireless debugging broken

### ISSUE THREAD

**Issue by dtaluthge** [RikkaApps/Shizuku#378]
Please report bugs of Shizuku itself.

**Requirements:**

- [x ] Shizuku version is up-to-date
- [ x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
- Mode: adb
- Android version: 14 beta AP11.231020.013.A1
- Device: pixel 6 pro

**Logs:**

Related **full logcat**.

**Describe the bug:**
When trying to grant permission via application list either all wireless debugging permission gets removed from system or app crashes. 

**Additional context:**
This started happening from latest beta build onwards.

**Comment by RikkaW** [comment]
13.5.3
