### ISSUE TITLE
App crash on authorization

### ISSUE THREAD

**Issue by trwy7** [RikkaApps/Shizuku#381]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.5.2 (from android settings)
- Mode: adb
- Android version: 14 beta
- Device: Pixel 6

**Logs:**

Related **full logcat**.

**Describe the bug:**

When attempting to grant an app permission to use Shizuku, Shizuku crashes and I need to reconnect ADB

**Additional context:**

**Comment by Jankie06** [comment]
same issue here on pixel 6

**Comment by KieronQuinn** [comment]
Use the latest action build: https://github.com/RikkaApps/Shizuku/actions/runs/6986573177

**Comment by trwy7** [comment]
It works now, thank you
