### ISSUE TITLE
Bug with Android 14 on Pixel 6a

### ISSUE THREAD

**Issue by FFNUser** [RikkaApps/Shizuku#382]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [ ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.5.2.r1028.2bbf671
- Mode: [adb, root] adb wireless, and PC adb
- Android version: 14
- Device: (optional) Pixel 6a

**Logs:**none

Related **full logcat**.

**Describe the bug:**
After enabling Shizuku, it turn off when I allowing any app access to Shizuku, if I don't do that, it stay enabled

https://github.com/RikkaApps/Shizuku/assets/151765508/e7175aa2-3c6d-45de-a58f-3ea0d4ed6165

**Additional context:**

**Comment by ChamakaKumudesh** [comment]
same happened to me in pixel 8 pro

**Comment by vfishv** [comment]
@RikkaW 发个新版本修复下bug呀

**Comment by trwy7** [comment]
Same here #381

**Comment by ChamakaKumudesh** [comment]
> same happened to me in pixel 8 pro

It looks like this issue happen only in pixel QPR beta. I opt out from beta and now in stable Shizuku works without issue.

**Comment by KieronQuinn** [comment]
This was fixed in #373 but no release has been made with the fix. I have an unofficial build linked in https://github.com/KieronQuinn/Smartspacer/issues/52

**Comment by vfishv** [comment]
https://github.com/RikkaApps/Shizuku/releases

here is v13.5.3
