### ISSUE TITLE
Shizuku not running, options not showing up. (URGENT)

### ISSUE THREAD

**Issue by KeiranGamingTV** [RikkaApps/Shizuku#393]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.53.r1036.fff3f87
- Mode: I think adb
- Android version: 13
- Device: Samsung Galaxy S20 FE 5G

**Logs:**
Don't know how to access logs.

**Describe the bug:**
No options to run Shizuku **at all** are showing up. _Even after uninstalling, reinstalling and force stopping._

**Additional context:**
![Screenshot_20231214_065916_Shizuku](https://github.com/RikkaApps/Shizuku/assets/119417615/05d56096-6cbe-48d9-af6a-65837a9d0a06)

https://github.com/RikkaApps/Shizuku/assets/119417615/e59196f5-7ddf-4a5a-8885-5903c0274d50

**Comment by RikkaW** [comment]
Is Shizuku installed in non-primary user (work profile, Samsung safe folder, etc.)?

**Comment by RikkaW** [comment]
Yes, it needs to be installed in the primary user.

Why? Simplified how Shizuku works:
- Shizuku extracts some files of Shizuku server
- Start the server with adb, so that there is a "server" with adb permissions
- App can use adb permission through that "server"

Adb has no access to files in non-primary user (/storage/emulated/xxx) and Shizuku app installed in non-primary user can only write files to there (without extra user actions). So, ¯\_(ツ)_/¯.

**Comment by KeiranGamingTV** [comment]
> Yes, it needs to be installed in the primary user.
> 
> Why? Simplified how Shizuku works:
> 
> * Shizuku extracts some files of Shizuku server
> * Start the server with adb, so that there is a "server" with adb permissions
> * App can use adb permission through that "server"
> 
> Adb has no access to files in non-primary user (/storage/emulated/xxx) and Shizuku app installed in non-primary user can only write files to there (without extra user actions). So, ¯_(ツ)_/¯.

Thank you!

**Comment by itsame-luigi** [comment]
I take it there's no chance of this working in the future?
