### ISSUE TITLE
Integration of dhizuku 

### ISSUE THREAD

**Issue by swjpilot** [RikkaApps/Shizuku#399]
Is it possible to integrate dhizuku API to gain device owner permissions as well?
https://github.com/iamr0s/Dhizuku
This could be awesomely powerful for non rooted phones!

**Comment by RikkaW** [comment]
Device owner permissions are so limited that they cannot fit the requirement for most apps that use Shizuku. The permission is only enough for freezer apps if I'm not wrong.

**Comment by swjpilot** [comment]
Ahhh ok thanks

**Comment by swjpilot** [comment]
You can do all of this with device owner too
https://developer.android.com/reference/android/app/admin/DevicePolicyManager
