### ISSUE TITLE
执行start.sh 后 出现提示Permission denied

### ISSUE THREAD

**Issue by yyc13145920** [RikkaApps/Shizuku#40]
设备 ： 小米 MIX2S

系统 ： MIUI 10 9.7.11 开发版 安卓版本 9 安全补丁程序级别 ：2019-06-1

电脑上的 ADB 版本：Android Debug Bridge version 1.0.41 Version 29.0.1-5644136

运行 Shizuku  启动命令时，终端的输出:
`PS C:\Users\NamelessMidNight> adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh`

`info: start.sh begin
chcon: '/data/local/tmp/shizuku_starter' to u:object_r:shell_data_file:s0: Permission denied
fatal: can't access null, please open Shizuku Manager and try again.
info: shizuku_starter exit with non-zero value 1`

请问是不是因为小米对系统的自定义将部分机制破坏了 所以没用办法使用 也做不到修复？先谢谢了

**Comment by RikkaW** [comment]
先发一下 `/sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh` 的内容吧（

**Comment by yyc13145920** [comment]
不好意思最近有点忙 忘了回复

start.sh里面的内容是：

`#!/system/bin/sh

STARTER_PATH="/data/app/moe.shizuku.privileged.api-HJfYrYIER9yWa34Db4b_cw==/lib/arm64/libshizuku.so"
STARTER_PARAM="--path-legacy=null --path=null --token=ca3bf2ab-2fe0-4e04-92a5-25c3119f2381"
LIBRARY_PATH="/data/app/moe.shizuku.privileged.api-HJfYrYIER9yWa34Db4b_cw==/lib/arm64/libhelper.so"

echo "info: start.sh begin"

if [[ -f "$STARTER_PATH" ]]; then
    rm -f /data/local/tmp/shizuku_starter
    cp "$STARTER_PATH" /data/local/tmp/shizuku_starter
    chmod 700 /data/local/tmp/shizuku_starter
    chown 2000 /data/local/tmp/shizuku_starter
    chgrp 2000 /data/local/tmp/shizuku_starter
    chcon u:object_r:shell_data_file:s0 /data/local/tmp/shizuku_starter

    #mkdir -p /data/local/tmp/shizuku
    #chmod 700 /data/local/tmp/shizuku
    #chown 2000 /data/local/tmp/shizuku
    #chgrp 2000 /data/local/tmp/shizuku
    #chcon u:object_r:shell_data_file:s0 /data/local/tmp/shizuku_starter

    #rm -f /data/local/tmp/shizuku/libhelper.so
    #cp "$LIBRARY_PATH" /data/local/tmp/shizuku/libhelper.so
    #chmod 700 /data/local/tmp/shizuku/libhelper.so
    #chown 2000 /data/local/tmp/shizuku/libhelper.so
    #chgrp 2000 /data/local/tmp/shizuku/libhelper.so

    export PATH=/data/local/tmp:/system/bin:$PATH
    shizuku_starter ${STARTER_PARAM} $1
    result=$?
    if [[ ${result} -ne 0 ]]; then
        echo "info: shizuku_starter exit with non-zero value $result"
    else
        echo "info: shizuku_starter exit with 0"
    fi
else
    echo "Starter file not exist, please open Shizuku Manager and try again."
fi
`
然后 /sdcard/Android/data/moe.shizuku.privileged.api/files 里面有如下文件 
[https://imgur.com/6K9zMgZ](url)
`polaris :/sdcard/Android/data/moe.shizuku.privileged.api/files $ ls
oat	server-27-v30.dex server-27-v32.dex	server-v4.dex start.sh
server-26-v30.dex server-27-v31.dex server-legacy-v32-api27.dex server-v5.dex`

**Comment by RikkaW** [comment]
看起来是“不可能出现的情况”

试试把 `/sdcard/Android/data/moe.shizuku.privileged.api/files` 清空再 force stop 一下 Shizuku 再按之前说的做一次吧（

**Comment by yyc13145920** [comment]
大佬你好 我使用 rm -rf * 清空了文件夹里的所有内容并强制停止了Shizuku后再次启动就可以了 就成功了 没有报错。。。。 不知道为什么 是因为以前多了一些东西吗？ 这是清空之后 Shizuku 自动生成的文件

	polaris:/sdcard/Android/data/moe.shizuku.privileged.api/files $ ls
	server-legacy-v32-api27.dex server-v5.dex start.sh

因为成功启动 Shizuku 的输出比以往要长很多 所以在下面贴出
```
	 /sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh                                               <
	info: start.sh begin
	chcon: '/data/local/tmp/shizuku_starter' to u:object_r:shell_data_file:s0: Permission denied
	info: source dex path is /storage/emulated/0/Android/data/moe.shizuku.privileged.api/files/server-v5.dex
	info: source legacy dex path is /storage/emulated/0/Android/data/moe.shizuku.privileged.api/files/server-legacy-v32-api27.dex
	info: dex path is /data/local/tmp/shizuku/server-v5.dex
	info: legacy dex path is /data/local/tmp/shizuku/server-legacy-v32-api27.dex
	info: starter begin
	info: killing old process...
	info: starting server v3...
	info: process forked, pid=30861
	info: checking shizuku_server start...
	info: checking shizuku_server stability...
	info: checking shizuku_server stability...
	info: checking shizuku_server stability...
	info: shizuku_server started.
	info: starting server v2 (legacy)...
	info: process forked, pid=31025
	info: checking shizuku_server_legacy start...
	info: checking shizuku_server_legacy stability...
	info: checking shizuku_server_legacy stability...
	info: checking shizuku_server_legacy stability...
	info: shizuku_server_legacy started.
	--- crash start ---
	[command] logcat -b crash -t '07-22 23:10:50.000' -d
	--- crash end ---
	--- shizuku start ---
	[command] logcat -b main -t '07-22 23:10:50.000' -d -s ShizukuServer ShizukuServerV3 ShizukuManager
	07-22 23:10:51.527 30862 30862 I ShizukuServerV3: disabled hidden api blacklist
	07-22 23:10:51.527 30862 30862 I ShizukuServerV3: server v3
	07-22 23:10:51.527 30862 30862 I ShizukuServerV3: using token from arg
	07-22 23:10:51.533 29838 29863 I ShizukuManager: onBinderReceived
	07-22 23:10:51.536 30862 30862 I ShizukuServerV3: send binder to user app moe.shizuku.privileged.api in user 0
	07-22 23:10:51.537 30862 30892 D ShizukuServerV3: transact: uid=10285, descriptor=android.content.pm.IPackageManager, code=51
	07-22 23:10:51.553 30862 30862 I ShizukuServerV3: send binder to user app moe.shizuku.privileged.api in user 999        07-22 23:10:51.626 30862 30892 D ShizukuServerV3: transact: uid=10285, descriptor=android.content.pm.IPackageManager, code=19
	07-22 23:10:51.627 30862 30892 D ShizukuServerV3: transact: uid=10285, descriptor=android.content.pm.IPackageManager, code=19
	07-22 23:10:51.698 30862 30893 D ShizukuServerV3: onUidActive: uid=10286
	07-22 23:10:51.699 30862 30893 D ShizukuServerV3: onActive: uid=10286, packages=[rikka.appops]
	07-22 23:10:51.794 30862 30862 I ShizukuServerV3: send binder to user app rikka.appops in user 0
	07-22 23:10:51.795 30862 30893 I ShizukuServerV3: send binder to user app rikka.appops in user 0
	07-22 23:10:51.858 30862 30893 D ShizukuServerV3: onUidActive: uid=10195
	07-22 23:10:51.858 30862 30893 D ShizukuServerV3: onActive: uid=10195, packages=[com.catchingnow.icebox]
	07-22 23:10:52.154 30862 30893 I ShizukuServerV3: send binder to user app com.catchingnow.icebox in user 0
	07-22 23:10:52.155 30862 30862 I ShizukuServerV3: send binder to user app com.catchingnow.icebox in user 0
	07-22 23:10:53.214 31026 31026 I ShizukuServer: using token from arg
	07-22 23:10:53.253 31026 31026 I ShizukuServer: disabled hidden api blacklist
	07-22 23:10:53.306 31026 31026 I ShizukuServer: uid: 2000
	07-22 23:10:53.307 31026 31026 I ShizukuServer: api version: 28
	07-22 23:10:53.307 31026 31026 I ShizukuServer: device: polaris
	07-22 23:10:53.307 31026 31026 I ShizukuServer: start version: 32 token: 1379b737-f803-4fd4-82f5-d0a14932be54
	07-22 23:10:53.319 31026 31026 I ShizukuServer: send token to manager app in user 0
	07-22 23:10:53.320 31026 31026 I ShizukuServer: send token to manager app in user 999
	07-22 23:10:53.349 29838 29838 I ShizukuManager: token update: 1379b737-f803-4fd4-82f5-d0a14932be54
	07-22 23:10:53.350 30862 30893 D ShizukuServerV3: transact: uid=10285, descriptor=android.content.pm.IPackageManager, code=51
	07-22 23:10:53.406 30862 30893 D ShizukuServerV3: transact: uid=10285, descriptor=android.content.pm.IPackageManager, code=19
	07-22 23:10:53.407 30862 30893 D ShizukuServerV3: transact: uid=10285, descriptor=android.content.pm.IPackageManager, code=19
	07-22 23:10:54.663 30862 30893 D ShizukuServerV3: onProcessDied: pid=28636, uid=10027
	--- shizuku end ---
	info: shizuku_starter exit with 0
```

**Comment by RikkaW** [comment]
只想到一种可能的原因（已经试着修了）

**Comment by zuihaodexiaohei** [comment]
大佬 最新版给小天才用会无响应 11.3.1版没法启用 info: start.sh begin
info: attempt to copy starter from /storage/emulated/0/Android/data/moe.shizuku.privileged.api/starter to /data/local/tmp/shizuku_starter
info: exec /data/local/tmp/shizuku_starter
info: starter begin
info: killing old process...
fatal: can't kill 3369, please try to stop existing Shizuku from app first.
info: shizuku_starter exit with non-zero value 9
