### ISSUE TITLE
[Question] How Shizuku know my app's content provider author?

### ISSUE THREAD

**Issue by laiqun** [RikkaApps/Shizuku#410]
Hi Shizuku Team:

"When an app starts, Shizuku sends the binder to the app via ContentProvider. So the user app needs to add the provider, moe.shizuku.api.ShizukuBinderReceiveProvider".

I check the Shizuku API demo code, the authorities have changed to: 
```xml
        <provider
            android:name="rikka.shizuku.ShizukuProvider"
            android:authorities="${applicationId}.shizuku"  <!-- this line -->
            android:enabled="true"
            android:exported="true"
            android:multiprocess="false"
            android:permission="android.permission.INTERACT_ACROSS_USERS_FULL" />
```
It's not a hardcode string. 
So, How Shizuku know my app started and get content provider authorities?

Thanks

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/blob/1fc3a2d348f1d8941e0c04dfe3ca13a65525a4cb/server/src/main/java/rikka/shizuku/server/ShizukuService.java#L512

It is "hardcoded". Find a content provider is through "authorities" (name) only.

**Comment by laiqun** [comment]
Thanks for your quick help.
Another question, how Shizuku to know my app have started?

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/blob/1fc3a2d348f1d8941e0c04dfe3ca13a65525a4cb/server/src/main/java/rikka/shizuku/server/BinderSender.java
