### ISSUE TITLE
/data directory is not touchable says "permission denied"

### ISSUE THREAD

**Issue by jaffar02** [RikkaApps/Shizuku#413]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: v13.5.3.r1036.fff3f87
- Mode: [adb]
- Android version: 12 (API 32)
- Device: (optional)

With rish in termux still can't access /data directory and says "Permission Denied". I tried Mt manager and Fv Filexplorer too but they also can't touch anything in /data directory even though permission is allowed in shizuku. 

Screenshots:
![image_2024-02-05_150107969](https://github.com/RikkaApps/Shizuku/assets/87228345/adac8bf7-1591-4ae3-bcbe-532e2dd3b08d)

![image_2024-02-05_150129461](https://github.com/RikkaApps/Shizuku/assets/87228345/d726d49a-83b2-4904-90e2-222e367580a4)

![image_2024-02-05_150142333](https://github.com/RikkaApps/Shizuku/assets/87228345/6b3efc7f-0154-4990-8e09-4631a3c54f63)

**Comment by jaffar02** [comment]
Ohh so any fix to list /data dir with shizuku?

**Comment by muuneneko** [comment]
> Ohh so any fix to list /data dir with shizuku?

just nvm about
if you want /data access - root your device
