### ISSUE TITLE
Please add adbshell local execution function/请添加adb shell 命令执行模块吧。

### ISSUE THREAD

**Issue by dylanleesky** [RikkaApps/Shizuku#414]
Add the "adb shell command executes locally" function
I couldn't find a good execution tool.

请添加“adb shell 本地执行”的功能，
找不到好用的执行工具。

**Comment by haruue** [comment]
如果你是普通 Shizuku 用户， 请安装 Termux， 然后在启动 Shizuku 服务后选择「在终端应用中使用 Shizuku」， 按照提示的步骤将 rish 安装到 Termux 中， 就可以在 Termux 里通过 rish 访问 adb shell 了。

如果你是利用 Shizuku 开发其他程序的开发者， 那么这个需求不会受到支持。
