### ISSUE TITLE
Cookie Run Kingdom Detecting Shizuku As Malicious

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [RikkaApps/Shizuku#416]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.5.3
- Mode: adb
- Android version: 13
- Device: TECNO POVA 5 (TECNO LH7n)
- Root: Not rooted

**Logs:**

Related **full logcat**.

**Describe the bug:**

Cookie Run Kingdom a.k.a "Appsealing" is detecting Shizuku as malicious tool. And i only use shizuku for accessing android/data folder using zarchiver. not for cheating.

**Additional context:**

![Screenshot_20240119-092754_1](https://github.com/RikkaApps/Shizuku/assets/78845241/28c53baa-ae78-4248-88f6-7c33665cd7a1)

Request:
Please add Spoofing Package Name might be help to hide detection

**Comment by shaggyskunk** [comment]
lol

**Comment by RikkaW** [comment]
Nothing we can do x_x

**Comment by Maritoguionyo** [comment]
Maybe opening it from another user if your rom supports it without having it "installed" on that user

**Comment by RainbowShatter** [comment]
well I don't know
