### ISSUE TITLE
START after BOOT without ROOT

### ISSUE THREAD

**Issue by hisbalah** [RikkaApps/Shizuku#438]
when you solve this, to be able to start it  automatically after reboot android, then it make sense. or just allow to automate to run in automatically, for example to just run  sh (bla bla bla) start.sh  command in termux programatically without root. than it will make sense, like this is only half of work, but, thank you anyway, Great job.  Let us all know, when is it possible.

**Comment by pixincreate** [comment]
I had been working on this for a while and I don't think it is possible to auto-start without root given that you cannot pair in background (might be possible which I'm currently is unaware of, open for discussion to learn about that).

I'm able to turn on ADB over WiFI, but cannot connect to it and execute start process unless paired (it is the only way if not SSL Library error will be thrown) which completely defeats the purpose.

And yes, you cannot execute `sh` without actually setting up ADB from within app.
