### ISSUE TITLE
Android 14 QPR3 beta2 No interface method grantRuntimePermission

### ISSUE THREAD

**Issue by vfishv** [RikkaApps/Shizuku#441]
java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)

**Comment by RikkaW** [comment]
Should already be solved in the QPR2 times. Are you on an older version of Shizuku (the latest version is 13.5.3)?

**Comment by vfishv** [comment]
> Should already be solved in the QPR2 times. Are you on an older version of Shizuku (the latest version is 13.5.3)?

Android 14 QPR3  Pixel 6 Pro

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/actions/runs/8221375079 Try this build 🤔

**Comment by vfishv** [comment]
> https://github.com/RikkaApps/Shizuku/actions/runs/8221375079 Try this build 🤔

It works，Thank you！

**Comment by vfishv** [comment]
13.5.4 fixed this
