### ISSUE TITLE
MI 9 Android Q 上的关闭 Shizuku 授权闪退问题。

### ISSUE THREAD

**Issue by zhaobozhen** [RikkaApps/Shizuku#45]
你好，最近着手开发一个应用引入了 Shizuku。引入后试着关闭 Shizuku Manager (3.4.5) 中的授权，程序会直接闪退。尝试关闭App Ops，冰箱也有同样问题。系统版本MIUI 10 9.8.22 Android Q。崩溃日志如下。

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lbe.security.miui/com.android.packageinstaller.permission.ui.GrantPermissionsActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x7f100026
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7520)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f100026
 at android.content.res.Resources.getText(Resources.java:379)
 at android.content.res.MiuiResources.getText(MiuiResources.java:97)
 at android.widget.TextView.setText(TextView.java:6376)
 at com.android.packageinstaller.permission.ui.GrantPermissionsDefaultViewHandler.updateDescription(Unknown Source:61)
 at com.android.packageinstaller.permission.ui.GrantPermissionsDefaultViewHandler.updateAll(Unknown Source:0)
 at com.android.packageinstaller.permission.ui.GrantPermissionsDefaultViewHandler.updateUi(Unknown Source:29)
 at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.showNextPermissionGroupGrantRequest(Unknown Source:436)
 at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.onCreate(Unknown Source:535)
 at android.app.Activity.performCreate(Activity.java:7880)
 at android.app.Activity.performCreate(Activity.java:7869)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1300)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
 ... 11 more

**Comment by zhaobozhen** [comment]
补充一下，刚才在 MI 6 Android P 上测试也有同样的问题。

**Comment by RikkaW** [comment]
锅看起来是在凄惨 MIUI 的 com.lbe.security.miui（

**Comment by haruue** [comment]
我在我的设备上重现了这个问题 MI MIX 2 / MIUI 10 9.8.22 开发版（国内版）。
我这边在申请权限的时候就崩了。不过调用栈不太一样。

```
08-31 15:07:03.465 21945 21945 E AndroidRuntime: FATAL EXCEPTION: main
08-31 15:07:03.465 21945 21945 E AndroidRuntime: Process: com.lbe.security.miui:ui, PID: 21945
08-31 15:07:03.465 21945 21945 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lbe.security.miui/com.android.packageinstaller.permission.ui.GrantPermissionsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2985)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6878)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at com.android.packageinstaller.permission.ui.GrantPermissionsDefaultViewHandler.updateDescription(Unknown Source:23)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at com.android.packageinstaller.permission.ui.GrantPermissionsDefaultViewHandler.updateUi(Unknown Source:25)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.showNextPermissionGroupGrantRequest(Unknown Source:257)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.onCreate(Unknown Source:540)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7232)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7221)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965)
08-31 15:07:03.465 21945 21945 E AndroidRuntime: 	... 11 more
```

总之是 MIUI 的申请权限时的 UI （也就是 `com.lbe.security.miui` ）有问题， 随便砸开来看一下就知道问题所在：

首先是在 `com.android.packageinstaller.permission.ui.GrantPermissionsDefaultViewHandler.updateDescription()` ， 他们在用户申请权限时， 会针对这个权限组显示一个图标（像下面这个图一样）， 他们会从一个硬编码的 map 中取得该图标。
```java
private void updateDescription() {
    // ...
    if (this.mPermissions != null) {
        this.mPermissionIcon.setImageResource(((Integer) Utils.mGroupIconMap.get(this.mGroupName)).intValue());
    }
    // ...
}
```
![Screenshot_2019-08-31-15-28-56-099_com lbe security miui2](https://user-images.githubusercontent.com/13131972/64060884-a2381d00-cc05-11e9-9a68-5ecae27887fa.png)

这个 map 硬编码在 `com.android.packageinstaller.permission.utils.Utils` 的静态代码块中， 很显然， 里面不可能包含 shizuku 的权限组 `moe.shizuku.manager.permission-group.API` ， get() 方法返回了 `null`， 于是就 `NullPointerException` 了。
![image](https://user-images.githubusercontent.com/13131972/64060896-c3007280-cc05-11e9-86ba-728816bbb18f.png)

可能 MIUI 开发团队不知道第三方应用程序也可以声明 `dangerous` 级别的权限， 并且其他应用也可以按照运行时权限来申请授权。

我进行了一些额外的测试：
+ 即使关掉 MIUI 优化， 同样的问题仍然会发生。
+ 在开启 MIUI 优化之后， 系统的权限管理中（ `com.miui.securitycenter` ）并不能看到申请的 Shizuku 权限（如图所示）。
![Screenshot_2019-08-31-15-46-35-203_com miui securitycenter](https://user-images.githubusercontent.com/13131972/64060972-9f89f780-cc06-11e9-86b0-626fdcdb9659.jpg)
+ 用户如果希望手动开启权限， 需要关掉 MIUI 优化， 然后在 AOSP 原生的应用程序详情（ `android.settings.APPLICATION_DETAILS_SETTINGS` ）中的「权限」中才能看到 Shizuku 定义的几个权限。 并且， 在用户开启了 MIUI 优化时， 这个「权限」界面是进不去的（即使能进入 AOSP 的「应用程序详情」界面）。

## 解决方案
鉴于 MIUI 开发团队糟糕的代码质量， 我觉得等他们修复这个 BUG 应该不太可行。

一个推荐的方案是检测到 MIUI 并且没有授权时， 将本来的运行时权限申请过程替换成弹出提示界面（可能是一个 Dialog 然后带有一个开启帮助网页的按钮），引导用户关掉 MIUI 优化， 并手动给应用授予权限。

**Comment by zhaobozhen** [comment]
感谢回复。
了解了，看来问题确实出在了 MIUI 最近更新的 Package Manager。我也会争取和 MIUI 开发组联系看看会不会有更好的解决方案。

**Comment by siemsen522** [comment]
#66

**Comment by rmbb22** [comment]
[]()

**Comment by larry18001** [comment]
rish exec /path/to/other/shell.

**Comment by larry18001** [comment]
rish exec /path/to/other/shell.
