### ISSUE TITLE
[ADB] cannot access server-v6.dex 

### ISSUE THREAD

**Issue by Kartikiscool** [RikkaApps/Shizuku#452]
- [ x] Shizuku version is up-to-date
- [x ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

**Information:**

- Mode: [adb]
- Android version:5.1.1

**Logs:**

~ $ adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh         info: start.sh begin
WARNING: linker: shizuku_starter: unused DT entry: type 0x6ffffef5 arg 0xa38
WARNING: linker: shizuku_starter: unused DT entry: type 0x6ffffffe arg 0xd44
WARNING: linker: shizuku_starter: unused DT entry: type 0x6fffffff arg 0x2
info: source dex path is /storage/emulated/0/Android/data/moe.shizuku.privileged.api/files/server-v6.dex
fatal: can't access /storage/emulated/0/Android/data/moe.shizuku.privileged.api/files/server-v6.dex, please open Shizuku app and try again.
info: shizuku_starter exit with non-zero value 1

**Describe the bug:**

@RikkaW 
I cant seem to start service with adb i just get the same error cant access server-v6.dex 

![Screenshot_20240319-181625_Termux](https://github.com/RikkaApps/Shizuku/assets/160822170/ac144529-2231-46ce-a38c-22e6dbcfba51)

**Comment by RikkaW** [comment]
Android 5 has not been supported for a really long time. 🤔

**Comment by Kartikiscool** [comment]
What is the issue android 5 should work just fine

Do you not have any solutions for this issue?  @RikkaW

**Comment by RikkaW** [comment]
Back in the old days, runtime permission (yes, apps can define their own permission for other apps to request, with system's UI) from Android 6+ is the only auth method.
As most apps using Shizuku should require Android 6+ or higher, it's not worth checking and fixing all the parts (most app UI, then UserService) to make it work on Android 5 again.
