### ISSUE TITLE
problem internet connect

### ISSUE THREAD

**Issue by mubkk** [RikkaApps/Shizuku#46]
After I installed shizuku, All internet connection app show "49年" in system notification like the attached pic. I tried uninstall, but can't fix.
![Screenshot_20190910-074942](https://user-images.githubusercontent.com/53546939/64575865-07c3a080-d3a0-11e9-95d3-e19176cbe279.png)

**Comment by RikkaW** [comment]
The last segment of the title of notification is time (set by the app send the notification).
Your case is more like your system time had been reset to 0 (1970-1-1) and this app use this time in the notification, so it shows "49年" after system time is synced.
So it's very likely to be a coincidence which not related to Shizuku.

**Comment by mubkk** [comment]
Thanks for your comment and I'm so sorry for wrong report to you.

Regards
