### ISSUE TITLE
cann‘t input pair code

### ISSUE THREAD

**Issue by qwert-f** [RikkaApps/Shizuku#468]
Please report bugs of Shizuku itself.

**Requirements:**

- [x ] Shizuku version is up-to-date
- [ x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [ x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [ ] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:latest
- Mode: [adb, root]:
- Android version:14
- Device: (optional)oneplus9r

**Logs:**

Related **full logcat**.

**Describe the bug:**

while click pair by code just show notify，i cnn't input pair code to pair

**Additional context:**

**Comment by Akhan7126** [comment]
1.

**Comment by qwert-f** [comment]
> 1. 

not understand what you mean，after i cancle find device，input field show
