### ISSUE TITLE
Need to download the 2 rish files manually until i fix open_document_tree error with Shizuku, so not a bug just HELP

### ISSUE THREAD

**Issue by theteeth** [RikkaApps/Shizuku#474]
need to download the 2 rish files ( rish & the .dex file) manually until i fix open_document_tree error with Shizuku
Maybe Shizuku could use different ui for folders etc?
i've tried discussions & looked through the github assets but can't find

Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:
- Mode: [adb, root]
- Android version:
- Device: (optional)

**Logs:**

Related **full logcat**.

**Describe the bug:**

**Additional context:**

**Comment by theteeth** [comment]
Thanks! Sorry didn't realise an apk has same format as a zip. Android beginners! Thanks again

**Comment by albinocabrera880-lab** [comment]
Muy buena

**Comment by spamoed00-rgb** [comment]
> They are in the sets folder of the apk.

**Comment by spamoed00-rgb** [comment]
> need to download the 2 rish files ( rish & the .dex file) manually until i fix open_document_tree error with Shizuku Maybe Shizuku could use different ui for folders etc? i've tried discussions & looked through the github assets but can't find
> 
> Please report bugs of Shizuku itself.
> 
> **Requirements:**
> 
> * [x]  Shizuku version is up-to-date[x]  Shizuku is downloaded from official channels (GitHub release or Google Play)[x]  Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)[x]  (Root users) No Xposed installed / Xposed is not enabled for Shizuku
> 
> Change "[x]" to "[]if it meets the requirements.
> 
> Reports not meet the requirements will be immediately closed. 
> 
> Information:
> 
> Shizuku version:
> Mode: [adb, root]
> Android version:
>  Device: (optional)
> 
> Logs:
> 
> Related full logcat
> 
> Describe the bug:
> 
> A clear and concise description of what the bug is.
> 
> Additional context:
> 
> Add any other context about the problem here.
