### ISSUE TITLE
Stuck in Shizuku.bindUserService sometimes.

### ISSUE THREAD

**Issue by laiqun** [RikkaApps/Shizuku#475]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:13.5.4.r1049.0e53409
- Mode: [adb, root]adb
- Android version:14
- Device: (optional)

**Logs:**

Related **full logcat**.

**Describe the bug:**

app may can't bindUserService success sometimes. 
If lock Shizuku GUI, and wait for a while(300ms) after open my App, the rate of this issue can down.
Kill Shizuku GUI process, the issue occur rate also can down.

**Additional context:**

**Comment by RikkaW** [comment]
Shizuku app helps UserService to send its binder to Shizuku server. So, if the normal operation of Shizuku app is affected, UserService will break as well.

https://github.com/RikkaApps/Shizuku/blob/979235425dc3562b4ba38cc168b92513f2fbaefe/manager/src/main/java/moe/shizuku/manager/ShizukuManagerProvider.kt#L30-L71

**Comment by laiqun** [comment]
Same with Issue: https://github.com/RikkaApps/Shizuku/issues/451
