### ISSUE TITLE
Persistent Notifications to keep Shizuku Alive

### ISSUE THREAD

**Issue by MacgyverJohnson** [RikkaApps/Shizuku#48]
Dear @RikkaW,
Shizuku is a phenomenal app for free and I have been greatly benefited...Using two shizuku assisted apps such as icebox and app ops in Samsung galaxy a50 android pie stock rom unrooted. With shizuku versionVersion 3.4.5.r288.726cd9a ... I have been facing a problem...Shizuku is getting killed even after making it "not optimised" in settings and disabling power saver mode...I did check out tips that were given in the website to make to persist without reboot....
So could there be persistent notification service that would keep the service alive ...or background service?
Thanks in advance....

**Comment by RikkaW** [comment]
Shizuku relies on the process started with adb or root, let Shizuku app itself not being killed does not help.

**Comment by MacgyverJohnson** [comment]
Just resolved this issue....adb using usb was never persistent..no matter what...now tried adb wireless and its works like a charm....working for days ...
On a different note ate there othere shizuku based apps besides app ops and icebox?
