### ISSUE TITLE
Xiaomi device notification wireless pairing optimization

### ISSUE THREAD

**Issue by ZXAS007** [RikkaApps/Shizuku#480]
In the classic notification style on Xiaomi devices, you only need to long press the notification to display the native reply button and then enter. Shizuku's input pairing code button replaces the native button and makes it unusable. Apps including tg and Black Threshold use the native reply button and have been tested.  The notification reply function can be used in the classic notification style, so I hope shizuku can also optimize this part

**Comment by RikkaW** [comment]
> Shizuku's input pairing code button replaces the native button and makes it unusable.

Native reply action is used (it is so native; it doesn't even use androidx library). I don't know and don't care why MIUI breaks it.

https://github.com/RikkaApps/Shizuku/blob/979235425dc3562b4ba38cc168b92513f2fbaefe/manager/src/main/java/moe/shizuku/manager/adb/AdbPairingService.kt#L271-L294
