### ISSUE TITLE
Does Shizuku not support editing .idc files?

### ISSUE THREAD

**Issue by Auditormadness9** [RikkaApps/Shizuku#482]
![Screenshot_20240503_220422_SystemUI Tuner.png](https://github.com/RikkaApps/Shizuku/assets/71278545/d1277187-10e4-4f89-aefd-24eab78524bf)

**Comment by BRBsoup** [comment]
Probably the button that says "Open Shizuku" 🤔🧔

**Comment by Auditormadness9** [comment]
> Probably the button that says "Open Shizuku" 🤔🧔

It just opens the website.
The Shizuku app itself is up and running and is granted all rights.
