### ISSUE TITLE
能否添加通过小黑屋的设备管理员权限获得权限？

### ISSUE THREAD

**Issue by lv746591263** [RikkaApps/Shizuku#483]
我看安装狮可以通过小黑屋获得权限，那shizuku的权限是否也可以这样获得？小黑屋有个设备管理员权限，那个重启后不用再重新弄这个获得权限的操作，很方便

**Comment by RikkaW** [comment]
管理员的权限十分有限，几乎只能满足冻结、安装这样十分有限的需求，而 adb 可以做的事情多太多
