### ISSUE TITLE
Legacy not working

### ISSUE THREAD

**Issue by cabban** [RikkaApps/Shizuku#51]
Cant tap

Huawei mate20 Pro android 10 kind regards

**Comment by cabban** [comment]
Thank u for nothing bad support!

**Comment by RikkaW** [comment]
No one can help for a single "Cant tap"

**Comment by cabban** [comment]
> No one can help for a single "Cant tap"

Can't start the action I ment at the top  legacy can't tap that one

**Comment by RikkaW** [comment]
I can't understand what you say.

**Comment by cabban** [comment]
> I can't understand what you say.
Very odd that u is a developer when you not even understand a quite easy issue rapport, sorry.. This is 
Not even hard to understand. Your app not working and it says can't start the action..😀

**Comment by RikkaW** [comment]
Have you tried to start the service?

**Comment by cabban** [comment]
> Have you tried to start the service?

Ofc several times 😀not working

**Comment by haruue** [comment]
Please tell us how you start the service?

+ root? adb?
+ if you start the service with root, please upload a screenshot or screen record after you tap the "start" button.
+ if you start the service with adb, please paste the output of start command here.
