### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by genspider** [RikkaApps/Shizuku#52]
安卓内终端（termux）也可以运行sh命令，但是尝试启动服务时，报错：
info: start.sh begin
start.sh: 9: start.sh: [[: not found
Starter file not exist, please open Shizuku Manager and try again.
是否可以扩展下启动方式？

**Comment by haruue** [comment]
Termux 只有应用权限， 没有 adb 权限。 即使能启动  Server ， 有
