### ISSUE TITLE
pm disable之后的应用无法通过shizuku调用package service启用

### ISSUE THREAD

**Issue by gogogoghost** [RikkaApps/Shizuku#53]
您好，最近开发一款冻结类APP，支持root与shizuku冻结应用，发现当应用被通过pm disable停用后，通过shizuku远程调用package service操作应用都会失败，代码如下
```kotlin
fun disableApp(pkgName:String):Boolean{
            val data=SystemServiceHelper.obtainParcel("package","android.content.pm.IPackageManager","setApplicationEnabledSetting")
            val reply=Parcel.obtain()
            data.writeString(pkgName)
            data.writeInt(3)
            try{
                ShizukuService.transactRemote(data,reply,0)
                reply.readException()
            }catch (e:Exception){
                Log.e("Shizuku",e.toString())
                return false
            }finally {
                data.recycle()
                reply.recycle()
            }
            return true
        }
```
他在正常情况工作良好，root模式使用了命令行的service指令去远程调用该服务，同样工作良好。但是当应用被pm disable一次之后，shizuku调用时会出现以下错误：
```shell
java.lang.SecurityException: Shell cannot change component state for com.coolapk.market/null to 3
```
报错信息与shell下未获取root权限时执行调用指令相类似：
```shell
$ pm disable com.coolapk.market
Security exception: Shell cannot change component state for com.coolapk.market/null to 2
```
即使应用被pm disable，root模式下通过命令行service指令调用同样的远程调用是可以继续修改应用停用状态的。但通过shizuku会出现错误。
安卓7的模拟器与安卓9的实体机同样出现了这个问题。
这个问题不影响程序主要执行流程，但比较好奇产生原因，希望作者能够解答，十分感激！

**Comment by gogogoghost** [comment]
标题不太严谨，补充一下，pm disable之后，是不能启用也不能停用（同样的方法，启用设置传入参数0，停用传入3），其他应用不受影响，仅被pm disable的应用会报错。

**Comment by RikkaW** [comment]
原因在[这边](https://cs.android.com/android/platform/superproject/+/android10-release:frameworks/base/services/core/java/com/android/server/pm/PackageManagerService.java;l=21269-21278)，shell 只能在 `COMPONENT_ENABLED_STATE_DISABLED_USER (3)` `COMPONENT_ENABLED_STATE_DEFAULT (0)` `COMPONENT_ENABLED_STATE_ENABLED (1)` 直接切换。你的在 `pm disable` 后再设为 3 应该就是从 `COMPONENT_ENABLED_STATE_DISABLED (2)` 到 3 所以不行（

**Comment by gogogoghost** [comment]
十分感谢
