### ISSUE TITLE
The button to the dev menu doesn't work on samsung android 14

### ISSUE THREAD

**Issue by xizerlix** [RikkaApps/Shizuku#531]
- [ V] Shizuku version is up-to-date
- [V ] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [V ] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.5.4
- Mode: [adb]
- Android version: 14
- Device: Samsung SM-A346E

**Logs:**

Related **full logcat**.

**Describe the bug:**

The button to the dev menu doesn't work on samsung android 14, it shows toast with text "Turn on Developer options first" (of course it already turned on).

**Additional context:**

![123](https://github.com/RikkaApps/Shizuku/assets/55129929/b6fdd4b5-bc98-4cf3-bf19-011e9104233e)

**Comment by xizerlix** [comment]
Looks like this problem exists only on model SM-A346E Android 14. Yesterday I have tested it on other Samsung models with Android 14 and had no mentioned problem. I'll wait for a solution from Samsung.

**Comment by ladywitchie** [comment]
> Looks like this problem exists only on model SM-A346E Android 14. Yesterday I have tested it on other Samsung models with Android 14 and had no mentioned problem. I'll wait for a solution from Samsung.

Nope, I'm having this same exact issue on a Samsung Galaxy Flip 3 as of Novemember 2024.

**Comment by fxfxyfx** [comment]
Same issue A23

**Comment by gursuj** [comment]
It worked previously on my A23 but doesn't now. For now, I got it running by connecting it to a PC and using the adb command. Note that the command provided on the [site](https://shizuku.rikka.app/guide/setup/#start-shizuku-3) may not work on your device. You'll need to use the specific command given by the `View Command` button.
