### ISSUE TITLE
Listener for "Tap to manange authorized apps"

### ISSUE THREAD

**Issue by henrichg** [RikkaApps/Shizuku#538]
Please, how to get into my application changes in Shizuku "Tap to manange authorized apps"? Exists listener for this?
Thanks.

**Comment by J-b432** [comment]
M

في الثلاثاء، ٢٥ يونيو ٢٠٢٤, ١:٣٩ م Henrich Gron ***@***.***>
كتب:

**Comment by henrichg** [comment]
OK, not needed. Because if in Shizuku I uncheck application, then application is terminated. And start of PPP again requires grant of Shizuku permission.

Issue closed.
