### ISSUE TITLE
Remove com.oplus.wifitest from Recommended list

### ISSUE THREAD

**Issue by trix7777** [RikkaApps/Shizuku#549]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[x]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version: 13.5.4.r1049.0e53409
- Mode: [adb, root]: adb
- Android version: 13
- Device: (optional) OnePlus 8 Pro (OxygenOS 13.1)

**Logs:**

Not relevant, close the issue if you want, I'm just telling you 😊

**Describe the bug:**

Uninstalling com.oplus.wifitest disables the function of the wireless debugging feature.

**Additional context:**

N/A

**Comment by trix7777** [comment]
I forgot to say that I really like your work! Thank you for this excellent app!! How can I support you?

Oh, and two suggestions as well, make the uninstalled apps searchable, preferably with both real package names and the user understandable names. The other is that I wish to hide some apps in the installed list, like the ones that are recommended to remove but as I as a user want to keep. Like an ignore list. 

Again, thank you for your good work!

**Comment by trix7777** [comment]
Sorry I must have been drunk or had a temporary memory lapse, this bug is not for Shizuku, it's for Canta obviously 🫣 Please close it 🌹

**Comment by MillionsToOne** [comment]
You can close it yourself
