### ISSUE TITLE
Shizuku not showing startup options except Root Option.

### ISSUE THREAD

**Issue by dwidarr** [RikkaApps/Shizuku#559]
When I open Shizuku, it only shows that the app is not running, and it doesn't show the startup options other than root like Wireless debugging. 
Here's what it looks like: 
![Screenshot_2024-07-25-21-23-20-876_moe shizuku privileged api](https://github.com/user-attachments/assets/fec606f8-d629-4ffa-a8b3-103562a7e96d)
Any help would be appreciated.

**Comment by LiJiu-gfgfv** [comment]
It may be that your magisk has hidden the root permission from shizuku 
(it is a comment through the translator)
可能是你的Magisk对Shizuku隐藏了root权限

**Comment by dwidarr** [comment]
> It may be that your magisk has hidden the root permission from shizuku (it is a comment through the translator) 可能是你的Magisk对Shizuku隐藏了root权限

My device isn't rooted though

**Comment by LiJiu-gfgfv** [comment]
> > It may be that your magisk has hidden the root permission from shizuku (it is a comment through the translator) 可能是你的Magisk对Shizuku隐藏了root权限
> 
> My device isn't rooted though

可能是你的设备没有USB调试也不支持无线adb调试
Maybe your device doesn't have USB debugging or support wireless adb debugging.

**Comment by dwidarr** [comment]
Nevermind, I figured out the issue. I was on second space, and I guess the device doesn't give 'admin' privileges to that space. I switched to first space, and it worked just fine. Thank you.

**Comment by LiJiu-gfgfv** [comment]
> Nevermind, I figured out the issue. I was on second space, and I guess the device doesn't give 'admin' privileges to that space. I switched to first space, and it worked just fine. Thank you.

Glad to help you.
