### ISSUE TITLE
Add an actual License to the repo

### ISSUE THREAD

**Issue by licaon-kter** [RikkaApps/Shizuku#56]
Ref: https://github.com/Aefyr/SAI/issues/43#issuecomment-541360323

/LE: It appears here: https://github.com/RikkaApps/Shizuku/blob/master/publish.gradle#L6 but is that for the whole repo?

**Comment by TPS** [comment]
@RikkaW please give some attention to this. 🙇🏾‍♂️

**Comment by RikkaW** [comment]
API has been moved to a standalone repo (https://github.com/RikkaApps/Shizuku-API), no license problem.
Dependencies also have been added to JCenter, no [custom repo problem](https://github.com/Aefyr/SAI/issues/43#issuecomment-541360323).

**Comment by TPS** [comment]
@RikkaW We mean include 1 in each repo.  https://choosealicense.com/ can help you a lot, if you wish.

**Comment by Atrate** [comment]
@RikkaW
This does not solve the issue. For people to be able to fork and change/enhance Shikuzu legally you need to select a license.

I'd personally recommend the GPLv3, for reasons of software freedom.

**Comment by Cyberavater** [comment]
@RikkaW 
Hi, if you meant this app to be open-source, please consider adding a license. Many open-source apps are refusing to use it, which is very disappointing.

**Comment by PowerOlive** [comment]
you let other people commit code to a copyrighted repo owned by you hosted by github
that is funny

**Comment by ThatOneCalculator** [comment]
Shizuku is now Apache 2 licensed. It'd be a great option to have :)
