### ISSUE TITLE
adb激活

### ISSUE THREAD

**Issue by caihe77** [RikkaApps/Shizuku#57]
C:\Users\xx>adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh
sh: /sdcard/Android/data/moe.shizuku.privileged.api/files/start.sh: No such file or directory

**Comment by RikkaW** [comment]
可能是[这里](https://github.com/android-in-china/Compatibility/issues/1)提到的情况？

**Comment by RikkaW** [comment]
尚未发布的新的版本已经将启动脚本移动至 `/data`，就不会遇到上面的问题了（
