### ISSUE TITLE
shizuku 权限显示错误

### ISSUE THREAD

**Issue by skbeh** [RikkaApps/Shizuku#58]
设备：LG G5
系统：Android 7.0
shizuku 版本：3.5.0.r323
如图，shizuku 权限显示为权限名，而不是正常的中文。
此问题在某次更新后出现。（好像是最近的一次更新）
![Screenshot_2020-03-17-09-57-19](https://user-images.githubusercontent.com/60107333/76814670-562b7f00-67c9-11ea-911d-3a2419ab28ce.png)

**Comment by RikkaW** [comment]
尝试重装（

**Comment by skbeh** [comment]
> 尝试重装（

重装后问题未解决。

**Comment by skbeh** [comment]
偶然发现又正常了......
