### ISSUE TITLE
Cannot install back after uninstalling

### ISSUE THREAD

**Issue by edntdftdftg** [RikkaApps/Shizuku#615]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment or broken ROM (GrapheneOS)
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

- Shizuku version: cannot install
- Mode: [adb, root] used to use root but cannot install
- Android version: 12
- Device: (optional) lenova yoga tab 11 rooted Via magisk

When i try to install Via Google play it says try again later. When i try to install using APK i get this error:
INSTALL_FAILED_DUPLICATE_PERMISSION: Package moe.shizuku.privileged.api attempting to redeclare permission moe.shizuku.privileged.api.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION already owned by moe.shizuku.privileged.api
When i uninstalled, the device rebooted but without the logo. I had a custom boot animation that Played after the logo comes, and when i clicked uninstall that bootanimztion Played. İ cant install now, pls help ASAP.

Thanks in advance.

**Comment by edntdftdftg** [comment]
Edit: sorry if its not Clear enough. My main languge is not english

**Comment by shaggyskunk** [comment]
"Custom Boot Animation", are you Rooted?

**Comment by shaggyskunk** [comment]
And, what device & Android version?

**Comment by edntdftdftg** [comment]
I said them all on the text but i will say again for you
Lenovo yoga tab 11 with root (magisk)
Android 12

**Comment by edntdftdftg** [comment]
Any helpp??

**Comment by edntdftdftg** [comment]
Anyone active plsss???

**Comment by edntdftdftg** [comment]
Please help

**Comment by edntdftdftg** [comment]
C'mon

**Comment by shaggyskunk** [comment]
Maybe Factory Reset and start over.

**Comment by edntdftdftg** [comment]
I cannot do that, there are too much important data. Are there any other solutions?

**Comment by shaggyskunk** [comment]
I'm not the Developer, and everyone has important data, and I know that it's a pain to Factory Reset, but since you have Root, you shouldn't have any problems with backing up your device. Swift Backup is quite good.

I personally have Unrooted Samsung devices, and they can't be Rooted because of Locked Bootloaders.. but I have never lost anything using Samsung's Smart Switch to backup my devices..
If I had your device, that's what I'd try, instead of wasting time here.

**Comment by edntdftdftg** [comment]
Thanks!
