### ISSUE TITLE
[code] sorry for ask how to write a binder to shizuku

### ISSUE THREAD

**Issue by NewBugger** [RikkaApps/Shizuku#64]
sorry for the stupid question.

i viewed the sample, then not known for those lines, i don't know how to write a binder and write it on which class or package, my app have mutilple packages named..
https://github.com/RikkaApps/Shizuku/blob/75b84e97bd3aa857361903161b433e744efe1711/sample/src/main/java/moe/shizuku/sample/MainActivity.java#L52 and https://github.com/RikkaApps/Shizuku/blob/75b84e97bd3aa857361903161b433e744efe1711/sample/src/main/java/moe/shizuku/sample/SampleApplication.java#L58 and https://github.com/RikkaApps/Shizuku/blob/75b84e97bd3aa857361903161b433e744efe1711/sample/src/main/AndroidManifest.xml#L29-L35

if bothered, just close this.

**Comment by Carlos041790** [comment]
Jaajajj bien perro desesperrado  🤣🤣🤣🤣

**Comment by NewBugger** [comment]
```
I/ActivityManager: Start proc for activity {.ui.home.HomeActivity}
E/AndroidRuntime: Process: org.princess.connecter.appchecker, PID: 20230
D/ShizukuServerV3: onActive: uid=10220, packages=org.princess.connecter.appchecker
W/ActivityTaskManager:   Force finishing activity /.ui.home.HomeActivity
I/ActivityManager: Showing crash dialog for package org.princess.connecter.appchecker u0
W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{5efb9cc u0 /.ui.home.HomeActivity t4556 f}
W/ActivityTaskManager: Activity pause timeout for ActivityRecord{5efb9cc u0 /.ui.home.HomeActivity t4556 f}
W/ActivityTaskManager:   Force finishing activity /.ui.home.HomeActivity
```

**Comment by NewBugger** [comment]
```
I/ActivityManager: Start proc for activity {.ui.home.HomeActivity}
E/AndroidRuntime: Process: , PID: 20230
D/ShizukuServerV3: onActive: uid=10220, packages=
W/ActivityTaskManager:   Force finishing activity /.ui.home.HomeActivity
I/ActivityManager: Showing crash dialog for package u0
W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{5efb9cc u0 /.ui.home.HomeActivity t4556 f}
W/ActivityTaskManager: Activity pause timeout for ActivityRecord{5efb9cc u0 /.ui.home.HomeActivity t4556 f}
W/ActivityTaskManager:   Force finishing activity /.ui.home.HomeActivity
```
i wanna call shizuku api in package org.princess.connecter.appchecker.ui, while my application name is defined to org.princess.connecter.appchecker, i'm afraid that shizuku binder won't take effect to other package even if it is at the same application.

i write the codes from learning sample: https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/AndroidManifest.xml#L47-L62 and https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/java/io/github/newbugger/android/blocker/ui/component/ComponentActivity.kt#L200-L234 and https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/java/io/github/newbugger/android/blocker/ui/component/ShizukuBinderReceiver.kt#L10-L18 and https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/java/io/github/newbugger/android/blocker/BlockerApplication.kt#L33-L51 and https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/java/io/github/newbugger/android/blocker/BlockerApplication.kt#L74-78

**Comment by NewBugger** [comment]
```
I/ActivityManager: Start proc for activity {.ui.home.HomeActivity}
E/AndroidRuntime: Process: , PID: 20230
D/ShizukuServerV3: onActive: uid=10220, packages=
W/ActivityTaskManager:   Force finishing activity /.ui.home.HomeActivity
I/ActivityManager: Showing crash dialog for package u0
W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{5efb9cc u0 /.ui.home.HomeActivity t4556 f}
W/ActivityTaskManager: Activity pause timeout for ActivityRecord{5efb9cc u0 /.ui.home.HomeActivity t4556 f}
W/ActivityTaskManager:   Force finishing activity /.ui.home.HomeActivity
```
i wanna call shizuku api in package io.github.newbugger.android.blocker.ui.component, while my application name is defined to io.github.newbugger.android.blocker, i'm afraid that shizuku binder won't take effect to other package even if it is at the same application.

i write the codes from learning sample: https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/AndroidManifest.xml#L47-L62 and https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/java/io/github/newbugger/android/blocker/ui/component/ComponentActivity.kt#L200-L234 and https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/java/io/github/newbugger/android/blocker/ui/component/ShizukuBinderReceiver.kt#L10-L18 and https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/java/io/github/newbugger/android/blocker/BlockerApplication.kt#L33-L51 and https://github.com/NewBugger/blocker-Android/blob/0d3dc5975a742ddd70a0f05e84317c285b7d7eac/app/src/main/java/io/github/newbugger/android/blocker/BlockerApplication.kt#L74-78

**Comment by RikkaW** [comment]
The first part is related to multi-process and those codes are only used for testing. It seems your app runs in a single process, you don't need to use things related to `ShizukuMultiProcessHelper` (`ShizukuBinderReceiver` in your code is unnecessary).

When an app starts, Shizuku sends the binder to the app via ContentProvider. So the user app needs to add the provider, `moe.shizuku.api.ShizukuBinderReceiveProvider`, to manifest.

Inside `ShizukuBinderReceiveProvider`, things are very simple, the received binder is stored to a static field in `ShizukuService` and call the `OnBinderReceivedListener` (again, a static field is used to store the listener).

Since `ShizukuBinderReceiveProvider` can't be guaranteed to the first to run, it's better to implement such a process.

1. Show the loading UI
2. Wait until `OnBinderReceivedListener` is called
3. Check permission and use `ShizukuService`

**Comment by NewBugger** [comment]
> The first part is related to multi-process and those codes are only used for testing. It seems your app runs in a single process, you don't need to use things related to `ShizukuMultiProcessHelper` (`ShizukuBinderReceiver` in your code is unnecessary).
> 
> When an app starts, Shizuku sends the binder to the app via ContentProvider. So the user app needs to add the provider, `moe.shizuku.api.ShizukuBinderReceiveProvider`, to manifest.
> 
> Inside `ShizukuBinderReceiveProvider`, things are very simple, the received binder is stored to a static field in `ShizukuService` and call the `OnBinderReceivedListener` (again, a static field is used to store the listener).
> 
> Since `ShizukuBinderReceiveProvider` can't be guaranteed to the first to run, it's better to implement such a process.
> 
> 1. Show the loading UI
> 2. Wait until `OnBinderReceivedListener` is called
> 3. Check permission and use `ShizukuService`

grateful thanks for answering me.

because i notice that multi-process disabled in sample https://github.com/RikkaApps/Shizuku/blob/75b84e97bd3aa857361903161b433e744efe1711/sample/src/main/AndroidManifest.xml#L39 and i refered this issue https://github.com/RikkaApps/Shizuku/issues/32#issuecomment-489157785
>> All I had to do was to put MultiProcessHelper.initialize(main) after getting permission. i'll remove multi-process related code and retry.

thanks again.

**Comment by RikkaW** [comment]
`android:multiprocess` of ContentProvider controls if the provider would be created for each process (https://developer.android.com/guide/topics/manifest/provider-element#multi).

Because on API 26+, there is no way to detect process creation (only `onUidActive` from `UidObserver`, not sure if there are other APIs). So the provider must be run in a specific process.

**Comment by NewBugger** [comment]
sorry, should i use onBinderReceivedListener {} or setBinderReceivedListener {}

**Comment by NewBugger** [comment]
i'm failed on shizukuTestV3 (log is the above reported), but successed on transactRemote use ..

**Comment by RikkaW** [comment]
Read/write stream from `RemoteProcess` in two threads, and please don't use `newProcess` to test Shizuku.

**Comment by NewBugger** [comment]
> Read/write stream from `RemoteProcess` in two threads, and please don't use `newProcess` to test Shizuku.

thanks and sorry, i followed the sample which use new process..
