### ISSUE TITLE
关于 ShizukuService#newProcess deprecated 的疑问

### ISSUE THREAD

**Issue by zhaobozhen** [RikkaApps/Shizuku#66]
今天看到 API 4.0.0 中将 ShizukuService#newProcess 方法标记为 depreacted，并推荐使用 binder 交互。但是我的应用需要使用 adb am 指令而并非 pm 指令，可以用 binder 拿到 ActivityManager 吗？

**Comment by RikkaW** [comment]
那当然是可以的（
你看例子里有用 PackageManager 和 UserManager 的

**Comment by zhaobozhen** [comment]
明白啦，感谢。
