### ISSUE TITLE
Shizuku Start via adb debug (localhost)

### ISSUE THREAD

**Issue by thetoolz** [RikkaApps/Shizuku#81]
Fire tv / android tv
can start adb command no pc
Through adb debugging

There should be a
Adb debugging option to start Shizuku

Adb debugging must be enabled in settings
(Only available on tv)

usb debugging pop up will show up to allow
Running of adb command

i still use tasker & tasker adb shell plugin app
to start shizuku adb command

adb connect localhost:5555
adb shell sh /data/user_de/0/moe.shizuku.privileged.api/start.sh

usb debugging pop up will show up to allow
Running of adb command

**Comment by haruue** [comment]
Launch-method which is only supported by a specific model will not be added into Shizuku.

If you think this is a common behavior or feature across many Android TV, please provide the screenshot or video for the instruction.

I don't think I understood what you are trying to say. Maybe you can try to use [Google Translator](https://translate.google.com/) or [DeepL Translator](https://www.deepl.com/en/translator) to make the issue easier to understand?

**Comment by thetoolz** [comment]
i guess i will still use
use tasker & tasker adb shell plugin app
to start shizuku adb command

if adb debugging is enabled in fire tv settings allows shizuku to start
on localhost:5555 through adb
directly on fire tv

**Comment by haruue** [comment]
This is a bug of your TV manufacturer, who set the service.adb.tcp.port=5555 by default in the system build.prop, that is why you can connect it with `adb connect` after "Enable the adb debugging".

The service.adb.tcp.port should be set to -1 in the common production builds, so this method only works on the devices with the above bug. Shizuku will not support it.

**Comment by thetoolz** [comment]
port 5555 is android default port

**Comment by RikkaW** [comment]
Version 5.1.0 adds the ability to try 5555 port without the system property check, please try and explain if it works.

**Comment by thetoolz** [comment]
No 5.1.0 changed nothing on port 5555
Guess I will continue to use tasker to start shizuku

**Comment by RikkaW** [comment]
What I thought:
Some weird TV with adb enabled but not system properties are not set

What is real:
Maybe @thetoolz don't even find the adb option existing before 💩
