### ISSUE TITLE
Can't uninstall shizuku when Island/Ice Box is working at Device Owner Mode

### ISSUE THREAD

**Issue by CDN18** [RikkaApps/Shizuku#83]
100% chance of getting a soft reboot when I'm trying to uninstall shizuku, Hope it can be fixed

----
Device: OnePlus 7 Pro
Android Version: 10
Shizuku State: Deactivated(Not working)
Device Owner(APP): Island

**Comment by RikkaW** [comment]
I can't 100% resurface it in the emulator at 100% chance (the chance is not high), and there are no meaningful logs.

Also, if the problem happens when Shizuku is stopped, it should not be a problem of Shizuku itself. When Shizuku is not running,  the only difference of Shizuku from any other apps is Shizuku defines a custom permission. I guess there may be deadlocks when the system resets permissions.

**Comment by RikkaW** [comment]
Commit 3678486 adds self-implemented permission to replace custom runtime permission. For backward compatibility, the existing permission cannot be removed immediately. If the permission was removed in the future, Shizuku itself is nothing different from a normal app. Close this issue since the problem is "solved".

**Comment by Nashmi97** [comment]
> 

M

**Comment by farshadjanu1** [comment]
``

**Comment by bek87** [comment]
Wow

**Comment by Yatkha01** [comment]
Very good

**Comment by Skizzels** [comment]
Op vr 19 apr. 2024 17:41 schreef Yatkha01 ***@***.***>:

**Comment by Hamam280788** [comment]
3678486c13b012b9f650d1d5363b7e222392d34e

**Comment by Hamidreza1360-coder** [comment]
> 100% chance of getting a soft reboot when I'm trying to uninstall shizuku, Hope it can be fixed
> 
> ----
> Device: OnePlus 7 Pro
> Android Version: 10
> Shizuku State: Deactivated(Not working)
> Device Owner(APP): Island
>

**Comment by musa098-indo** [comment]
adb shell /data/app/moe.shizuku.privileged.api-xvd8dzYdQx-HDZnbQfhojw==/lib/arm64/libshizuku.so

**Comment by akhil22697** [comment]
Also, if the problem happens when Shizuku is stopped, it should not be a problem of Shizuku itself. When Shizuku is not running, the only difference of Shizuku from any other apps is Shizuku defines a custom permission. I guess there may be deadlocks when the system resets permissions.

**Comment by poteakshay241** [comment]
K

**Comment by kpwint54-cloud** [comment]
adb shell /data/app/moe.shizuku.privileged.api-xvd8dzYdQx-HDZnbQfhojw==/lib/arm64/libshizuku.so

**Comment by kpwint54-cloud** [comment]
adb shell /data/app/moe.shizuku.privileged.api-xvd8dzYdQx-HDZnbQfhojw==/lib/arm64/libshizuku.so

**Comment by kpwint54-cloud** [comment]
adb shell /data/app/moe.shizuku.privileged.api-xvd8dzYdQx-HDZnbQfhojw==/lib/arm64/libshizuku.so

**Comment by omarshahen541-dotcom** [comment]
@RikkaW

**Comment by ftwcash2-netizen** [comment]
https://github.com/rikkaapps/shizuku/issues/83

**Comment by irfanmulla37121-crypto** [comment]
Gauusyyqiduyss

**Comment by sharmasuraj96950-hash** [comment]
https://github.com/RikkaApps/Shizuku/issues/83#issue-705466391

**Comment by sharmasuraj96950-hash** [comment]
https://github.com/RikkaApps/Shizuku/issues/83#issue-705466391

**Comment by sharmasuraj96950-hash** [comment]
https://github.com/RikkaApps/Shizuku/issues/83#issue-705466391

**Comment by MustafaKabashi** [comment]
Yo

**Comment by thurazawthz9963-cpu** [comment]
again

**Comment by thurazawthz9963-cpu** [comment]
> shizuku ကို uninstall လုပ်ဖို့ကြိုးစားတဲ့အခါ soft reboot ရဖို့ 100% အခွင့်အလမ်း၊ ပြုပြင်နိုင်မယ်လို့ မျှော်လင့်ပါတယ်
> 
> စက်ပစ္စည်း- OnePlus 7 Pro Android ဗားရှင်း- 10 Shizuku အခြေအနေ- ပိတ်ထားသည်(အလုပ်မလုပ်) စက်ပစ္စည်းပိုင်ရှင်(APP)- ကျွန်း

[README.md](https://github.com/user-attachments/files/23218343/README.md)

**Comment by thurazawthz9963-cpu** [comment]
*&&"^÷¥%

**Comment by Hamidreza1360-coder** [comment]
TronLink GUARDIAN:
Popular websites to buy energy  🔋

• https://app.justlend.org/#/energy

•https://sunfee.io

•https://catfee.io

•https://tchange.cc

• https://tr.energy/en/consumers/

• https://www.tokengoodies.com/buy-energy

• https://trc.aeee.io/

• https://tronlending.xyz/rent

• http://Nitronenergy.com

• https://trxx.io/en/

• https://tronenergy.market/exchange/rentenergy

• https://feee.io/?ic=53JF 

• https://tronpulse.io/r/rentenergy

• https://tronnrg.com/

• http://ergon.ustx.io 

• https://Tofee.net

• https://renttronenergy.com/rent

• https://mefree.net

• https://tronenergize.com/

• https://dapp.brutus.finance/?energy

• https://tronsave.io/

• https://avvv.io/

Telegram Bots to buy energy 🔋

- @zuuuio_bot
- @TRX_3Bot
- @shengxin888bot
- @balanengliangbot
- @guccl_bot
- @AAAAATRXBOT
- @tchangebot
- @TRXTRX
- @shenzhoutrxbot
- @fuktrx_bot
- @hwtrcbot
- Buy-Energy-Bot
- Brutus Energy Bot
- @TRON_energy_bot
- @nengliangvipBot
- TRXEnergyMarket Bot
- @BuyEnergyTronsave_bot
- @SuperXCoinBot
- @AvvvioBot
- @savetron_bot

Important warning: use the above websites or Telegram bots with your own responsibility, We TronLink will not be responsible for anything

1. Scammers will message you as soon as you joined

2. Scammers are using the same  profile picture of that original real admin, if anyone messages you first and offers you help must be a scammer, real admin never message you first

3. 🙆‍♂🙆‍♂if any scammer message you then,  immediately forward 1 message of that scammer to this group 🙆‍♂🙆‍♂

4. 😡😡😡Never share your 12 words mnemonic phrase or private key to anyone in the world 😡😡😡

5. 😡😡😡 All USDT mining and high daily return promising investments are scams,  Never use such websites 😡😡😡

There is no way to recover your lost money, Reinstall tronlink and create a new wallet and use it

If you need a legitimate investment platform then follow
https://youtu.be/rH7_1ElYlQA

6. What are Energy and bandwidth  👉   https://t.me/TronLink/803902

Handpicked:
Popular dapp websites 🎉 🎉 🎉 

Tron Perpetual Future Trading ☀️☀️
No KYC needed - Trade Bitcoin, Tron,  Ethereum, Sol, XRP, BNB, etc....

Sunperp.com

Meme trading 

https://sunpump.meme/


Free wallet Notification bot

@TronNoteebot

Get your wallet notification in Telegram for the incoming outgoing, staking unstaking delegate reclaim approval activities 

Important warning, we tronlink has no responsibility on what website you use on tronlink, use any website on tronlink with your own responsibility

**Comment by kkimhau491-hash** [comment]
https://github.com/RikkaApps/Shizuku/issues/83 free free max ghim đầu

**Comment by kkimhau491-hash** [comment]
> 100% chance of getting a soft reboot when I'm trying to uninstall shizuku, Hope it can be fixed
> 
> Device: OnePlus 7 Pro Android Version: 10 Shizuku State: Deactivated(Not working) Device Owner(APP): Island
Free free max ghim đầu

**Comment by kkimhau491-hash** [comment]
> Owner free max ghim đầu aim bot

**Comment by jhajhariasamjhaie-bit** [comment]
**jiv**

**Comment by Silver0707** [comment]
> 100% chance of getting a soft reboot when I'm trying to uninstall shizuku, Hope it can be fixed
> 
> ----
> Device: OnePlus 7 Pro
> Android Version: 10
> Shizuku State: Deactivated(Not working)
> Device Owner(APP): Island
>

**Comment by mdsourov7744** [comment]
Bvhttps://github.com/RikkaApps/Shizuku/issues/83

**Comment by qwertyuiajhf-lgtm** [comment]
private void onRequestPermissionsResult(int requestCode, int grantResult) {
    boolean granted = grantResult == PackageManager.PERMISSION_GRANTED;
    // Do stuff based on the result and the request code
}

private final Shizuku.OnRequestPermissionResultListener REQUEST_PERMISSION_RESULT_LISTENER = this::onRequestPermissionsResult;

@Override
protected void onCreate(Bundle savedInstanceState) {
    // ...
    Shizuku.addRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER);
    // ...
}

@Override
protected void onDestroy() {
    // ...
    Shizuku.removeRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER);
    // ...
}

private boolean checkPermission(int code) {
  if (Shizuku.isPreV11()) {
    // Pre-v11 is unsupported
    return false;
  }

  if (Shizuku.checkSelfPermission() == PackageManager.PERMISSION_GRANTED) {
    // Granted
    return true;
  } else if (Shizuku.shouldShowRequestPermissionRationale()) {
    // Users choose "Deny and don't ask again"
    return false;
  } else {
    // Request the permission
    Shizuku.requestPermission(code);
    return false;
  }
}

**Comment by sfdssfccxsrfvc-ship-it** [comment]
H b i

**Comment by Ojaidi000** [comment]
> private void onRequestPermissionsResult(int requestCode, int grantResult) { boolean granted = grantResult == PackageManager.PERMISSION_GRANTED; // Do stuff based on the result and the request code }
> 
> private final Shizuku.OnRequestPermissionResultListener REQUEST_PERMISSION_RESULT_LISTENER = this::onRequestPermissionsResult;
> 
> [@OverRide](https://github.com/OverRide) protected void onCreate(Bundle savedInstanceState) { // ... Shizuku.addRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER); // ... }
> 
> [@OverRide](https://github.com/OverRide) protected void onDestroy() { // ... Shizuku.removeRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER); // ... }
> 
> private boolean checkPermission(int code) { if (Shizuku.isPreV11()) { // Pre-v11 is unsupported return false; }
> 
> if (Shizuku.checkSelfPermission() == PackageManager.PERMISSION_GRANTED) { // Granted return true; } else if (Shizuku.shouldShowRequestPermissionRationale()) { // Users choose "Deny and don't ask again" return false; } else { // Request the permission Shizuku.requestPermission(code); return false; } }

**Comment by tobokalovesengeldi506-cell** [comment]
> reboot

https://github.com/RikkaApps/Shizuku/issues/83#issue-705466391

**Comment by maulanajeandrian-design** [comment]
Cara bisa star gimana

**Comment by marmarboy32-cloud** [comment]
adb shell /data/app/~~vFKgsqS5126ODvE-I8jokg==/moe.shizuku.privileged.api-nJBAUEVce5bIVGr5AkwJNw==/lib/arm64/libshizuku.soadb shell /data/app/~~vFKgsqS5126ODvE-I8jokg==/moe.shizuku.privileged.api-nJBAUEVce5bIVGr5AkwJNw==/lib/arm64/libshizuku.soadb shell /data/app/~~vFKgsqS5126ODvE-I8jokg==/moe.shizuku.privileged.api-nJBAUEVce5bIVGr5AkwJNw==/lib/arm64/libshizuku.so

**Comment by marmarboy32-cloud** [comment]
### 

> _****_

**Comment by muhtarovajasmin-droid** [comment]
Hh

**Comment by muhtarovajasmin-droid** [comment]
Duplicate of #586

**Comment by moomhanse-sys** [comment]
https://github.com/RikkaApps/Shizuku/issues/83#issuecomment-3001331276

**Comment by mmoe61684-ui** [comment]
adb shell /data/app/~~tTlfMowEWK8-6qyt_SzWZA==/moe.shizuku.privileged.api-n6PhztPMpKSB7lbzesEANg==/lib/arm64/libshizuku.so

**Comment by mmoe61684-ui** [comment]
### 9999

**Comment by kauamurilo865-hash** [comment]
private static final IPackageManager PACKAGE_MANAGER = IPackageManager.Stub.asInterface(
    new ShizukuBinderWrapper(SystemServiceHelper.getSystemService("package")));

public static void grantRuntimePermission(String packageName, String permissionName, int userId) {
    try {
        PACKAGE_MANAGER.grantRuntimePermission(packageName, permissionName, userId);
    } catch (RemoteException tr) {
        throw new RuntimeException(tr.getMessage(), tr);
    }
}

**Comment by Flako35CDN** [comment]
> 100% chance of getting a soft reboot when I'm trying to uninstall shizuku, Hope it can be fixed
> 
> Device: OnePlus 8 Pro Android Version: 10 Shizuku State: Deactivated(Not working) Device Owner(APP): Island

**Comment by akshaysubin100-svg** [comment]
> 100% chance of getting a soft reboot when I'm trying to uninstall shizuku, Hope it can be fixed
> 
> Device: OnePlus 7 Pro Android Version: 10 Shizuku State: Deactivated(Not working) Device Owner(APP): Island

**Comment by lambi28904-glitch** [comment]
shared/src/main/java/moe/shizuku/server/ServerConstants.java

**Comment by mk1484409-gif** [comment]
private void onRequestPermissionsResult(int requestCode, int grantResult) {
    boolean granted = grantResult == PackageManager.PERMISSION_GRANTED;
    // Do stuff based on the result and the request code
}

private final Shizuku.OnRequestPermissionResultListener REQUEST_PERMISSION_RESULT_LISTENER = this::onRequestPermissionsResult;

@Override
protected void onCreate(Bundle savedInstanceState) {
    // ...
    Shizuku.addRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER);
    // ...
}

@Override
protected void onDestroy() {
    // ...
    Shizuku.removeRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER);
    // ...
}

private boolean checkPermission(int code) {
  if (Shizuku.isPreV11()) {
    // Pre-v11 is unsupported
    return false;
  }

  if (Shizuku.checkSelfPermission() == PackageManager.PERMISSION_GRANTED) {
    // Granted
    return true;
  } else if (Shizuku.shouldShowRequestPermissionRationale()) {
    // Users choose "Deny and don't ask again"
    return false;
  } else {
    // Request the permission
    Shizuku.requestPermission(code);
    return false;
  }
}

> _<provider
    android:name="rikka.shizuku.ShizukuProvider"
    android:authorities="${applicationId}.shizuku"
    android:multiprocess="false"
    android:enabled="true"
    android:exported="true"
    android:permission="android.permission.INTERACT_ACROSS_USERS_FULL" />

private void onRequestPermissionsResult(int requestCode, int grantResult) {
    boolean granted = grantResult == PackageManager.PERMISSION_GRANTED;
    // Do stuff based on the result and the request code
}

private final Shizuku.OnRequestPermissionResultListener REQUEST_PERMISSION_RESULT_LISTENER = this::onRequestPermissionsResult;

@Override
protected void onCreate(Bundle savedInstanceState) {
    // ...
    Shizuku.addRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER);
    // ...
}

@Override
protected void onDestroy() {
    // ...
    Shizuku.removeRequestPermissionResultListener(REQUEST_PERMISSION_RESULT_LISTENER);
    // ...
}

private boolean checkPermission(int code) {
  if (Shizuku.isPreV11()) {
    // Pre-v11 is unsupported
    return false;
  }

  if (Shizuku.checkSelfPermission() == PackageManager.PERMISSION_GRANTED) {
    // Granted
    return true;
  } else if (Shizuku.shouldShowRequestPermissionRationale()) {
    // Users choose "Deny and don't ask again"
    return false;
  } else {
    // Request the permission
    Shizuku.requestPermission(code);
    return false;
  }
}_

**Comment by kraj966091-cyber** [comment]
> 100% chance of getting a soft reboot when I'm trying to uninstall shizuku, Hope it can be fixed
> 
> Device: OnePlus 7 Pro Android Version: 10 Shizuku State: Deactivated(Not working) Device Owner(APP): Island

**Comment by syfjmyl512-ui** [comment]
لايك تسجيل الدخول في هو انستا
