### ISSUE TITLE
Able to run in DPC mode

### ISSUE THREAD

**Issue by mailinglists35** [RikkaApps/Shizuku#91]
is this technically possible?

kind of like Ice Box does it.

this way I could run ice box in shizuku mode and make shizuku the device owner app

thanks!

**Comment by RikkaW** [comment]
The permission of Device (profile) owner is so limited and it's completely different from the current (user apps must change, this is also unacceptable).

**Comment by dontknowhy** [comment]
@RikkaW 
can DPM turn on the wireless adb?
my honor device can't turn wireless adb on(the developer option doesn't have any update Since Android 8.1(doesn't have any code pairing option,i even need a normal adb to turn wireless adb on))
