### ISSUE TITLE
Is this possible to access inside /Android?

### ISSUE THREAD

**Issue by sleeping-player** [RikkaApps/Shizuku#95]
I'm sorry I can't recognize this even by looking at the docs as I'm not a developer. I can't find if this API exists.

**Comment by RikkaW** [comment]
ADB (and root, of course) does have such permission to access the Android folder (if your "/Android" means this).

It almost impossible to provide file-related APIs that cover every requirement, so there are no file APIs. However, "UserService" gives the developer the ability to run the app's code under root or adb, it's very easy to implement file-related APIs by themself.
