### ISSUE TITLE
Breaks LADB

### ISSUE THREAD

**Issue by brian6932** [RikkaApps/Shizuku#98]
LADB requires you to force stop Shizuku to actually be able to use it, if you don't you get an infinite loading screen https://github.com/tytydraco/LADB

LADB's dev is aware of this:
![image](https://user-images.githubusercontent.com/18603393/110271382-e8f29a00-7f95-11eb-8afa-2a2ab193d337.png)

**Comment by RikkaW** [comment]
I can't resurface the "problem". I believe it's a problem of LADB.

In addition, Shizuku does not do anything that blocks other connections 🙃.

![image](https://user-images.githubusercontent.com/12999176/110273831-6820b600-8008-11eb-9894-cdffb0b3bed1.png)

**Comment by tytydraco** [comment]
> I can't resurface the "problem". I believe it's a problem of LADB.
> 
> In addition, Shizuku does not do anything that blocks other connections 🙃.
> 
> 🙃:
> LADB: bundle an adb binary and sell for money
> Shizuku: implement a subset of adb protocol
> This money is too easy to earn
> 
> ![image](https://user-images.githubusercontent.com/12999176/110273831-6820b600-8008-11eb-9894-cdffb0b3bed1.png)

Sorry, allow me to clarify. Shizuku doesn't intentionally block the connection, but the Android device can only have one active ADB connection at once. It can either only be ADB or Shizuku. It's nobody's fault except the devices. 

Also, I don't think it's fair to say Shizuku and LADB do the same thing. My app focused on simply giving an end user access to the ADB binary. Shizuku is a backend framework for developers go give permissions to apps.

Money shouldn't be brought into it. My app is open source, users can compile it for free if they like. It's just a way for me to support myself for college.

**Comment by qinlili23333** [comment]
![Screenshot_20210309-111124357](https://user-images.githubusercontent.com/24567775/110413082-3b33d800-80c8-11eb-9efe-7a95061d2951.jpg)
On my device LADB can work while Shizuku running.
-Zenfone6 Android11

**Comment by RikkaW** [comment]
@tytydraco 
> but the Android device can only have one active ADB connection at once.

I believe there is no such limitation (I have also tested with "traditional wireless adb", adb tcpip).

![Screenshot_20210309-111350~2](https://user-images.githubusercontent.com/12999176/110413350-ab425e00-80c8-11eb-92bb-a05339783582.png)

**Comment by RikkaW** [comment]
@tytydraco Tested with Android 9, also works with multiple connections.

I found when use adb to connect self, `adb devices` may also show an emulator device.
```
$ ./adb devices
List of devices attached
192.168.0.116:5555      device
emulator-5554   device
```
Maybe this is the reason 🤔.

**Comment by tytydraco** [comment]
> @tytydraco Tested with Android 9, also works with multiple connections.
> 
> I found when use adb to connect self, `adb devices` may also show an emulator device.
> 
> ```
> $ ./adb devices
> List of devices attached
> 192.168.0.116:5555      device
> emulator-5554   device
> ```
> 
> Maybe this is the reason 🤔.

That has been an issue for me previously. Maybe it has come back again. Thank you for the debugging ❤️

**Comment by RikkaW** [comment]
@tytydraco Always use `adb -s` can bypass this problem .

**Comment by tytydraco** [comment]
> @tytydraco Always use `adb -s` can bypass this problem 😋.

Well -s requires a serial right? I guess a way that I could get around that would be to parse `adb devices` output and remove entries that classify as an emulator. That leaves problems if there are other connections, so I may then have to pick the topmost device. Unless there is a way to get the ADB serial from the device itself. I can get the serial using Android APIs but Q needs extra permissions. I wonder if there is another way you know of?

**Comment by haruue** [comment]
> Well -s requires a serial right?
adb -s can also be used with the `ip:port` pair such as `127.0.0.1:12345` after the wireless adb connection is obtained.

**Comment by tytydraco** [comment]
> > Well -s requires a serial right?
> 
> adb -s can also be used with the `ip:port` pair such as `127.0.0.1:12345` after the wireless adb connection is obtained.

Just worked with this, looked promising but I believe I found a cleaner solution using transport IDs. Specifying `-t 1` should choose the functional device, not the emulator. In testing, regardless if I specify 1 or 2, the device connects properly, even when the emulator is connected. The only downside is that it takes slightly longer than usual to connect.
